import { QUICK7_DISPLAY_TITLE } from "@/app/quick-7/display-title";
import type { TopicSeed } from "./topic-types";

export const QUICK7_CALCULATOR_NAME = QUICK7_DISPLAY_TITLE;

/** 第 7 台 mini-blog：車貸路線 vs 直接投入全球股市（slug 保留以維持既有 URL） */
export const QUICK7_TOPIC_SEEDS: TopicSeed[] = [
  {
    slug: "quick7-leverage-choice-mortgage-vs-global-stocks",
    title: `💣 ${QUICK7_DISPLAY_TITLE}｜先看月付，再看長期差距`,
    subtitle: "你不是在選車款，你是在選現金流版本。",
    seoTitle: `${QUICK7_DISPLAY_TITLE}教學｜車貸路線與全球股市路線比較`,
    metaDescription: "第七台聚焦車貸與全球股市投入比較，用同一時間軸看清月付壓力與長期資產差異。",
    focus: QUICK7_DISPLAY_TITLE,
    keywordA: "車貸和存股怎麼選",
    keywordB: "買車還是投資ETF",
    keywordC: "車貸現金流試算",
    closeQuestion: "這台車的月付，會不會讓你停不下來的定期定額？",
    calculatorRoute: "/quick-7",
    calculatorName: QUICK7_CALCULATOR_NAME,
    calculatorNote: "把車貸與全球股市放在同一張時間軸。先看月付，再看結清後的長期差距。",
  },
  {
    slug: "quick7-rent-or-buy-global-portfolio-balance",
    title: "現金買車、車貸，還是先存股？三條路怎麼比",
    subtitle: "先算每月還得動，再談哪條比較帥。",
    seoTitle: `現金買車還是車貸？${QUICK7_DISPLAY_TITLE}平衡法`,
    metaDescription: "用第七台比較現金購車、車貸與先投資全球股市，避免只靠「先開再說」。",
    focus: "購車方式與投資平衡",
    keywordA: "現金買車還是貸款",
    keywordB: "買車存股平衡",
    keywordC: "購車投資取捨",
    closeQuestion: "你追的是馬上開走，還是長期資產彈性？",
    calculatorRoute: "/quick-7",
    calculatorName: QUICK7_CALCULATOR_NAME,
  },
  {
    slug: "quick7-mortgage-term-20-vs-30-impact",
    title: "車貸 3 年、5 年、7 年，差的不只總利息",
    subtitle: "期數越長，月付越輕，但投資可能晚很久才開始。",
    seoTitle: `車貸年限怎麼選？${QUICK7_DISPLAY_TITLE}比較`,
    metaDescription: "比較不同車貸年限對月現金流與結清後投資彈性的影響，找出你能長期執行的版本。",
    focus: "車貸年限選擇",
    keywordA: "車貸3年5年差別",
    keywordB: "車貸期數怎麼選",
    keywordC: "車貸與投資彈性",
    closeQuestion: "你要的是月付輕鬆，還是早點把錢拿去滾？",
    calculatorRoute: "/quick-7",
    calculatorName: QUICK7_CALCULATOR_NAME,
  },
  {
    slug: "quick7-down-payment-vs-dca-global-etf",
    title: "頭期款先付滿，還是留錢分批投全球 ETF？",
    subtitle: "車可以晚一點買，複利不會等你。",
    seoTitle: `頭期款買車還是投資？${QUICK7_DISPLAY_TITLE}`,
    metaDescription: "比較頭期款一次付清與分批投入全球 ETF 的差異，看懂購車的機會成本。",
    focus: "頭期款對分批投入",
    keywordA: "頭期款買車還是投資",
    keywordB: "買車頭期機會成本",
    keywordC: "分批投入全球ETF",
    closeQuestion: "你比較想早點上路，還是早點讓資產上路？",
    calculatorRoute: "/quick-7",
    calculatorName: QUICK7_CALCULATOR_NAME,
  },
  {
    slug: "quick7-rate-hike-risk-check",
    title: "車貸利率調高了，你的購車計畫還撐得住嗎？",
    subtitle: "先想逆風，不是悲觀，是別被業代帶節奏。",
    seoTitle: `車貸利率上升怎麼辦？${QUICK7_DISPLAY_TITLE}風險檢查`,
    metaDescription: "透過第七台檢查升息或利率調整下的月付承受度，避免購車後投資歸零。",
    focus: "車貸升息風險",
    keywordA: "車貸利率上升怎麼辦",
    keywordB: "車貸利率試算",
    keywordC: "購車壓力管理",
    closeQuestion: "你的計畫只在低利率時才合理嗎？",
    calculatorRoute: "/quick-7",
    calculatorName: QUICK7_CALCULATOR_NAME,
  },
  {
    slug: "quick7-single-income-mortgage-survival-map",
    title: "單薪族背車貸，怎樣才不會每月都在硬撐？",
    subtitle: "先活得下去，才有資格談存股。",
    seoTitle: `單薪車貸壓力怎麼解？${QUICK7_DISPLAY_TITLE}生存地圖`,
    metaDescription: "給單薪族的車貸與投資平衡框架，避免高月付導致定期定額中斷。",
    focus: "單薪車貸生存地圖",
    keywordA: "單薪買車貸款壓力",
    keywordB: "單薪購車規劃",
    keywordC: "車貸與存股平衡",
    closeQuestion: "你的月付，還留得出投資空間嗎？",
    calculatorRoute: "/quick-7",
    calculatorName: QUICK7_CALCULATOR_NAME,
  },
  {
    slug: "quick7-double-income-home-invest-strategy",
    title: "雙薪家庭買車＋存股，先對齊哪三個數字？",
    subtitle: "一台車會吃掉兩個人的現金流預算。",
    seoTitle: `雙薪家庭買車又投資？${QUICK7_DISPLAY_TITLE}策略`,
    metaDescription: "第七台提供雙薪家庭對齊思路，整合車貸月付與全球股市投入節奏。",
    focus: "雙薪購車投資策略",
    keywordA: "雙薪家庭買車投資",
    keywordB: "夫妻車貸存股規劃",
    keywordC: "家庭理財對齊",
    closeQuestion: "你們是在選車，還是在選未來三年的現金流？",
    calculatorRoute: "/quick-7",
    calculatorName: QUICK7_CALCULATOR_NAME,
  },
  {
    slug: "quick7-bonus-prepay-or-invest-global",
    title: "有獎金時，先提前還車貸還是加碼全球股市？",
    subtitle: "別急著選邊，先看你想買什麼。",
    seoTitle: `獎金先還車貸還是投資？${QUICK7_DISPLAY_TITLE}教學`,
    metaDescription: "比較獎金提前清車貸與加碼投資兩種路線，協助做出更有依據的配置。",
    focus: "獎金配置抉擇",
    keywordA: "獎金先還車貸還是投資",
    keywordB: "提前還車貸還是ETF",
    keywordC: "獎金理財分配",
    closeQuestion: "這筆獎金，你想買的是無債，還是時間？",
    calculatorRoute: "/quick-7",
    calculatorName: QUICK7_CALCULATOR_NAME,
  },
  {
    slug: "quick7-liquidity-buffer-before-leverage",
    title: "辦車貸前先留現金緩衝，真的很重要",
    subtitle: "你不是怕買車，你是怕沒彈性。",
    seoTitle: `買車前需要多少緩衝金？${QUICK7_DISPLAY_TITLE}提醒`,
    metaDescription: "說明購車貸款前建立流動性緩衝的必要性，降低月付壓力導致計畫中斷。",
    focus: "購車前流動性緩衝",
    keywordA: "買車前要留多少現金",
    keywordB: "購車緩衝金規劃",
    keywordC: "車貸風險控管",
    closeQuestion: "你的計畫有預留修車、保險與失業空檔嗎？",
    calculatorRoute: "/quick-7",
    calculatorName: QUICK7_CALCULATOR_NAME,
  },
  {
    slug: "quick7-home-ownership-hidden-costs",
    title: "買車後最容易忽略的隱形成本清單",
    subtitle: "付得起頭期，不代表養得起。",
    seoTitle: `養車隱形成本有哪些？${QUICK7_DISPLAY_TITLE}完整檢查`,
    metaDescription: "整理牌照稅、保險、保養、油耗等持有成本，協助建立更貼近真實的車貸路線。",
    focus: "養車隱形成本",
    keywordA: "養車隱形成本",
    keywordB: "汽車持有成本",
    keywordC: "車貸總成本",
    closeQuestion: "你現在算的，是車價，還是每月養車帳？",
    calculatorRoute: "/quick-7",
    calculatorName: QUICK7_CALCULATOR_NAME,
  },
  {
    slug: "quick7-property-concentration-risk",
    title: "資產都卡在車上，風險真的有那麼大嗎？",
    subtitle: "車會折舊，現金流卻是每天發生。",
    seoTitle: `汽車資產集中風險？${QUICK7_DISPLAY_TITLE}配置提醒`,
    metaDescription: "用第七台對照「重車輕股」與持續投入全球股市，看懂流動性與折舊差異。",
    focus: "購車資產集中",
    keywordA: "買車佔收入太高",
    keywordB: "汽車折舊風險",
    keywordC: "車貸ETF平衡",
    closeQuestion: "你的淨值，會不會被一台車綁死？",
    calculatorRoute: "/quick-7",
    calculatorName: QUICK7_CALCULATOR_NAME,
  },
  {
    slug: "quick7-bear-market-while-paying-mortgage",
    title: "繳車貸同時遇股市下跌，該怎麼守住存股紀律？",
    subtitle: "雙重壓力時，最怕亂停扣。",
    seoTitle: `車貸期遇股災怎麼辦？${QUICK7_DISPLAY_TITLE}應對`,
    metaDescription: "模擬繳車貸又遇市場修正的決策框架，降低恐慌式停扣或賣在低點。",
    focus: "車貸期遇股災",
    keywordA: "繳車貸股市下跌",
    keywordB: "雙重壓力理財",
    keywordC: "逆風存股策略",
    closeQuestion: "逆風來時，你知道先砍哪一項支出嗎？",
    calculatorRoute: "/quick-7",
    calculatorName: QUICK7_CALCULATOR_NAME,
  },
  {
    slug: "quick7-career-uncertainty-and-mortgage",
    title: "職涯不確定時，還適合背車貸嗎？",
    subtitle: "承諾不是越長越好，是越能扛越好。",
    seoTitle: `工作不穩還能貸款買車嗎？${QUICK7_DISPLAY_TITLE}風險管理`,
    metaDescription: "針對收入不確定族群，提供車貸與投資並行時的風險管理邏輯。",
    focus: "職涯不確定與車貸",
    keywordA: "工作不穩能買車嗎",
    keywordB: "車貸承諾風險",
    keywordC: "收入波動購車",
    closeQuestion: "你的月付，跟收入波動匹配嗎？",
    calculatorRoute: "/quick-7",
    calculatorName: QUICK7_CALCULATOR_NAME,
  },
  {
    slug: "quick7-inflation-and-mortgage-choice",
    title: "通膨下還要買新車嗎？先算真實壓力",
    subtitle: "不是通膨本身，關鍵是你的月付體質。",
    seoTitle: `通膨下買車划算嗎？${QUICK7_DISPLAY_TITLE}分析`,
    metaDescription: "比較通膨情境下車貸與先投資路線差異，避免單一論點誤導購車決策。",
    focus: "通膨與購車抉擇",
    keywordA: "通膨下買車划算嗎",
    keywordB: "通膨理財購車",
    keywordC: "車貸存股比較",
    closeQuestion: "你在對抗通膨，還是在放大月付？",
    calculatorRoute: "/quick-7",
    calculatorName: QUICK7_CALCULATOR_NAME,
  },
  {
    slug: "quick7-global-diversification-vs-local-home-bias",
    title: "想買國產／進口車很正常，但別把投資也鎖在本地",
    subtitle: "熟悉感不等於風險更低。",
    seoTitle: `買車情緒怎麼平衡全球分散？${QUICK7_DISPLAY_TITLE}`,
    metaDescription: "用第七台對照「先滿足用車」與「持續全球分散投入」，提升配置決策品質。",
    focus: "購車情緒與全球分散",
    keywordA: "買車衝動理財",
    keywordB: "全球分散投資",
    keywordC: "車貸與ETF配置",
    closeQuestion: "你的決策，來自試算還是業代話術？",
    calculatorRoute: "/quick-7",
    calculatorName: QUICK7_CALCULATOR_NAME,
  },
  {
    slug: "quick7-retire-with-mortgage-plan",
    title: "退休前還在繳車貸，一定不行嗎？",
    subtitle: "關鍵不在有沒有貸款，而在月付可承受度。",
    seoTitle: `退休前車貸沒清怎麼規劃？${QUICK7_DISPLAY_TITLE}路線`,
    metaDescription: "說明退休前仍有車貸時如何重整現金流與投資節奏，降低焦慮。",
    focus: "退休前車貸",
    keywordA: "退休前車貸沒清",
    keywordB: "退休購車規劃",
    keywordC: "退休現金流管理",
    closeQuestion: "你想追求無貸款形式，還是可持續退休現金流？",
    calculatorRoute: "/quick-7",
    calculatorName: QUICK7_CALCULATOR_NAME,
  },
  {
    slug: "quick7-asset-rebalance-after-home-buy",
    title: "買車後要不要重配資產？很多人都忽略了",
    subtitle: "車進來後，流動性結構其實已經變了。",
    seoTitle: `買車後資產配置怎麼調？${QUICK7_DISPLAY_TITLE}重配建議`,
    metaDescription: "提供購車後資產重平衡方向，避免過度集中在折舊資產與固定月付。",
    focus: "買車後資產重配",
    keywordA: "買車後資產配置",
    keywordB: "汽車佔比太高怎麼辦",
    keywordC: "投資組合重平衡",
    closeQuestion: "你有把『買車後的新月付』算進配置嗎？",
    calculatorRoute: "/quick-7",
    calculatorName: QUICK7_CALCULATOR_NAME,
  },
  {
    slug: "quick7-upgrade-home-vs-upgrade-portfolio",
    title: "換新車還是加碼投資組合，哪個先？",
    subtitle: "每次升級，都有一個看不見的機會成本。",
    seoTitle: `換車還是加碼投資？${QUICK7_DISPLAY_TITLE}比較`,
    metaDescription: "比較換車升級與投資升級兩種路線，釐清生活與資產優先序。",
    focus: "換車vs加碼投資",
    keywordA: "換車還是加碼投資",
    keywordB: "換車機會成本",
    keywordC: "資產升級策略",
    closeQuestion: "這次升級，是買到便利，還是買到壓力？",
    calculatorRoute: "/quick-7",
    calculatorName: QUICK7_CALCULATOR_NAME,
  },
  {
    slug: "quick7-cashflow-first-paper-wealth-second",
    title: "帳面資產再漂亮，也比不上穩定現金流",
    subtitle: "車貸月付會先教會你這件事。",
    seoTitle: `為何現金流比帳面富有更重要？${QUICK7_DISPLAY_TITLE}`,
    metaDescription: "從第七台角度拆解月付與投資的落差，降低購車後的理財焦慮。",
    focus: "現金流優先",
    keywordA: "車貸現金流壓力",
    keywordB: "帳面富有但焦慮",
    keywordC: "可持續理財策略",
    closeQuestion: "你現在追求的是有車，還是活得有底氣？",
    calculatorRoute: "/quick-7",
    calculatorName: QUICK7_CALCULATOR_NAME,
  },
  {
    slug: "quick7-build-30year-leverage-discipline",
    title: "長期車貸＋存股紀律，不靠賭運氣，靠持續校正",
    subtitle: "不是一次選對車，而是每年都能調整。",
    seoTitle: `車貸與全球股市怎麼平衡？${QUICK7_DISPLAY_TITLE}框架`,
    metaDescription: "建立可持續的車貸與全球股市並行策略，讓你在不同階段都能穩定前進。",
    focus: "長期購車投資紀律",
    keywordA: "車貸存股長期平衡",
    keywordB: "購車投資紀律",
    keywordC: "車貸全球股市策略",
    closeQuestion: "你的策略，留了多少空間給未來的自己調整？",
    calculatorRoute: "/quick-7",
    calculatorName: QUICK7_CALCULATOR_NAME,
  },
];
