export type Quick1ExclusiveSection = {
  heading: string;
  paragraphs: string[];
  bullets?: string[];
};

export type Quick1ExclusivePost = {
  slug: string;
  title: string;
  subtitle: string;
  seoTitle: string;
  metaDescription: string;
  publishAtIso: string;
  calculatorRoute: "/quick-1" | "/quick-2" | "/quick-3" | "/quick-4" | "/quick-5" | "/quick-6" | "/quick-7" | "/quick-8" | "/quick-9" | "/quick-10";
  calculatorTitle: string;
  calculatorNote: string;
  sections: Quick1ExclusiveSection[];
  closeQuestion: string;
  disclaimer: string;
};

type TopicSeed = {
  slug: string;
  title: string;
  subtitle: string;
  seoTitle: string;
  metaDescription: string;
  focus: string;
  keywordA: string;
  keywordB: string;
  keywordC: string;
  closeQuestion: string;
  calculatorRoute?: "/quick-1" | "/quick-2" | "/quick-3" | "/quick-4" | "/quick-5" | "/quick-6" | "/quick-7" | "/quick-8" | "/quick-9" | "/quick-10";
  calculatorName?: string;
  calculatorNote?: string;
};

const PUBLISH_DATES = [
  "2026-05-04T09:00:00+08:00",
  "2026-05-16T09:00:00+08:00",
  "2026-05-28T09:00:00+08:00",
  "2026-06-09T09:00:00+08:00",
  "2026-06-21T09:00:00+08:00",
  "2026-07-03T09:00:00+08:00",
  "2026-07-15T09:00:00+08:00",
  "2026-07-27T09:00:00+08:00",
  "2026-08-08T09:00:00+08:00",
  "2026-08-20T09:00:00+08:00",
  "2026-09-01T09:00:00+08:00",
  "2026-09-13T09:00:00+08:00",
  "2026-09-25T09:00:00+08:00",
  "2026-10-07T09:00:00+08:00",
  "2026-10-19T09:00:00+08:00",
  "2026-10-31T09:00:00+08:00",
  "2026-11-12T09:00:00+08:00",
  "2026-11-24T09:00:00+08:00",
  "2026-12-06T09:00:00+08:00",
  "2026-12-18T09:00:00+08:00",
  "2026-12-30T09:00:00+08:00",
  "2027-01-11T09:00:00+08:00",
  "2027-01-23T09:00:00+08:00",
  "2027-02-04T09:00:00+08:00",
  "2027-02-16T09:00:00+08:00",
  "2027-02-28T09:00:00+08:00",
  "2027-03-12T09:00:00+08:00",
  "2027-03-24T09:00:00+08:00",
  "2027-04-05T09:00:00+08:00",
  "2027-04-17T09:00:00+08:00",
  "2027-04-29T09:00:00+08:00",
  "2027-05-11T09:00:00+08:00",
  "2027-05-23T09:00:00+08:00",
  "2027-06-04T09:00:00+08:00",
  "2027-06-16T09:00:00+08:00",
  "2027-06-28T09:00:00+08:00",
  "2027-07-10T09:00:00+08:00",
  "2027-07-22T09:00:00+08:00",
  "2027-08-03T09:00:00+08:00",
  "2027-08-15T09:00:00+08:00",
  "2027-08-27T09:00:00+08:00",
  "2027-09-08T09:00:00+08:00",
  "2027-09-20T09:00:00+08:00",
  "2027-10-02T09:00:00+08:00",
  "2027-10-14T09:00:00+08:00",
  "2027-10-26T09:00:00+08:00",
  "2027-11-07T09:00:00+08:00",
  "2027-11-19T09:00:00+08:00",
] as const;

const QUICK2_PUBLISH_DATES: Record<string, string> = {
  "quick2-freedom-countdown-target-years": "2026-05-05T09:00:00+08:00",
  "quick2-monthly-40000-countdown": "2026-05-17T09:00:00+08:00",
  "quick2-monthly-50000-countdown": "2026-05-29T09:00:00+08:00",
  "quick2-monthly-60000-countdown": "2026-06-10T09:00:00+08:00",
  "quick2-raise-invest-or-extend-years": "2026-06-22T09:00:00+08:00",
  "quick2-first-10-years-gap": "2026-07-04T09:00:00+08:00",
  "quick2-salary-plateau-countdown": "2026-07-16T09:00:00+08:00",
  "quick2-double-income-household-target": "2026-07-28T09:00:00+08:00",
  "quick2-single-income-pressure-map": "2026-08-09T09:00:00+08:00",
  "quick2-bonus-allocation-countdown": "2026-08-21T09:00:00+08:00",
  "quick2-lifestyle-upgrade-warning": "2026-09-02T09:00:00+08:00",
  "quick2-early-retire-vs-slower-path": "2026-09-14T09:00:00+08:00",
  "quick2-bear-market-delay-check": "2026-09-26T09:00:00+08:00",
  "quick2-annual-review-reset-plan": "2026-10-08T09:00:00+08:00",
  "quick2-40000-to-60000-upgrade-roadmap": "2026-10-20T09:00:00+08:00",
  "quick2-starting-late-with-high-goal": "2026-11-01T09:00:00+08:00",
  "quick2-stress-free-monthly-input": "2026-11-13T09:00:00+08:00",
  "quick2-housing-cost-impact-countdown": "2026-11-25T09:00:00+08:00",
  "quick2-family-support-pressure": "2026-12-07T09:00:00+08:00",
  "quick2-side-income-accelerator": "2026-12-19T09:00:00+08:00",
};

const QUICK3_PUBLISH_DATES: Record<string, string> = {
  "quick3-dream-monthly-income-simulator": "2026-05-06T09:00:00+08:00",
  "quick3-monthly-30000-reverse-plan": "2026-05-18T09:00:00+08:00",
  "quick3-monthly-40000-reverse-plan": "2026-05-30T09:00:00+08:00",
  "quick3-monthly-50000-reverse-plan": "2026-06-11T09:00:00+08:00",
  "quick3-monthly-60000-reverse-plan": "2026-06-23T09:00:00+08:00",
  "quick3-how-much-per-month-for-15-years": "2026-07-05T09:00:00+08:00",
  "quick3-how-much-per-month-for-20-years": "2026-07-17T09:00:00+08:00",
  "quick3-how-much-per-month-for-25-years": "2026-07-29T09:00:00+08:00",
  "quick3-increase-goal-or-extend-years": "2026-08-10T09:00:00+08:00",
  "quick3-salary-growth-reverse-strategy": "2026-08-22T09:00:00+08:00",
  "quick3-single-income-reverse-plan": "2026-09-03T09:00:00+08:00",
  "quick3-double-income-reverse-plan": "2026-09-15T09:00:00+08:00",
  "quick3-bonus-topup-reverse-plan": "2026-09-27T09:00:00+08:00",
  "quick3-late-start-reverse-path": "2026-10-09T09:00:00+08:00",
  "quick3-inflation-adjusted-monthly-goal": "2026-10-21T09:00:00+08:00",
  "quick3-risk-buffer-before-goal-upgrade": "2026-11-02T09:00:00+08:00",
  "quick3-side-income-accelerate-goal": "2026-11-14T09:00:00+08:00",
  "quick3-annual-reset-reverse-checklist": "2026-11-26T09:00:00+08:00",
  "quick3-expense-cut-vs-income-rise": "2026-12-08T09:00:00+08:00",
  "quick3-avoid-overoptimistic-goal-gap": "2026-12-20T09:00:00+08:00",
};

const QUICK5_PUBLISH_DATES: Record<string, string> = {
  "quick5-principal-vs-compound-reality": "2026-05-08T09:00:00+08:00",
  "quick5-first-100k-snowball-start": "2026-05-20T09:00:00+08:00",
  "quick5-first-500k-compound-curve": "2026-06-01T09:00:00+08:00",
  "quick5-first-million-snowball-moment": "2026-06-13T09:00:00+08:00",
  "quick5-10year-vs-20year-gap": "2026-06-25T09:00:00+08:00",
  "quick5-20year-vs-30year-gap": "2026-07-07T09:00:00+08:00",
  "quick5-stop-investing-for-1year-impact": "2026-07-19T09:00:00+08:00",
  "quick5-small-increase-big-longterm-gap": "2026-07-31T09:00:00+08:00",
  "quick5-monthly-10000-vs-12000": "2026-08-12T09:00:00+08:00",
  "quick5-monthly-15000-vs-20000": "2026-08-24T09:00:00+08:00",
  "quick5-lump-sum-plus-monthly-plan": "2026-09-05T09:00:00+08:00",
  "quick5-bear-market-continue-or-stop": "2026-09-17T09:00:00+08:00",
  "quick5-inflation-vs-nominal-balance": "2026-09-29T09:00:00+08:00",
  "quick5-expense-growth-eats-snowball": "2026-10-11T09:00:00+08:00",
  "quick5-salary-growth-boost-compound": "2026-10-23T09:00:00+08:00",
  "quick5-risk-buffer-before-acceleration": "2026-11-04T09:00:00+08:00",
  "quick5-annual-rebalance-snowball-check": "2026-11-16T09:00:00+08:00",
  "quick5-dividend-reinvest-snowball": "2026-11-28T09:00:00+08:00",
  "quick5-why-time-beats-perfect-timing": "2026-12-10T09:00:00+08:00",
  "quick5-build-30year-snowball-habit": "2026-12-22T09:00:00+08:00",
};

const TOPIC_SEEDS: TopicSeed[] = [
  {
    slug: "quick1-monthly-20000-compound-playbook",
    title: "每月投入兩萬，20 年後會自由嗎？先把存股複利計算機打開再說",
    subtitle: "先把焦慮翻成數字，你會比昨天更靠近自由。",
    seoTitle: "每月投入兩萬 20 年後有多少？存股複利計算機複利試算與月領估算教學",
    metaDescription: "以存股複利計算機示範每月投入兩萬的複利路徑，從月投、年數到月領估算，幫你把理想變成可執行計畫。",
    focus: "每月投入兩萬",
    keywordA: "每月投入兩萬 20 年後有多少",
    keywordB: "定期定額多久能退休",
    keywordC: "複利計算器月領怎麼算",
    closeQuestion: "你會先調高月投入，還是先調高「不中斷投入」的穩定度？",
  },
  {
    slug: "quick1-first-million-discipline-map",
    title: "第一個一百萬不是天分題，是節奏題：用存股複利計算機把路線畫出來",
    subtitle: "你需要的不是神準預測，而是能活 10 年的投入節奏。",
    seoTitle: "第一桶金要多久？存股複利計算機解析每月投入與複利時間軸",
    metaDescription: "用存股複利計算機拆解第一桶金累積時間，實測不同月投入與年數設定，找到最能長期執行的版本。",
    focus: "第一桶金時間軸",
    keywordA: "第一桶金要多久",
    keywordB: "每月存多少可以到一百萬",
    keywordC: "複利計算器設定方式",
    closeQuestion: "你現在的月投入，是能做 36 個月的版本嗎？",
  },
  {
    slug: "quick1-retirement-monthly-cashflow-baseline",
    title: "退休月領怎麼抓才不自欺？先用存股複利計算機算出你的底線版本",
    subtitle: "退休不是喊口號，是每個月把底線往上墊高。",
    seoTitle: "退休月領金額如何估算？存股複利計算機實作月投與年數規劃",
    metaDescription: "從退休月領倒推月投入，利用存股複利計算機建立可執行的退休現金流底線，減少焦慮與瞎猜。",
    focus: "退休月領底線",
    keywordA: "退休月領金額如何估算",
    keywordB: "每月投入多少才有被動收入",
    keywordC: "退休試算怎麼做",
    closeQuestion: "你想要的是「不用上班」，還是「可以自由選工作」？",
  },
  {
    slug: "quick1-monthly-10000-vs-15000-gap",
    title: "月投一萬和一萬五，差在哪？不是 5000 而已",
    subtitle: "差距會被時間放大，重點是你願不願意看見它。",
    seoTitle: "月投一萬 vs 一萬五差多少？存股複利計算機比較 20 年資產差距",
    metaDescription: "比較月投一萬與一萬五在不同年數下的複利結果，搭配存股複利計算機找出你可負擔且有感的加碼策略。",
    focus: "月投級距比較",
    keywordA: "月投一萬和一萬五差多少",
    keywordB: "提高月投入有用嗎",
    keywordC: "複利差距比較",
    closeQuestion: "你現在可以多加多少，才不會讓生活直接失衡？",
  },
  {
    slug: "quick1-bonus-lump-sum-yearly-plan",
    title: "年終獎金該花掉還是加碼？用一個按鈕看 10 年差距",
    subtitle: "不是不能花，而是先算過再花。",
    seoTitle: "年終獎金投資怎麼分配？存股複利計算機看一次加碼的長期效果",
    metaDescription: "以存股複利計算機模擬年終加碼與不加碼兩種路線，幫你評估獎金分配和長期資產成長的關係。",
    focus: "年終獎金加碼",
    keywordA: "年終獎金要不要投資",
    keywordB: "一次加碼有用嗎",
    keywordC: "獎金投資規劃",
    closeQuestion: "今年的獎金，你要全部花掉，還是留一部分給未來的你？",
  },
  {
    slug: "quick1-salary-growth-stepup-plan",
    title: "加薪後月投該怎麼調？先調多少才不會三個月後崩掉",
    subtitle: "加薪不是全拿去升級消費，留一點給複利會很有感。",
    seoTitle: "加薪後要提高多少月投？存股複利計算機試算最穩升級幅度",
    metaDescription: "加薪後如何調整月投入才可持續？用存股複利計算機比較不同加碼比例，避免短期衝動長期斷線。",
    focus: "加薪後月投調整",
    keywordA: "加薪後月投要加多少",
    keywordB: "加薪理財分配",
    keywordC: "提高投入不痛苦方法",
    closeQuestion: "你會把加薪的幾成交給未來，而不是全部留給當下？",
  },
  {
    slug: "quick1-bear-market-keep-investing",
    title: "市場下跌還要繼續投入嗎？先別靠感覺，先看長線",
    subtitle: "最難的不是看懂走勢，是在波動裡保持節奏。",
    seoTitle: "股市下跌還要定期定額嗎？存股複利計算機看長期投入優勢",
    metaDescription: "面對市場回檔，透過存股複利計算機觀察持續投入與停扣的長期差異，建立可執行的抗波動策略。",
    focus: "下跌時持續投入",
    keywordA: "股市下跌還要定期定額嗎",
    keywordB: "停扣影響有多大",
    keywordC: "熊市投資心態",
    closeQuestion: "下次下跌來時，你要停手，還是照計畫慢慢買？",
  },
  {
    slug: "quick1-inflation-adjusted-goals",
    title: "你以為目標是 2000 萬？加上時間後可能根本不夠",
    subtitle: "目標不是固定數字，而是會隨時間變動的生活成本。",
    seoTitle: "退休目標金額怎麼抓？存股複利計算機搭配通膨思維調整目標",
    metaDescription: "用存股複利計算機先看資產路徑，再以通膨思維校正退休目標，避免只看名目數字造成判斷偏差。",
    focus: "目標金額校正",
    keywordA: "退休目標金額怎麼算",
    keywordB: "通膨下資產規劃",
    keywordC: "名目和實質差異",
    closeQuestion: "你的目標數字，有把未來的生活成本算進去嗎？",
  },
  {
    slug: "quick1-couple-joint-invest-plan",
    title: "伴侶理財常吵架？先用同一張圖看同一件事",
    subtitle: "不是誰對誰錯，而是你們看的是不同版本的未來。",
    seoTitle: "情侶夫妻如何一起投資？存股複利計算機建立共同月投計畫",
    metaDescription: "提供伴侶共同理財流程，透過存股複利計算機對齊月投入與年數期待，減少情緒衝突與目標落差。",
    focus: "伴侶共同規劃",
    keywordA: "夫妻理財怎麼分配",
    keywordB: "情侶共同投資規劃",
    keywordC: "家庭月投設定",
    closeQuestion: "你們吵的是錢，還是其實沒對齊同一個時間軸？",
  },
  {
    slug: "quick1-late-start-catchup-strategy",
    title: "30 歲才開始會太晚嗎？你真正需要的是追回路徑",
    subtitle: "晚開始不等於沒機會，怕的是晚開始又不開始。",
    seoTitle: "30 歲才開始投資來得及嗎？存股複利計算機追回策略教學",
    metaDescription: "針對晚起步族群，示範如何用存股複利計算機調整月投入與年數，建立可追趕但不爆壓的理財路線。",
    focus: "晚開始追趕",
    keywordA: "30歲開始投資來得及嗎",
    keywordB: "晚開始理財怎麼追",
    keywordC: "追趕複利策略",
    closeQuestion: "你要花時間後悔，還是花時間把路線追回來？",
  },
  {
    slug: "quick1-freelancer-irregular-income-plan",
    title: "收入不固定怎麼月投？接案族的穩定投入方法",
    subtitle: "不規律收入，也能做出有規律的投入。",
    seoTitle: "自由工作者如何定期定額？存股複利計算機設計彈性月投法",
    metaDescription: "給接案與收入波動族群的月投配置建議，透過存股複利計算機建立高低月雙版本，降低中斷機率。",
    focus: "不固定收入月投",
    keywordA: "收入不固定怎麼投資",
    keywordB: "接案族定期定額",
    keywordC: "彈性月投規劃",
    closeQuestion: "你的投資計畫，有替淡季預留呼吸空間嗎？",
  },
  {
    slug: "quick1-parenting-education-retire-balance",
    title: "有小孩後還能存退休嗎？先把兩個目標拆開算",
    subtitle: "教育金和退休金都重要，先排序就不會亂。",
    seoTitle: "有小孩怎麼規劃退休？存股複利計算機平衡教育金與退休金",
    metaDescription: "示範家庭在教育支出與退休準備並行時，如何用存股複利計算機設計雙軌月投與年期策略。",
    focus: "教育與退休平衡",
    keywordA: "有小孩怎麼存退休",
    keywordB: "教育金退休金分配",
    keywordC: "家庭理財月投",
    closeQuestion: "你家目前的理財順序，真的符合你們最在意的生活嗎？",
  },
  {
    slug: "quick1-debt-first-or-invest-first",
    title: "先還債還是先投資？不是二選一，重點在比例",
    subtitle: "極端答案很爽，但通常不適合真實生活。",
    seoTitle: "先還債還是先投資？存股複利計算機拆解現金流比例配置",
    metaDescription: "透過存股複利計算機模擬不同還債與月投比例，找出兼顧壓力管理與資產成長的務實解法。",
    focus: "還債投資比例",
    keywordA: "先還債還是先投資",
    keywordB: "負債時怎麼理財",
    keywordC: "現金流比例配置",
    closeQuestion: "你現在的分配，是在降低焦慮，還是在放大焦慮？",
  },
  {
    slug: "quick1-year-end-rebalance-checklist",
    title: "年底理財健檢怎麼做？每年一次就很有感",
    subtitle: "不用複雜，只要固定檢查三個數字。",
    seoTitle: "年底理財健檢清單：用存股複利計算機回顧月投與年數進度",
    metaDescription: "提供年度理財檢查流程，搭配存股複利計算機回顧月投入、年數進度與月領目標，建立長期迭代習慣。",
    focus: "年度健檢",
    keywordA: "年底理財健檢怎麼做",
    keywordB: "年度投資回顧",
    keywordC: "理財檢查清單",
    closeQuestion: "今年你的理財成績，是靠運氣還是靠流程？",
  },
  {
    slug: "quick1-emergency-fund-before-invest",
    title: "緊急預備金要先存嗎？先存多少才算夠",
    subtitle: "先把安全墊鋪好，投資才不會遇事就停。",
    seoTitle: "緊急預備金要存多少？存股複利計算機搭配安全墊與月投規劃",
    metaDescription: "說明緊急預備金與月投的先後與並行方式，透過存股複利計算機設計不易中斷的長期策略。",
    focus: "安全墊與月投",
    keywordA: "緊急預備金要存多少",
    keywordB: "先存錢還是先投資",
    keywordC: "預備金與月投比例",
    closeQuestion: "你現在的策略，遇到一次突發支出會不會整套中斷？",
  },
  {
    slug: "quick1-etf-dividend-reinvest-idea",
    title: "配息到底該花還是再投入？一個選擇，十年差很多",
    subtitle: "再投入不是神話，但長期很誠實。",
    seoTitle: "ETF 配息要花掉還是再投入？存股複利計算機看長期差異",
    metaDescription: "以存股複利計算機比較配息再投入與不再投入兩種路徑，協助你建立符合生活與目標的資金使用規則。",
    focus: "配息再投入",
    keywordA: "配息要不要再投入",
    keywordB: "ETF配息理財",
    keywordC: "再投入效果",
    closeQuestion: "你想要的是短期舒服，還是長期更有選擇權？",
  },
  {
    slug: "quick1-target-30000-passive-income",
    title: "目標月領 3 萬，月投要多少才比較有機會",
    subtitle: "先看到底線，再決定要加碼還是延長時間。",
    seoTitle: "月領 3 萬怎麼規劃？存股複利計算機倒推月投入與年期",
    metaDescription: "針對月領三萬元目標，利用存股複利計算機倒推所需月投入與年數，建立可執行退休現金流路線。",
    focus: "月領3萬倒推",
    keywordA: "月領三萬要存多少",
    keywordB: "被動收入三萬規劃",
    keywordC: "退休月領倒推",
    closeQuestion: "你會先提高投入，還是先延長計畫年期？",
  },
  {
    slug: "quick1-monthly-5min-review-system",
    title: "每月只花 5 分鐘，也能把理財做得很穩",
    subtitle: "不是你沒時間，是沒有固定節奏。",
    seoTitle: "每月理財回顧怎麼做？存股複利計算機 5 分鐘檢查流程",
    metaDescription: "建立每月五分鐘理財檢查習慣，透過存股複利計算機追蹤月投、年數與月領偏差，持續修正不焦慮。",
    focus: "每月5分鐘回顧",
    keywordA: "每月理財回顧流程",
    keywordB: "理財習慣怎麼養成",
    keywordC: "5分鐘檢查法",
    closeQuestion: "你願意每月固定 5 分鐘，換長期少很多焦慮嗎？",
  },
  {
    slug: "quick1-avoid-over-optimistic-return",
    title: "報酬率別一開始就填太高，這是最常見的自我欺騙",
    subtitle: "樂觀不是錯，但只用樂觀一定會痛。",
    seoTitle: "複利試算報酬率怎麼設定？存股複利計算機的保守中性樂觀三版法",
    metaDescription: "示範保守、中性、樂觀三組報酬率的試算方法，搭配存股複利計算機降低過度樂觀帶來的規劃失真。",
    focus: "報酬率三版法",
    keywordA: "複利報酬率怎麼設定",
    keywordB: "理財假設太樂觀",
    keywordC: "保守中性樂觀試算",
    closeQuestion: "你現在用的報酬率，是你希望的，還是你承受得了的？",
  },
  {
    slug: "quick1-build-30year-freedom-habit",
    title: "30 年自由不是一個決定，是一個可以活下去的習慣",
    subtitle: "先把節奏守住，時間自然會幫你放大結果。",
    seoTitle: "30 年財富自由路線圖：存股複利計算機建立長期投入習慣",
    metaDescription: "以存股複利計算機打造 30 年可持續投入習慣，從月投紀律到年期管理，建立穩定放大的資產引擎。",
    focus: "30年長期習慣",
    keywordA: "30年投資規劃",
    keywordB: "長期投入習慣",
    keywordC: "財富自由路線圖",
    closeQuestion: "你今天做的哪個小動作，能讓 10 年後的你說聲謝謝？",
  },
  {
    slug: "quick2-freedom-countdown-target-years",
    title: "💣 財富自由倒數計時器怎麼用？先算清楚你距離目標還有幾年",
    subtitle: "這台不是拿來做夢，是拿來把時間壓力說清楚。",
    seoTitle: "財富自由倒數計時器教學：目標月領與月投入怎麼設定才務實",
    metaDescription:
      "用第二台財富自由倒數計時器，從目標月領與每月投入倒推達標年數。適合想快速看清退休時間軸與調整方向的讀者。",
    focus: "財富自由倒數計時器",
    keywordA: "財富自由倒數計時器怎麼用",
    keywordB: "目標月領要設多少",
    keywordC: "每月投入幾年達成",
    closeQuestion: "你比較想先拉高月投入，還是先把目標月領調到能長期承受的版本？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
    calculatorNote: "先填目標月領，再填每月投入，直接看達標年數。先求可執行，再求速度。",
  },
  {
    slug: "quick2-monthly-40000-countdown",
    title: "月領 4 萬倒數怎麼抓？先看幾年達標，再談加碼",
    subtitle: "先把時間壓力看清楚，你就不會亂衝。",
    seoTitle: "月領 4 萬要幾年達成？財富自由倒數計時器實測",
    metaDescription: "透過財富自由倒數計時器，示範月領 4 萬目標下，月投入與達標年數的關係，快速找到可執行節奏。",
    focus: "月領4萬倒數",
    keywordA: "月領4萬要幾年",
    keywordB: "月投入和達標年數",
    keywordC: "退休倒數試算",
    closeQuestion: "你會先提高投入，還是先接受更長的時間軸？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-monthly-50000-countdown",
    title: "目標月領 5 萬，達標年數為何差這麼多？",
    subtitle: "同樣努力，不同起跑值，時間差可能很大。",
    seoTitle: "月領 5 萬需要多久？財富自由倒數計時器教學",
    metaDescription: "比較不同月投入下，月領 5 萬目標的達標時間，利用財富自由倒數計時器找到更務實路線。",
    focus: "月領5萬達標年",
    keywordA: "月領5萬多久達成",
    keywordB: "退休月領目標設定",
    keywordC: "達標時間比較",
    closeQuestion: "你現在的目標月領，是理想值還是可持續值？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-monthly-60000-countdown",
    title: "月領 6 萬不是不能追，先看你要拿什麼交換",
    subtitle: "時間、投入、生活壓力，三者一定要平衡。",
    seoTitle: "月領 6 萬怎麼規劃？財富自由倒數計時器倒推年數",
    metaDescription: "用財富自由倒數計時器分析月領 6 萬目標，評估不同投入對達標年數與壓力的影響。",
    focus: "月領6萬規劃",
    keywordA: "月領6萬怎麼達成",
    keywordB: "倒推達標年數",
    keywordC: "高月領規劃",
    closeQuestion: "你要更快，還是要更穩？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-raise-invest-or-extend-years",
    title: "該加碼還是延長年數？倒數計時器一看就懂",
    subtitle: "同一目標，不同策略，壓力感差很多。",
    seoTitle: "加碼月投或延長年數哪個好？財富自由倒數計時器比較",
    metaDescription: "比較『提高月投入』與『拉長年數』兩種策略，利用財富自由倒數計時器看哪個更符合你的生活。",
    focus: "加碼或延長",
    keywordA: "加碼還是延長年數",
    keywordB: "月投策略比較",
    keywordC: "達標策略選擇",
    closeQuestion: "你比較能承受短期壓力，還是長期等待？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-first-10-years-gap",
    title: "前 10 年最容易放棄：先把倒數做成可執行版本",
    subtitle: "不是你沒毅力，是設定太硬。",
    seoTitle: "前 10 年投資最難怎麼撐？財富自由倒數計時器思路",
    metaDescription: "用財富自由倒數計時器把目標拆小，降低前 10 年心理壓力，提高持續投入機率。",
    focus: "前10年持續",
    keywordA: "投資前10年怎麼撐",
    keywordB: "如何避免中途放棄",
    keywordC: "理財可執行版本",
    closeQuestion: "你現在的設定，是幫你前進，還是逼你放棄？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-salary-plateau-countdown",
    title: "薪水卡住怎麼辦？倒數計時器幫你重排路線",
    subtitle: "收入不變時，更要把時間與投入配好。",
    seoTitle: "薪水沒成長也能退休嗎？財富自由倒數計時器規劃法",
    metaDescription: "針對收入成長有限族群，示範如何用財富自由倒數計時器重排投入與年數，維持達標可能。",
    focus: "薪資停滯規劃",
    keywordA: "薪水不漲怎麼理財",
    keywordB: "收入停滯退休規劃",
    keywordC: "倒數計時器規劃",
    closeQuestion: "如果收入短期不變，你願意先調整哪個旋鈕？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-double-income-household-target",
    title: "雙薪家庭如何定目標月領？先把共同時間軸對齊",
    subtitle: "兩個人的投入節奏，必須用同一張圖討論。",
    seoTitle: "雙薪家庭退休目標怎麼抓？財富自由倒數計時器實作",
    metaDescription: "給雙薪家庭的倒數規劃範例，透過財富自由倒數計時器對齊目標月領、投入金額與達標時間。",
    focus: "雙薪目標對齊",
    keywordA: "雙薪家庭退休規劃",
    keywordB: "家庭目標月領設定",
    keywordC: "共同理財時間軸",
    closeQuestion: "你們現在的理財溝通，是在對齊目標還是在互相消耗？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-single-income-pressure-map",
    title: "單薪壓力很大？先用倒數計時器找到不爆表版本",
    subtitle: "先活得下去，才有機會走得下去。",
    seoTitle: "單薪族如何規劃退休？財富自由倒數計時器路線圖",
    metaDescription: "單薪族可用財富自由倒數計時器，找出不超壓的月投入與可接受達標年數，建立穩定路線。",
    focus: "單薪壓力地圖",
    keywordA: "單薪族退休規劃",
    keywordB: "單薪月投設定",
    keywordC: "壓力不爆表理財",
    closeQuestion: "你現在追的是速度，還是可持續？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-bonus-allocation-countdown",
    title: "有獎金時，倒數應該怎麼縮短才最有感？",
    subtitle: "一次加碼可以快，但要放在對的位置。",
    seoTitle: "獎金怎麼用能縮短退休年數？財富自由倒數計時器試算",
    metaDescription: "示範有獎金時如何用倒數計時器比較不同加碼策略，找到對達標年數最有感的配置。",
    focus: "獎金縮短倒數",
    keywordA: "獎金怎麼縮短退休",
    keywordB: "一次加碼怎麼配",
    keywordC: "達標年數縮短",
    closeQuestion: "你的獎金，想買當下快樂，還是買未來時間？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-lifestyle-upgrade-warning",
    title: "生活升級前先看倒數：別讓目標越來越遠",
    subtitle: "收入增加不代表你一定更接近自由。",
    seoTitle: "生活升級會拖慢退休嗎？財富自由倒數計時器提醒",
    metaDescription: "利用財富自由倒數計時器，在生活升級前先檢查達標年數變化，避免無感延後退休目標。",
    focus: "生活升級警訊",
    keywordA: "生活升級拖慢退休",
    keywordB: "收入增加卻沒存到錢",
    keywordC: "退休目標越來越遠",
    closeQuestion: "這次升級真的值得，還是只是習慣性加開銷？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-early-retire-vs-slower-path",
    title: "提早退休還是慢慢退？倒數計時器讓選擇更清楚",
    subtitle: "你不只在選年份，也在選生活節奏。",
    seoTitle: "提早退休可行嗎？財富自由倒數計時器比較快慢兩路",
    metaDescription: "比較激進與穩健兩種退休路線，透過財富自由倒數計時器看壓力與達標時間差距。",
    focus: "快慢路線比較",
    keywordA: "提早退休可行嗎",
    keywordB: "退休快慢路線",
    keywordC: "達標年數比較",
    closeQuestion: "你要的是最早退休，還是最穩退休？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-bear-market-delay-check",
    title: "市場下跌會讓倒數延長嗎？先把心理預期校正",
    subtitle: "知道會變慢，比突然受傷好太多。",
    seoTitle: "市場下跌退休倒數會延後嗎？財富自由倒數計時器示意",
    metaDescription: "用倒數計時器建立下跌情境心理預期，理解達標年數可能延長，減少恐慌式停扣。",
    focus: "下跌延長預期",
    keywordA: "市場下跌退休延後",
    keywordB: "下跌時怎麼維持投入",
    keywordC: "倒數延長怎麼辦",
    closeQuestion: "你有為逆風準備備案，還是只準備順風劇本？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-annual-review-reset-plan",
    title: "每年重算一次倒數，為什麼比你想像更重要",
    subtitle: "不重算，計畫就會默默過期。",
    seoTitle: "年度重算退休倒數怎麼做？財富自由倒數計時器流程",
    metaDescription: "建立每年重算倒數習慣，利用財富自由倒數計時器校正目標月領、投入與達標年數。",
    focus: "年度重算倒數",
    keywordA: "年度重算退休計畫",
    keywordB: "理財計畫多久更新",
    keywordC: "退休倒數校正",
    closeQuestion: "你的目標還是去年的版本，還是今年的現實版本？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-40000-to-60000-upgrade-roadmap",
    title: "目標從 4 萬升到 6 萬：該怎麼升級不爆壓",
    subtitle: "目標可以升，節奏更要跟著升。",
    seoTitle: "目標月領從 4 萬到 6 萬怎麼調？財富自由倒數計時器規劃",
    metaDescription: "用倒數計時器示範目標升級時，如何同步調整投入與年數，避免理想升級但執行崩盤。",
    focus: "月領升級路線",
    keywordA: "月領目標升級",
    keywordB: "4萬到6萬規劃",
    keywordC: "退休升級策略",
    closeQuestion: "你想升級的是數字，還是整體可執行能力？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-starting-late-with-high-goal",
    title: "晚開始又高目標，真的沒機會嗎？先看倒數拆解",
    subtitle: "你需要的是策略，不是自責。",
    seoTitle: "晚開始還能追高月領嗎？財富自由倒數計時器拆解法",
    metaDescription: "針對晚起步且高目標族群，透過倒數計時器拆解可行路線，平衡速度與壓力。",
    focus: "晚開始高目標",
    keywordA: "晚開始高目標退休",
    keywordB: "晚開始怎麼追",
    keywordC: "退休倒數拆解",
    closeQuestion: "你要繼續內耗，還是開始重排可行路線？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-stress-free-monthly-input",
    title: "月投入要設到剛好痛，還是幾乎無痛？",
    subtitle: "太痛會斷，太鬆會慢，重點是平衡。",
    seoTitle: "月投入怎麼設最穩？財富自由倒數計時器找平衡點",
    metaDescription: "利用財富自由倒數計時器尋找投入壓力與達標速度平衡，建立不中斷的長期理財節奏。",
    focus: "投入壓力平衡",
    keywordA: "月投入要設多少",
    keywordB: "理財投入壓力",
    keywordC: "可持續月投",
    closeQuestion: "你現在是為了快而痛苦，還是為了穩而前進？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-housing-cost-impact-countdown",
    title: "房租變動會影響退休倒數嗎？先算就不慌",
    subtitle: "固定支出一變，整條時間軸都會動。",
    seoTitle: "房租上升會延後退休嗎？財富自由倒數計時器檢查法",
    metaDescription: "在租金或居住成本變動時，用倒數計時器快速重算達標年數，及時修正投入策略。",
    focus: "居住成本影響",
    keywordA: "房租上升退休影響",
    keywordB: "居住成本理財",
    keywordC: "倒數重算方法",
    closeQuestion: "你的計畫有替生活成本上升留空間嗎？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-family-support-pressure",
    title: "要支援家人時，退休倒數該怎麼調整才不失速",
    subtitle: "責任增加，不代表目標一定要放棄。",
    seoTitle: "家庭支援壓力下如何維持退休進度？倒數計時器示範",
    metaDescription: "面對家庭支援支出，利用財富自由倒數計時器調整投入與年數，維持可前進但不崩盤的節奏。",
    focus: "家庭支援調整",
    keywordA: "家庭支援理財調整",
    keywordB: "退休進度維持",
    keywordC: "支出增加怎麼辦",
    closeQuestion: "你願意怎麼調，才能同時守住責任與未來？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-side-income-accelerator",
    title: "副業收入要怎麼用，才能最有效縮短倒數",
    subtitle: "有額外收入時，最怕只是額外花掉。",
    seoTitle: "副業收入如何加速退休？財富自由倒數計時器策略",
    metaDescription: "透過倒數計時器比較副業收入的不同分配方式，找出對達標年數最有效的加速策略。",
    focus: "副業加速倒數",
    keywordA: "副業收入怎麼投",
    keywordB: "縮短退休年數方法",
    keywordC: "副業理財配置",
    closeQuestion: "你的副業收入，是在放大目標，還是放大消費？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick3-dream-monthly-income-simulator",
    title: "💣 夢想月領試算器：先算出你的夢想月領，才知道月投要多誠實",
    subtitle: "夢想不是不能大，先讓它變成可執行的數字。",
    seoTitle: "夢想月領試算器教學：想月領 5 萬，每月要投多少才合理？",
    metaDescription:
      "用第三台夢想月領試算器，從希望月領與預計年數倒推出建議月投金額，快速建立可執行的退休準備路線。",
    focus: "夢想月領試算器",
    keywordA: "夢想月領試算器怎麼用",
    keywordB: "希望月領5萬要投多少",
    keywordC: "月領倒推月投工具",
    closeQuestion: "你會先調高希望月領，還是先把年數拉長，換一條壓力更低的路？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
    calculatorNote: "先填希望月領，再選預計年數，直接看建議月投。先求能執行，再求更漂亮。",
  },
  {
    slug: "quick3-monthly-30000-reverse-plan",
    title: "夢想月領 3 萬怎麼反推？先算月投再談速度",
    subtitle: "目標先拆清楚，執行才不會亂。",
    seoTitle: "夢想月領 3 萬要月投多少？夢想月領試算器反推教學",
    metaDescription: "用夢想月領試算器示範月領 3 萬目標，從年數倒推每月投入，建立可執行退休計畫。",
    focus: "月領3萬反推",
    keywordA: "月領3萬要月投多少",
    keywordB: "夢想月領試算器",
    keywordC: "反推月投教學",
    closeQuestion: "你現在先要的是穩定做到，還是數字漂亮？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-monthly-40000-reverse-plan",
    title: "夢想月領 4 萬：反推月投時最常算錯哪裡？",
    subtitle: "不是算不出來，是常常設太理想。",
    seoTitle: "月領 4 萬如何反推月投？夢想月領試算器實測",
    metaDescription: "針對月領 4 萬目標，使用夢想月領試算器比較不同年數下的投入需求，避開過度樂觀設定。",
    focus: "月領4萬反推",
    keywordA: "月領4萬月投多少",
    keywordB: "退休目標反推",
    keywordC: "投入需求比較",
    closeQuestion: "你願意先降目標，還是先拉長年數？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-monthly-50000-reverse-plan",
    title: "月領 5 萬夢想版，反推後壓力到底多大？",
    subtitle: "越想快達成，越要先看可承受度。",
    seoTitle: "月領 5 萬反推月投：夢想月領試算器看壓力差距",
    metaDescription: "夢想月領試算器可快速比較月領 5 萬目標下不同年數與投入壓力，幫你選擇可持續版本。",
    focus: "月領5萬反推",
    keywordA: "月領5萬反推月投",
    keywordB: "投入壓力試算",
    keywordC: "可持續目標設定",
    closeQuestion: "你想要更快，還是更穩地走到目標？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-monthly-60000-reverse-plan",
    title: "月領 6 萬不是不行，但要知道代價是什麼",
    subtitle: "目標可以大，節奏要真實。",
    seoTitle: "月領 6 萬要投多少？夢想月領試算器反推達標路線",
    metaDescription: "示範高月領目標下的月投反推方法，利用夢想月領試算器找到速度與壓力的平衡。",
    focus: "月領6萬反推",
    keywordA: "月領6萬要投多少",
    keywordB: "高目標理財規劃",
    keywordC: "反推達標路線",
    closeQuestion: "你真的要快，還是其實要能長期做？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-how-much-per-month-for-15-years",
    title: "15 年內達標要月投多少？",
    subtitle: "縮短時間，代價通常是提高投入。",
    seoTitle: "15 年退休目標怎麼反推月投？夢想月領試算器",
    metaDescription: "以 15 年時間軸為例，透過夢想月領試算器反推每月投入，快速評估可行與不可行區間。",
    focus: "15年反推",
    keywordA: "15年退休月投多少",
    keywordB: "時間軸反推",
    keywordC: "短年限規劃",
    closeQuestion: "你能承受的是高投入，還是更長時間？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-how-much-per-month-for-20-years",
    title: "20 年版本最常見：怎麼反推才不自欺？",
    subtitle: "關鍵不是公式，是你能不能連續做。",
    seoTitle: "20 年退休反推月投教學｜夢想月領試算器",
    metaDescription: "用夢想月領試算器建立 20 年標準版規劃，避開只看理想報酬而忽略執行壓力。",
    focus: "20年反推",
    keywordA: "20年月投反推",
    keywordB: "退休標準版規劃",
    keywordC: "可執行理財",
    closeQuestion: "你現在的 20 年版本，是理想版還是實戰版？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-how-much-per-month-for-25-years",
    title: "把時間拉到 25 年，壓力會不會好很多？",
    subtitle: "有時候延長年數，比硬撐投入更有效。",
    seoTitle: "25 年退休路線怎麼反推？夢想月領試算器比較",
    metaDescription: "比較 25 年長期路線下的月投入需求，利用夢想月領試算器找到更穩定的達標方式。",
    focus: "25年反推",
    keywordA: "25年退休規劃",
    keywordB: "延長年數有用嗎",
    keywordC: "長期投入策略",
    closeQuestion: "你願意拿多一點時間，換少很多壓力嗎？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-increase-goal-or-extend-years",
    title: "要升目標，還是先延長年數？",
    subtitle: "順序錯了，很容易三個月後崩掉。",
    seoTitle: "升目標還是延長年數？夢想月領試算器判斷法",
    metaDescription: "針對升級目標時的常見糾結，透過夢想月領試算器比較兩條路線的可執行性。",
    focus: "升目標或延長",
    keywordA: "升目標還是延長年數",
    keywordB: "目標升級策略",
    keywordC: "可執行判斷",
    closeQuestion: "你現在最缺的是時間，還是可持續投入？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-salary-growth-reverse-strategy",
    title: "加薪後怎麼反推新目標？",
    subtitle: "加薪如果沒轉成投入，倒數不會自己變短。",
    seoTitle: "加薪後月領目標怎麼升級？夢想月領試算器策略",
    metaDescription: "用夢想月領試算器示範加薪後目標調整方法，避免生活升級吃掉投入增幅。",
    focus: "加薪反推策略",
    keywordA: "加薪後目標調整",
    keywordB: "月領目標升級",
    keywordC: "加薪理財策略",
    closeQuestion: "你會把加薪留給現在，還是分一部分給未來？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-single-income-reverse-plan",
    title: "單薪版反推：如何不爆壓還能前進",
    subtitle: "先守住節奏，再慢慢加速。",
    seoTitle: "單薪族月領目標反推：夢想月領試算器實戰",
    metaDescription: "單薪族使用夢想月領試算器，反推可承受投入與時間軸，避免高壓設定造成中斷。",
    focus: "單薪反推",
    keywordA: "單薪月領目標反推",
    keywordB: "單薪退休規劃",
    keywordC: "不爆壓投入",
    closeQuestion: "你現在的設定，是在幫你走得遠還是走得累？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-double-income-reverse-plan",
    title: "雙薪反推：怎麼讓兩個人的節奏對齊",
    subtitle: "不是誰投得多，而是同一張時間軸。",
    seoTitle: "雙薪家庭月領目標反推｜夢想月領試算器",
    metaDescription: "夢想月領試算器可協助雙薪家庭對齊目標、投入與年數，降低理財溝通摩擦。",
    focus: "雙薪反推",
    keywordA: "雙薪家庭反推月投",
    keywordB: "家庭目標對齊",
    keywordC: "雙薪理財節奏",
    closeQuestion: "你們現在是同隊合作，還是各算各的？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-bonus-topup-reverse-plan",
    title: "有獎金時，反推結果怎麼優化最有感",
    subtitle: "一次加碼要加在對的地方。",
    seoTitle: "獎金加碼如何優化月領目標？夢想月領試算器",
    metaDescription: "用夢想月領試算器比較有獎金與無獎金版本，找出對目標月領最有效的加碼方式。",
    focus: "獎金反推優化",
    keywordA: "獎金加碼理財",
    keywordB: "月領目標優化",
    keywordC: "一次加碼策略",
    closeQuestion: "你的獎金，會變成資產加速器嗎？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-late-start-reverse-path",
    title: "晚開始怎麼反推？先把路線拆細",
    subtitle: "晚不代表沒機會，不拆才沒機會。",
    seoTitle: "晚開始投資如何反推月領目標？夢想月領試算器",
    metaDescription: "針對晚起步族群，透過夢想月領試算器拆解目標與投入，建立可追趕路徑。",
    focus: "晚開始反推",
    keywordA: "晚開始反推月投",
    keywordB: "追趕目標路線",
    keywordC: "晚起步理財",
    closeQuestion: "你要繼續拖延，還是先開啟可追趕版本？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-inflation-adjusted-monthly-goal",
    title: "月領目標要不要加通膨？不加常常會錯估",
    subtitle: "名目數字好看，不代表未來夠用。",
    seoTitle: "月領目標要含通膨嗎？夢想月領試算器校正法",
    metaDescription: "用夢想月領試算器先做基礎反推，再加入通膨思維校正目標，避免低估未來需求。",
    focus: "通膨校正目標",
    keywordA: "月領目標通膨",
    keywordB: "退休目標校正",
    keywordC: "實質購買力",
    closeQuestion: "你現在追的是漂亮數字，還是實際生活力？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-risk-buffer-before-goal-upgrade",
    title: "升目標前先留緩衝，不然很容易半路掉隊",
    subtitle: "先有餘裕，再追更高月領。",
    seoTitle: "升級月領目標前要先留多少緩衝？夢想月領試算器",
    metaDescription: "示範升目標前先設緩衝的反推方法，透過夢想月領試算器降低中途放棄風險。",
    focus: "升級前緩衝",
    keywordA: "升目標前要留緩衝",
    keywordB: "中途放棄怎麼避免",
    keywordC: "反推風險控管",
    closeQuestion: "你想追更高目標，還是先把穩定度拉高？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-side-income-accelerate-goal",
    title: "副業收入怎麼用，反推結果才會真的變短",
    subtitle: "多賺的錢，最怕只是多花掉。",
    seoTitle: "副業收入如何加速月領目標？夢想月領試算器",
    metaDescription: "比較副業收入的不同用途，利用夢想月領試算器找出最能縮短目標時間的分配方式。",
    focus: "副業加速目標",
    keywordA: "副業收入怎麼用",
    keywordB: "加速月領目標",
    keywordC: "副業資金分配",
    closeQuestion: "你的副業，是在補現在，還是在加速未來？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-annual-reset-reverse-checklist",
    title: "每年一次反推重設，能省下很多焦慮",
    subtitle: "不重設，計畫就會和現實脫節。",
    seoTitle: "年更月領目標反推清單｜夢想月領試算器",
    metaDescription: "用夢想月領試算器建立年度重設流程，讓目標月領、投入與年數跟著現實更新。",
    focus: "年度反推重設",
    keywordA: "年度反推清單",
    keywordB: "目標年更流程",
    keywordC: "理財重設",
    closeQuestion: "你今年的目標，是新版本還是去年舊版本？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-expense-cut-vs-income-rise",
    title: "省支出和增收入，哪個對反推比較快？",
    subtitle: "答案常常不是二選一，而是先後順序。",
    seoTitle: "省支出 vs 增收入哪個更快達標？夢想月領試算器比較",
    metaDescription: "比較降低支出與提高收入兩條路，透過夢想月領試算器評估對月領目標的影響速度。",
    focus: "省支出或增收入",
    keywordA: "省支出還是增收入",
    keywordB: "達標速度比較",
    keywordC: "反推策略優先序",
    closeQuestion: "你下一步該先省，還是先賺？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-avoid-overoptimistic-goal-gap",
    title: "目標別設太樂觀，反推失真會讓你更焦慮",
    subtitle: "先誠實，再樂觀，才走得長。",
    seoTitle: "避免反推過度樂觀：夢想月領試算器務實設定法",
    metaDescription: "說明夢想月領反推常見過度樂觀問題，提供務實設定方法，提升長期執行率。",
    focus: "避免過度樂觀",
    keywordA: "反推太樂觀怎麼辦",
    keywordB: "務實月領設定",
    keywordC: "長期執行率",
    closeQuestion: "你現在是在規劃未來，還是在安慰現在？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick4-etf-monthly-income-simulator-guide",
    title: "💣 ETF 月領試算器：先算現金流，再決定 ETF 配置",
    subtitle: "不是配息越高越好，先看你每月實際想領多少。",
    seoTitle: "ETF 月領試算器教學：目標月領倒推資產與投入策略",
    metaDescription:
      "用第四台 ETF 月領試算器，先從目標月領反推資產需求，再回頭校正投入節奏，打造較穩定的退休現金流計畫。",
    focus: "ETF 月領試算器",
    keywordA: "ETF月領試算器怎麼用",
    keywordB: "ETF月領要準備多少資產",
    keywordC: "ETF退休現金流規劃",
    closeQuestion: "你現在的 ETF 目標，是在追高配息，還是在追可持續月領？",
    calculatorRoute: "/quick-4",
    calculatorName: "ETF 月領試算器",
    calculatorNote: "先填目標月領，再看反推資產與投入。先求穩定，再追效率。",
  },
  {
    slug: "quick5-principal-vs-compound-reality",
    title: "💣 雪球效應：本金 vs 複利｜你以為在存錢，其實在買時間",
    subtitle: "本金成長看起來慢，複利成長常在後段突然拉開。",
    seoTitle: "雪球效應：本金 vs 複利教學｜同月投下兩條曲線差距有多大",
    metaDescription:
      "透過第五台雪球效應：本金 vs 複利，直觀看見同一投入在不同時間軸的差距，幫你建立長期投入耐心。",
    focus: "雪球效應：本金 vs 複利",
    keywordA: "本金複利差距有多大",
    keywordB: "複利什麼時候會明顯",
    keywordC: "定期定額複利對照",
    closeQuestion: "你現在放棄的是一時的焦慮，還是後段最關鍵的複利區間？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
    calculatorNote: "看同一筆月投在本金線與複利線的分岔。先理解時間價值，再談報酬率。",
  },
  {
    slug: "quick5-first-100k-snowball-start",
    title: "第一個 10 萬最慢？雪球效應：本金 vs 複利的起跑觀念",
    subtitle: "最難的是起步，不是複利本身。",
    seoTitle: "第一個10萬怎麼存最快？雪球效應：本金 vs 複利起跑教學",
    metaDescription: "用雪球效應：本金 vs 複利看第一個 10 萬的形成過程，理解起跑期最該守住的投入節奏。",
    focus: "第一個10萬起跑",
    keywordA: "第一個10萬怎麼存",
    keywordB: "複利起跑期怎麼做",
    keywordC: "月投起步策略",
    closeQuestion: "你願意先慢一點但持續，還是快一點卻很快中斷？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-first-500k-compound-curve",
    title: "為什麼 50 萬前看起來很普通？其實你正在進入複利區",
    subtitle: "很多人放棄在最可惜的前段。",
    seoTitle: "存到50萬後會加速嗎？雪球效應：本金 vs 複利曲線解析",
    metaDescription: "透過第五台對照曲線理解 50 萬門檻後的加速感，建立對時間與紀律的正確認知。",
    focus: "50萬門檻曲線",
    keywordA: "存到50萬後會怎樣",
    keywordB: "複利加速點在哪",
    keywordC: "資產曲線成長",
    closeQuestion: "你現在的投入策略，有打算撐過看起來最無聊的那段嗎？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-first-million-snowball-moment",
    title: "第一個 100 萬不是終點，是雪球開始有感的那一刻",
    subtitle: "到這裡才看見時間真正站在你這邊。",
    seoTitle: "第一個100萬之後怎麼走？雪球效應：本金 vs 複利實戰思路",
    metaDescription: "用雪球效應：本金 vs 複利檢視百萬後路線，避免提早鬆懈，讓複利繼續放大成果。",
    focus: "第一個100萬後",
    keywordA: "第一個100萬之後",
    keywordB: "百萬後投資策略",
    keywordC: "雪球效應怎麼放大",
    closeQuestion: "到第一個百萬後，你是想停下來喘，還是把節奏守住？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-10year-vs-20year-gap",
    title: "同樣月投，10 年 vs 20 年差在哪？答案常超過想像",
    subtitle: "差距不是線性，而是被時間放大。",
    seoTitle: "月投10年和20年差多少？雪球效應：本金 vs 複利差距圖",
    metaDescription: "比較同月投入在 10 年與 20 年的結果差，透過對照曲線看懂時間的放大力。",
    focus: "10年vs20年差距",
    keywordA: "月投10年和20年差多少",
    keywordB: "時間對複利影響",
    keywordC: "長期投資差距",
    closeQuestion: "如果時間是最大槓桿，你現在有沒有在好好使用它？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-20year-vs-30year-gap",
    title: "20 年跟 30 年的差，不只多 10 年而已",
    subtitle: "後段的斜率，才是複利最狠的地方。",
    seoTitle: "投資20年和30年差在哪？雪球效應：本金 vs 複利後段威力",
    metaDescription: "透過第五台觀察 20 年與 30 年曲線差，理解長期複利在後段快速拉開的關鍵。",
    focus: "20年vs30年差距",
    keywordA: "投資20年和30年差別",
    keywordB: "複利後段威力",
    keywordC: "延長投資年期價值",
    closeQuestion: "你願不願意多給自己 10 年，把結果放大到真正有感？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-stop-investing-for-1year-impact",
    title: "中斷一年真的差很多嗎？雪球效應：本金 vs 複利直接對照",
    subtitle: "短暫停手，可能讓後段落差擴大。",
    seoTitle: "投資中斷一年影響多大？雪球效應：本金 vs 複利試算",
    metaDescription: "模擬中斷投入一年的影響，利用對照曲線看見節奏斷裂對長期結果的代價。",
    focus: "中斷一年影響",
    keywordA: "投資中斷一年差多少",
    keywordB: "停扣影響",
    keywordC: "持續投入的重要",
    closeQuestion: "你有沒有替自己設計『不想投時也能投』的備案？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-small-increase-big-longterm-gap",
    title: "每月多 1000 看起來很少，長期可能很有感",
    subtitle: "微調，不一定微小。",
    seoTitle: "每月多存1000有用嗎？雪球效應：本金 vs 複利長期差距",
    metaDescription: "以第五台比較月投微幅增加的長期效果，找出不爆生活但能加速路線的調整方式。",
    focus: "小幅加碼長期差",
    keywordA: "每月多存1000有用嗎",
    keywordB: "小額加碼投資",
    keywordC: "長期複利差距",
    closeQuestion: "你願意少一點短期舒適，換長期更大的餘裕嗎？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-monthly-10000-vs-12000",
    title: "月投 10000 vs 12000：你以為只差 2000，其實不只",
    subtitle: "被放大的不是金額，是時間乘上紀律。",
    seoTitle: "月投10000和12000差多少？雪球效應：本金 vs 複利比較",
    metaDescription: "比較月投 10000 與 12000 在長期路徑的差異，幫你找出最可執行的升級幅度。",
    focus: "10000對12000",
    keywordA: "月投10000和12000差多少",
    keywordB: "月投加2000有用嗎",
    keywordC: "定期定額差距",
    closeQuestion: "你現在的版本，是最舒服的，還是最有效的？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-monthly-15000-vs-20000",
    title: "月投 15000 vs 20000：差距何時開始擴大？",
    subtitle: "開始那幾年不明顯，後面通常會拉開。",
    seoTitle: "月投15000和20000差距多大？雪球效應：本金 vs 複利試算",
    metaDescription: "用第五台比較月投 15000 與 20000 的時間差距，幫你判斷加碼是否值得。",
    focus: "15000對20000",
    keywordA: "月投15000和20000差多少",
    keywordB: "加碼5000值不值得",
    keywordC: "月投策略比較",
    closeQuestion: "如果可以加碼，你想一次加大，還是分段加？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-lump-sum-plus-monthly-plan",
    title: "一次投入加每月投入，雪球會滾更快嗎？",
    subtitle: "組合打法，重點是節奏不是衝動。",
    seoTitle: "一次投入搭配月投怎麼配？雪球效應：本金 vs 複利規劃",
    metaDescription: "示範一次投入與定期投入並行的策略，透過對照曲線找出更穩的複利節奏。",
    focus: "一次加碼加月投",
    keywordA: "一次投入加月投",
    keywordB: "加碼策略怎麼配",
    keywordC: "複利節奏規劃",
    closeQuestion: "你的加碼是有計畫，還是每次都憑當下情緒？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-bear-market-continue-or-stop",
    title: "下跌時該停還是續投？雪球效應：本金 vs 複利幫你看長線",
    subtitle: "情緒很吵時，最需要看圖說話。",
    seoTitle: "下跌時停扣還是續投？雪球效應：本金 vs 複利長線比較",
    metaDescription: "在市場回檔情境下，透過第五台對照續投與停手的長期差，降低情緒決策風險。",
    focus: "下跌續投或停手",
    keywordA: "下跌時要不要停扣",
    keywordB: "熊市續投策略",
    keywordC: "情緒投資修正",
    closeQuestion: "下次市場震盪時，你要照情緒，還是照計畫？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-inflation-vs-nominal-balance",
    title: "名目有在長，不代表購買力也在長",
    subtitle: "雪球要看體積，也要看密度。",
    seoTitle: "通膨下的複利怎麼看？雪球效應：本金 vs 複利實用提醒",
    metaDescription: "從名目數字與實質購買力差異出發，搭配第五台建立更務實的長期目標。",
    focus: "通膨與名目差",
    keywordA: "通膨下複利怎麼看",
    keywordB: "名目和實質差異",
    keywordC: "購買力理財",
    closeQuestion: "你在追的數字，能不能真的換到你要的生活？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-expense-growth-eats-snowball",
    title: "支出慢慢長大，可能正在吃掉你的雪球速度",
    subtitle: "看似小調整，長期會很有感。",
    seoTitle: "生活支出上升會拖慢複利嗎？雪球效應：本金 vs 複利對照",
    metaDescription: "示範固定支出上升對月投與長期曲線的影響，幫你提前調整而非事後焦慮。",
    focus: "支出成長拖慢",
    keywordA: "支出上升投資影響",
    keywordB: "月投被生活吃掉",
    keywordC: "理財節奏調整",
    closeQuestion: "你有沒有定期檢查：哪筆支出正在默默吃掉未來？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-salary-growth-boost-compound",
    title: "加薪後怎麼讓雪球更快？不是全加碼，是先分配",
    subtitle: "加薪是一個重設節奏的機會。",
    seoTitle: "加薪後月投怎麼調？雪球效應：本金 vs 複利升級策略",
    metaDescription: "利用第五台比較加薪後不同投入比例，找到可持續又能加速的複利升級版本。",
    focus: "加薪後放大雪球",
    keywordA: "加薪後月投怎麼調",
    keywordB: "加薪理財分配",
    keywordC: "複利加速策略",
    closeQuestion: "這次加薪，你打算幫今天的自己，還是也幫未來的自己？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-risk-buffer-before-acceleration",
    title: "想加速前先放安全墊，雪球才不會遇事就停",
    subtitle: "速度重要，但不中斷更重要。",
    seoTitle: "加速投入前要先做什麼？雪球效應：本金 vs 複利安全墊觀念",
    metaDescription: "說明在加大投入前先建立風險緩衝的必要性，避免計畫因突發事件中斷。",
    focus: "安全墊先行",
    keywordA: "投資前要先準備什麼",
    keywordB: "安全墊與月投",
    keywordC: "避免中斷投入",
    closeQuestion: "你的計畫有備案嗎？還是只在順風時有效？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-annual-rebalance-snowball-check",
    title: "每年檢查一次雪球方向，勝過每天盯盤焦慮",
    subtitle: "路線對，比頻繁動作更重要。",
    seoTitle: "年度複利健檢怎麼做？雪球效應：本金 vs 複利檢查清單",
    metaDescription: "提供年度檢查流程，搭配第五台確認投入節奏是否仍與目標一致。",
    focus: "年度雪球健檢",
    keywordA: "年度理財檢查怎麼做",
    keywordB: "複利路線校正",
    keywordC: "投資健檢清單",
    closeQuestion: "你現在的路線，還是去年那條嗎？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-dividend-reinvest-snowball",
    title: "配息再投入，為什麼常是雪球變大的關鍵",
    subtitle: "看起來小，長期常很關鍵。",
    seoTitle: "配息再投入有差嗎？雪球效應：本金 vs 複利十年觀察",
    metaDescription: "比較配息再投入與不再投入的長期差異，協助你建立適合自己的資金規則。",
    focus: "配息再投入雪球",
    keywordA: "配息再投入有差嗎",
    keywordB: "ETF配息再投資",
    keywordC: "複利放大方法",
    closeQuestion: "你希望配息帶來短期舒服，還是長期更大選擇權？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-why-time-beats-perfect-timing",
    title: "完美進場很難，長時間在場反而更實際",
    subtitle: "你不必抓神點位，也能靠紀律放大結果。",
    seoTitle: "進場時機重要還是時間重要？雪球效應：本金 vs 複利給答案",
    metaDescription: "透過第五台對照理解『長時間在場』的價值，減少追求完美時機造成的拖延。",
    focus: "時間勝過時機",
    keywordA: "進場時機和時間哪個重要",
    keywordB: "長期在場價值",
    keywordC: "定期定額心理建設",
    closeQuestion: "你現在是在等完美時機，還是在累積真實時間？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-build-30year-snowball-habit",
    title: "30 年雪球不是奇蹟，是一套可活下去的習慣",
    subtitle: "習慣比天分更能決定長期差距。",
    seoTitle: "30年複利怎麼做得到？雪球效應：本金 vs 複利習慣養成法",
    metaDescription: "以第五台為核心建立 30 年長期投入習慣，從小步穩定到長期放大，打造可持續路線。",
    focus: "30年雪球習慣",
    keywordA: "30年複利怎麼做",
    keywordB: "長期投資習慣",
    keywordC: "雪球效應養成",
    closeQuestion: "你今天願意做哪個小動作，讓 10 年後的自己更有底氣？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick6-house-vs-invest-decision-map",
    title: "💣 買房跟投資試算器：你不是二選一，是在選現金流壓力",
    subtitle: "同樣都叫資產，現金流體感可能完全不同。",
    seoTitle: "買房跟投資試算器：房貸路線與投資路線如何比較",
    metaDescription:
      "用第六台買房跟投資試算器，比較不同房貸支出與投資投入的長期結果，幫你做更貼近生活的配置判斷。",
    focus: "買房跟投資試算器",
    keywordA: "買房跟投資怎麼選",
    keywordB: "房貸與投資比較",
    keywordC: "現金流壓力試算",
    closeQuestion: "你現在最需要的是資產增值，還是先把每月壓力降到可持續？",
    calculatorRoute: "/quick-6",
    calculatorName: "買房跟投資試算器",
    calculatorNote: "把房貸與投資放進同一張時間軸看。先看壓力，再看收益。",
  },
  {
    slug: "quick7-car-vs-invest-decision-map",
    title: "💣 買車跟投資試算器：這筆車款，十年後可能是另一筆自由",
    subtitle: "不是不能買車，而是先看它換走了多少未來選擇權。",
    seoTitle: "買車跟投資試算器：車貸支出與長期投資差距一次看懂",
    metaDescription:
      "第七台買車跟投資試算器可比較車貸支出與投資投入的長期資產差，協助你判斷當下消費與未來自由的取捨。",
    focus: "買車跟投資試算器",
    keywordA: "買車跟投資怎麼選",
    keywordB: "車貸機會成本",
    keywordC: "延後消費試算",
    closeQuestion: "這台車帶來的是必要便利，還是其實只是短期情緒補償？",
    calculatorRoute: "/quick-7",
    calculatorName: "買車跟投資試算器",
    calculatorNote: "先輸入車貸相關支出，再看同期間投資路線差距。先看現實，再做決定。",
  },
  {
    slug: "quick8-delay-gratification-simulator-guide",
    title: "💣 延遲享樂模擬器：晚一點花，真的會差很多嗎？",
    subtitle: "你不是在犧牲快樂，而是在買更大的選擇權。",
    seoTitle: "延遲享樂模擬器教學：分期支出 vs 可投資金額長期差距",
    metaDescription:
      "使用第八台延遲享樂模擬器，觀察分期支出與可投資金額變化如何影響長期資產，讓消費決策更有依據。",
    focus: "延遲享樂模擬器",
    keywordA: "延遲享樂有用嗎",
    keywordB: "分期對投資影響",
    keywordC: "可投資金額試算",
    closeQuestion: "你願意把哪一筆當下想要，換成未來更穩的底氣？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
    calculatorNote: "先調整分期支出，再看可投資金額與曲線差距。你會很快看懂代價。",
  },
  {
    slug: "quick9-delay-spending-value-calculator-guide",
    title: "💣 延遲消費價值計算機：晚買不是忍耐，是重新定價",
    subtitle: "同一筆錢，時間不同，價值真的不同。",
    seoTitle: "延遲消費價值計算機：3年5年10年切換看差距",
    metaDescription:
      "透過第九台延遲消費價值計算機，以 3/5/10 年幅度比較延後消費的資產差，幫你做更聰明的消費節奏。",
    focus: "延遲消費價值計算機",
    keywordA: "延遲消費價值怎麼算",
    keywordB: "晚買真的划算嗎",
    keywordC: "消費延後試算",
    closeQuestion: "你現在的每一次刷卡，真的符合你想要的長期生活版本嗎？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
    calculatorNote: "切換 3/5/10 年視角看差距，別只看當下價格，先看長期機會成本。",
  },
  {
    slug: "quick10-asset-stress-test-simulator-guide",
    title: "💣 資產抗壓模擬器：如果遇到壓力，你的計畫撐得住嗎？",
    subtitle: "真正穩定的計畫，不是最漂亮，是跌倒後還能走。",
    seoTitle: "資產抗壓模擬器教學：壓力情境下的財務韌性怎麼看",
    metaDescription:
      "第十台資產抗壓模擬器可測試不同壓力情境對資產路徑影響，幫你提前找出脆弱點，優化長期理財策略。",
    focus: "資產抗壓模擬器",
    keywordA: "資產抗壓怎麼測試",
    keywordB: "投資壓力情境試算",
    keywordC: "財務韌性規劃",
    closeQuestion: "你的計畫是只在順風有效，還是逆風也能繼續走？",
    calculatorRoute: "/quick-10",
    calculatorName: "資產抗壓模擬器",
    calculatorNote: "先測壓力情境，再調參數，找出你真正撐得住的版本。",
  },
];

function buildSections(seed: TopicSeed, calculatorName: string): Quick1ExclusiveSection[] {
  return [
    {
      heading: `先把問題說白：${seed.focus}，不是靠感覺`,
      paragraphs: [
        `很多人一開始都會問：「${seed.focus}到底要怎麼做才對？」`,
        "我通常會先回一句內心戲：\"先別急著找標準答案，先看你現在做不做得到。\"",
        `${calculatorName}的價值很務實：把你現在的月投入、年數，直接翻成看得懂的結果。`,
        "當數字攤開，你就不再靠想像做決策...而是靠可驗證的路線在前進。",
      ],
      bullets: [`🔎 你可能也在找：${seed.keywordA}`, `🔎 你可能也在找：${seed.keywordB}`, `🔎 你可能也在找：${seed.keywordC}`],
    },
    {
      heading: "最常見的卡點：不是不努力，是路線太硬",
      paragraphs: [
        "很多計畫一開始很熱血，三個月後就停下來。不是你不行，而是你把起跑值設得太吃緊。",
        "我自己的原則很簡單：可以慢，但不要斷。因為一旦中斷，重啟的心理成本會比你想像高。",
        "把目標拆成可調旋鈕最實際——提高月投入、延長年數、或先調整生活版本。",
        "你不需要一次完美；你只需要每次都比上一次更可持續。",
      ],
    },
    {
      heading: "給你一套可執行版 ✅",
      paragraphs: [
        "① 先填你「下個月也做得到」的月投入。",
        "② 用 15 / 20 / 25 年三組比較，別只看單一答案。",
        "③ 看月領示意時，問自己一句：\"這個生活版本我願意長期承擔嗎？\"",
        "④ 每 30 天回來校正一次，只調參數，不用自責。",
        "一句話收尾：理財不是比賽誰最猛，而是看誰最能長期不掉線。",
      ],
    },
  ];
}

export const QUICK1_EXCLUSIVE_POSTS: Quick1ExclusivePost[] = TOPIC_SEEDS.map((seed, idx) => {
  const calculatorRoute = seed.calculatorRoute ?? "/quick-1";
  const calculatorName = seed.calculatorName ?? "存股複利計算機";
  const fallbackDate = PUBLISH_DATES[idx] ?? (() => {
    const baseMs = Date.parse("2026-05-04T01:00:00.000Z");
    const isoDate = new Date(baseMs + Math.max(0, idx) * 12 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
    return `${isoDate}T09:00:00+08:00`;
  })();
  const scheduledAt =
    calculatorRoute === "/quick-2"
      ? (QUICK2_PUBLISH_DATES[seed.slug] ?? fallbackDate)
      : calculatorRoute === "/quick-3"
        ? (QUICK3_PUBLISH_DATES[seed.slug] ?? fallbackDate)
        : calculatorRoute === "/quick-5"
          ? (QUICK5_PUBLISH_DATES[seed.slug] ?? fallbackDate)
          : fallbackDate;
  return {
    slug: seed.slug,
    title: seed.title,
    subtitle: seed.subtitle,
    seoTitle: seed.seoTitle,
    metaDescription: seed.metaDescription,
    publishAtIso: scheduledAt,
    calculatorRoute,
    calculatorTitle: `${calculatorName}（直接放入）`,
    calculatorNote: seed.calculatorNote ?? "先改月投，再改年數，最後看月領示意。先求做得到，再求做得快。",
    sections: buildSections(seed, calculatorName),
    closeQuestion: seed.closeQuestion,
    disclaimer: "本文為情境試算與經驗分享，非投資建議；實際結果受市場、費用、稅務與個人行為影響。",
  };
});

export function getQuick1ExclusivePostBySlug(slug: string): Quick1ExclusivePost | undefined {
  return QUICK1_EXCLUSIVE_POSTS.find((post) => post.slug === slug);
}
