export type Quick1ExclusiveSection = {
  heading: string;
  paragraphs: string[];
  bullets?: string[];
};

export type Quick1ExclusivePost = {
  slug: string;
  title: string;
  subtitle: string;
  seoTitle: string;
  metaDescription: string;
  publishAtIso: string;
  calculatorRoute: "/quick-1" | "/quick-2" | "/quick-3" | "/quick-4" | "/quick-5" | "/quick-6" | "/quick-7" | "/quick-8" | "/quick-9" | "/quick-10";
  calculatorTitle: string;
  calculatorNote: string;
  sections: Quick1ExclusiveSection[];
  closeQuestion: string;
  disclaimer: string;
};

type TopicSeed = {
  slug: string;
  title: string;
  subtitle: string;
  seoTitle: string;
  metaDescription: string;
  focus: string;
  keywordA: string;
  keywordB: string;
  keywordC: string;
  closeQuestion: string;
  calculatorRoute?: "/quick-1" | "/quick-2" | "/quick-3" | "/quick-4" | "/quick-5" | "/quick-6" | "/quick-7" | "/quick-8" | "/quick-9" | "/quick-10";
  calculatorName?: string;
  calculatorNote?: string;
};

const PUBLISH_DATES = [
  "2026-05-04T09:00:00+08:00",
  "2026-05-16T09:00:00+08:00",
  "2026-05-28T09:00:00+08:00",
  "2026-06-09T09:00:00+08:00",
  "2026-06-21T09:00:00+08:00",
  "2026-07-03T09:00:00+08:00",
  "2026-07-15T09:00:00+08:00",
  "2026-07-27T09:00:00+08:00",
  "2026-08-08T09:00:00+08:00",
  "2026-08-20T09:00:00+08:00",
  "2026-09-01T09:00:00+08:00",
  "2026-09-13T09:00:00+08:00",
  "2026-09-25T09:00:00+08:00",
  "2026-10-07T09:00:00+08:00",
  "2026-10-19T09:00:00+08:00",
  "2026-10-31T09:00:00+08:00",
  "2026-11-12T09:00:00+08:00",
  "2026-11-24T09:00:00+08:00",
  "2026-12-06T09:00:00+08:00",
  "2026-12-18T09:00:00+08:00",
  "2026-12-30T09:00:00+08:00",
  "2027-01-11T09:00:00+08:00",
  "2027-01-23T09:00:00+08:00",
  "2027-02-04T09:00:00+08:00",
  "2027-02-16T09:00:00+08:00",
  "2027-02-28T09:00:00+08:00",
  "2027-03-12T09:00:00+08:00",
  "2027-03-24T09:00:00+08:00",
  "2027-04-05T09:00:00+08:00",
  "2027-04-17T09:00:00+08:00",
  "2027-04-29T09:00:00+08:00",
  "2027-05-11T09:00:00+08:00",
  "2027-05-23T09:00:00+08:00",
  "2027-06-04T09:00:00+08:00",
  "2027-06-16T09:00:00+08:00",
  "2027-06-28T09:00:00+08:00",
  "2027-07-10T09:00:00+08:00",
  "2027-07-22T09:00:00+08:00",
  "2027-08-03T09:00:00+08:00",
  "2027-08-15T09:00:00+08:00",
  "2027-08-27T09:00:00+08:00",
  "2027-09-08T09:00:00+08:00",
  "2027-09-20T09:00:00+08:00",
  "2027-10-02T09:00:00+08:00",
  "2027-10-14T09:00:00+08:00",
  "2027-10-26T09:00:00+08:00",
  "2027-11-07T09:00:00+08:00",
  "2027-11-19T09:00:00+08:00",
] as const;

const QUICK2_PUBLISH_DATES: Record<string, string> = {
  "quick2-freedom-countdown-target-years": "2026-05-05T09:00:00+08:00",
  "quick2-monthly-40000-countdown": "2026-05-17T09:00:00+08:00",
  "quick2-monthly-50000-countdown": "2026-05-29T09:00:00+08:00",
  "quick2-monthly-60000-countdown": "2026-06-10T09:00:00+08:00",
  "quick2-raise-invest-or-extend-years": "2026-06-22T09:00:00+08:00",
  "quick2-first-10-years-gap": "2026-07-04T09:00:00+08:00",
  "quick2-salary-plateau-countdown": "2026-07-16T09:00:00+08:00",
  "quick2-double-income-household-target": "2026-07-28T09:00:00+08:00",
  "quick2-single-income-pressure-map": "2026-08-09T09:00:00+08:00",
  "quick2-bonus-allocation-countdown": "2026-08-21T09:00:00+08:00",
  "quick2-lifestyle-upgrade-warning": "2026-09-02T09:00:00+08:00",
  "quick2-early-retire-vs-slower-path": "2026-09-14T09:00:00+08:00",
  "quick2-bear-market-delay-check": "2026-09-26T09:00:00+08:00",
  "quick2-annual-review-reset-plan": "2026-10-08T09:00:00+08:00",
  "quick2-40000-to-60000-upgrade-roadmap": "2026-10-20T09:00:00+08:00",
  "quick2-starting-late-with-high-goal": "2026-11-01T09:00:00+08:00",
  "quick2-stress-free-monthly-input": "2026-11-13T09:00:00+08:00",
  "quick2-housing-cost-impact-countdown": "2026-11-25T09:00:00+08:00",
  "quick2-family-support-pressure": "2026-12-07T09:00:00+08:00",
  "quick2-side-income-accelerator": "2026-12-19T09:00:00+08:00",
};

const QUICK3_PUBLISH_DATES: Record<string, string> = {
  "quick3-dream-monthly-income-simulator": "2026-05-06T09:00:00+08:00",
  "quick3-monthly-30000-reverse-plan": "2026-05-18T09:00:00+08:00",
  "quick3-monthly-40000-reverse-plan": "2026-05-30T09:00:00+08:00",
  "quick3-monthly-50000-reverse-plan": "2026-06-11T09:00:00+08:00",
  "quick3-monthly-60000-reverse-plan": "2026-06-23T09:00:00+08:00",
  "quick3-how-much-per-month-for-15-years": "2026-07-05T09:00:00+08:00",
  "quick3-how-much-per-month-for-20-years": "2026-07-17T09:00:00+08:00",
  "quick3-how-much-per-month-for-25-years": "2026-07-29T09:00:00+08:00",
  "quick3-increase-goal-or-extend-years": "2026-08-10T09:00:00+08:00",
  "quick3-salary-growth-reverse-strategy": "2026-08-22T09:00:00+08:00",
  "quick3-single-income-reverse-plan": "2026-09-03T09:00:00+08:00",
  "quick3-double-income-reverse-plan": "2026-09-15T09:00:00+08:00",
  "quick3-bonus-topup-reverse-plan": "2026-09-27T09:00:00+08:00",
  "quick3-late-start-reverse-path": "2026-10-09T09:00:00+08:00",
  "quick3-inflation-adjusted-monthly-goal": "2026-10-21T09:00:00+08:00",
  "quick3-risk-buffer-before-goal-upgrade": "2026-11-02T09:00:00+08:00",
  "quick3-side-income-accelerate-goal": "2026-11-14T09:00:00+08:00",
  "quick3-annual-reset-reverse-checklist": "2026-11-26T09:00:00+08:00",
  "quick3-expense-cut-vs-income-rise": "2026-12-08T09:00:00+08:00",
  "quick3-avoid-overoptimistic-goal-gap": "2026-12-20T09:00:00+08:00",
};

const QUICK5_PUBLISH_DATES: Record<string, string> = {
  "quick5-principal-vs-compound-reality": "2026-05-08T09:00:00+08:00",
  "quick5-first-100k-snowball-start": "2026-05-20T09:00:00+08:00",
  "quick5-first-500k-compound-curve": "2026-06-01T09:00:00+08:00",
  "quick5-first-million-snowball-moment": "2026-06-13T09:00:00+08:00",
  "quick5-10year-vs-20year-gap": "2026-06-25T09:00:00+08:00",
  "quick5-20year-vs-30year-gap": "2026-07-07T09:00:00+08:00",
  "quick5-stop-investing-for-1year-impact": "2026-07-19T09:00:00+08:00",
  "quick5-small-increase-big-longterm-gap": "2026-07-31T09:00:00+08:00",
  "quick5-monthly-10000-vs-12000": "2026-08-12T09:00:00+08:00",
  "quick5-monthly-15000-vs-20000": "2026-08-24T09:00:00+08:00",
  "quick5-lump-sum-plus-monthly-plan": "2026-09-05T09:00:00+08:00",
  "quick5-bear-market-continue-or-stop": "2026-09-17T09:00:00+08:00",
  "quick5-inflation-vs-nominal-balance": "2026-09-29T09:00:00+08:00",
  "quick5-expense-growth-eats-snowball": "2026-10-11T09:00:00+08:00",
  "quick5-salary-growth-boost-compound": "2026-10-23T09:00:00+08:00",
  "quick5-risk-buffer-before-acceleration": "2026-11-04T09:00:00+08:00",
  "quick5-annual-rebalance-snowball-check": "2026-11-16T09:00:00+08:00",
  "quick5-dividend-reinvest-snowball": "2026-11-28T09:00:00+08:00",
  "quick5-why-time-beats-perfect-timing": "2026-12-10T09:00:00+08:00",
  "quick5-build-30year-snowball-habit": "2026-12-22T09:00:00+08:00",
};

const QUICK6_PUBLISH_DATES: Record<string, string> = {
  "quick6-leverage-choice-property-vs-global-stocks": "2026-05-09T09:00:00+08:00",
  "quick6-rent-vs-buy-cashflow-truth": "2026-05-21T09:00:00+08:00",
  "quick6-down-payment-vs-monthly-invest-gap": "2026-06-02T09:00:00+08:00",
  "quick6-interest-rate-shock-stress-test": "2026-06-14T09:00:00+08:00",
  "quick6-15year-vs-30year-loan-impact": "2026-06-26T09:00:00+08:00",
  "quick6-home-ownership-cost-hidden-list": "2026-07-08T09:00:00+08:00",
  "quick6-liquidity-trap-property-heavy-portfolio": "2026-07-20T09:00:00+08:00",
  "quick6-first-home-or-first-million": "2026-08-01T09:00:00+08:00",
  "quick6-couple-buy-home-invest-balance": "2026-08-13T09:00:00+08:00",
  "quick6-single-income-mortgage-pressure-map": "2026-08-25T09:00:00+08:00",
  "quick6-inflation-helps-or-hurts-home-buyer": "2026-09-06T09:00:00+08:00",
  "quick6-global-etf-vs-local-property-bias": "2026-09-18T09:00:00+08:00",
  "quick6-bear-market-while-paying-mortgage": "2026-09-30T09:00:00+08:00",
  "quick6-bonus-use-prepay-or-invest": "2026-10-12T09:00:00+08:00",
  "quick6-career-risk-and-mortgage-commitment": "2026-10-24T09:00:00+08:00",
  "quick6-rebalance-after-buying-property": "2026-11-05T09:00:00+08:00",
  "quick6-retire-with-mortgage-plan": "2026-11-17T09:00:00+08:00",
  "quick6-property-upgrade-vs-portfolio-growth": "2026-11-29T09:00:00+08:00",
  "quick6-why-cashflow-beats-paper-wealth": "2026-12-11T09:00:00+08:00",
  "quick6-build-30year-leverage-discipline": "2026-12-23T09:00:00+08:00",
};

const QUICK7_PUBLISH_DATES: Record<string, string> = {
  "quick7-leverage-choice-mortgage-vs-global-stocks": "2026-05-10T09:00:00+08:00",
  "quick7-rent-or-buy-global-portfolio-balance": "2026-05-22T09:00:00+08:00",
  "quick7-mortgage-term-20-vs-30-impact": "2026-06-03T09:00:00+08:00",
  "quick7-down-payment-vs-dca-global-etf": "2026-06-15T09:00:00+08:00",
  "quick7-rate-hike-risk-check": "2026-06-27T09:00:00+08:00",
  "quick7-single-income-mortgage-survival-map": "2026-07-09T09:00:00+08:00",
  "quick7-double-income-home-invest-strategy": "2026-07-21T09:00:00+08:00",
  "quick7-bonus-prepay-or-invest-global": "2026-08-02T09:00:00+08:00",
  "quick7-liquidity-buffer-before-leverage": "2026-08-14T09:00:00+08:00",
  "quick7-home-ownership-hidden-costs": "2026-08-26T09:00:00+08:00",
  "quick7-property-concentration-risk": "2026-09-07T09:00:00+08:00",
  "quick7-bear-market-while-paying-mortgage": "2026-09-19T09:00:00+08:00",
  "quick7-career-uncertainty-and-mortgage": "2026-10-01T09:00:00+08:00",
  "quick7-inflation-and-mortgage-choice": "2026-10-13T09:00:00+08:00",
  "quick7-global-diversification-vs-local-home-bias": "2026-10-25T09:00:00+08:00",
  "quick7-retire-with-mortgage-plan": "2026-11-06T09:00:00+08:00",
  "quick7-asset-rebalance-after-home-buy": "2026-11-18T09:00:00+08:00",
  "quick7-upgrade-home-vs-upgrade-portfolio": "2026-11-30T09:00:00+08:00",
  "quick7-cashflow-first-paper-wealth-second": "2026-12-12T09:00:00+08:00",
  "quick7-build-30year-leverage-discipline": "2026-12-24T09:00:00+08:00",
};

const QUICK8_PUBLISH_DATES: Record<string, string> = {
  "quick8-delay-gratification-simulator-guide": "2026-05-10T09:00:00+08:00",
  "quick8-installment-vs-invest-3000-gap": "2026-05-22T09:00:00+08:00",
  "quick8-installment-vs-invest-5000-gap": "2026-06-03T09:00:00+08:00",
  "quick8-new-phone-now-or-later": "2026-06-15T09:00:00+08:00",
  "quick8-subscription-creep-vs-freedom-speed": "2026-06-27T09:00:00+08:00",
  "quick8-weekend-shopping-habit-audit": "2026-07-09T09:00:00+08:00",
  "quick8-couple-spending-alignment-framework": "2026-07-21T09:00:00+08:00",
  "quick8-year-end-sale-trap-analysis": "2026-08-02T09:00:00+08:00",
  "quick8-bonus-spend-or-invest-split": "2026-08-14T09:00:00+08:00",
  "quick8-travel-budget-vs-longterm-assets": "2026-08-26T09:00:00+08:00",
  "quick8-lifestyle-upgrade-timing-choice": "2026-09-07T09:00:00+08:00",
  "quick8-emotion-buying-cooldown-system": "2026-09-19T09:00:00+08:00",
  "quick8-credit-card-installment-hidden-cost": "2026-10-01T09:00:00+08:00",
  "quick8-low-buy-impulse-high-invest-routine": "2026-10-13T09:00:00+08:00",
  "quick8-pay-yourself-first-delay-gratification": "2026-10-25T09:00:00+08:00",
  "quick8-family-budget-priority-map": "2026-11-06T09:00:00+08:00",
  "quick8-side-income-do-not-inflate-lifestyle": "2026-11-18T09:00:00+08:00",
  "quick8-minimalism-vs-consumption-balance": "2026-11-30T09:00:00+08:00",
  "quick8-annual-reset-delay-gratification-plan": "2026-12-12T09:00:00+08:00",
  "quick8-build-30year-delay-gratification-habit": "2026-12-24T09:00:00+08:00",
};

const QUICK9_PUBLISH_DATES: Record<string, string> = {
  "quick9-delay-spending-value-calculator-guide": "2026-05-11T09:00:00+08:00",
  "quick9-3year-5year-10year-compare": "2026-05-23T09:00:00+08:00",
  "quick9-buy-now-vs-buy-later-laptop-case": "2026-06-04T09:00:00+08:00",
  "quick9-installment-or-cash-global-invest-impact": "2026-06-16T09:00:00+08:00",
  "quick9-impulse-purchase-cooldown-72h": "2026-06-28T09:00:00+08:00",
  "quick9-monthly-wants-budget-cap-system": "2026-07-10T09:00:00+08:00",
  "quick9-credit-card-points-vs-real-cost": "2026-07-22T09:00:00+08:00",
  "quick9-year-end-discount-vs-longterm-value": "2026-08-03T09:00:00+08:00",
  "quick9-subscription-stack-cleanup-plan": "2026-08-15T09:00:00+08:00",
  "quick9-iphone-upgrade-cycle-choice": "2026-08-27T09:00:00+08:00",
  "quick9-car-upgrade-delay-value": "2026-09-08T09:00:00+08:00",
  "quick9-home-appliance-replace-or-repair": "2026-09-20T09:00:00+08:00",
  "quick9-side-income-spend-or-invest-rule": "2026-10-02T09:00:00+08:00",
  "quick9-couple-big-ticket-decision-framework": "2026-10-14T09:00:00+08:00",
  "quick9-family-consumption-priority-order": "2026-10-26T09:00:00+08:00",
  "quick9-buy-experience-or-buy-asset-balance": "2026-11-07T09:00:00+08:00",
  "quick9-annual-reset-consumption-value-map": "2026-11-19T09:00:00+08:00",
  "quick9-low-consumption-high-freedom-routine": "2026-12-01T09:00:00+08:00",
  "quick9-avoid-lifestyle-inflation-checklist": "2026-12-13T09:00:00+08:00",
  "quick9-build-30year-delay-spending-discipline": "2026-12-25T09:00:00+08:00",
};

const QUICK10_PUBLISH_DATES: Record<string, string> = {
  "quick10-compound-dream-vs-crash-reality-guide": "2026-05-12T09:00:00+08:00",
  "quick10-if-crash-hits-last-year-what-happens": "2026-05-24T09:00:00+08:00",
  "quick10-20percent-drop-stress-case": "2026-06-05T09:00:00+08:00",
  "quick10-30percent-drop-stress-case": "2026-06-17T09:00:00+08:00",
  "quick10-40percent-drop-stress-case": "2026-06-29T09:00:00+08:00",
  "quick10-withdrawal-need-during-crash": "2026-07-11T09:00:00+08:00",
  "quick10-emergency-fund-before-risk-assets": "2026-07-23T09:00:00+08:00",
  "quick10-sequence-risk-for-near-retire": "2026-08-04T09:00:00+08:00",
  "quick10-sell-in-panic-vs-hold-discipline": "2026-08-16T09:00:00+08:00",
  "quick10-recovery-years-after-big-drawdown": "2026-08-28T09:00:00+08:00",
  "quick10-asset-allocation-under-crash": "2026-09-09T09:00:00+08:00",
  "quick10-hedge-cash-bond-equity-balance": "2026-09-21T09:00:00+08:00",
  "quick10-income-stability-vs-risk-capacity": "2026-10-03T09:00:00+08:00",
  "quick10-job-loss-plus-market-crash-plan": "2026-10-15T09:00:00+08:00",
  "quick10-family-protection-during-drawdown": "2026-10-27T09:00:00+08:00",
  "quick10-annual-crash-rehearsal-checklist": "2026-11-08T09:00:00+08:00",
  "quick10-avoid-overoptimistic-return-setting": "2026-11-20T09:00:00+08:00",
  "quick10-sleep-well-portfolio-design": "2026-12-02T09:00:00+08:00",
  "quick10-build-30year-antifragile-habit": "2026-12-14T09:00:00+08:00",
  "quick10-crash-reality-longterm-discipline": "2026-12-26T09:00:00+08:00",
};

const TOPIC_SEEDS: TopicSeed[] = [
  {
    slug: "quick1-monthly-20000-compound-playbook",
    title: "每月投入兩萬，20 年後會自由嗎？先把存股複利計算機打開再說",
    subtitle: "先把焦慮翻成數字，你會比昨天更靠近自由。",
    seoTitle: "每月投入兩萬 20 年後有多少？存股複利計算機複利試算與月領估算教學",
    metaDescription: "以存股複利計算機示範每月投入兩萬的複利路徑，從月投、年數到月領估算，幫你把理想變成可執行計畫。",
    focus: "每月投入兩萬",
    keywordA: "每月投入兩萬 20 年後有多少",
    keywordB: "定期定額多久能退休",
    keywordC: "複利計算器月領怎麼算",
    closeQuestion: "你會先調高月投入，還是先調高「不中斷投入」的穩定度？",
  },
  {
    slug: "quick1-first-million-discipline-map",
    title: "第一個一百萬不是天分題，是節奏題：用存股複利計算機把路線畫出來",
    subtitle: "你需要的不是神準預測，而是能活 10 年的投入節奏。",
    seoTitle: "第一桶金要多久？存股複利計算機解析每月投入與複利時間軸",
    metaDescription: "用存股複利計算機拆解第一桶金累積時間，實測不同月投入與年數設定，找到最能長期執行的版本。",
    focus: "第一桶金時間軸",
    keywordA: "第一桶金要多久",
    keywordB: "每月存多少可以到一百萬",
    keywordC: "複利計算器設定方式",
    closeQuestion: "你現在的月投入，是能做 36 個月的版本嗎？",
  },
  {
    slug: "quick1-retirement-monthly-cashflow-baseline",
    title: "退休月領怎麼抓才不自欺？先用存股複利計算機算出你的底線版本",
    subtitle: "退休不是喊口號，是每個月把底線往上墊高。",
    seoTitle: "退休月領金額如何估算？存股複利計算機實作月投與年數規劃",
    metaDescription: "從退休月領倒推月投入，利用存股複利計算機建立可執行的退休現金流底線，減少焦慮與瞎猜。",
    focus: "退休月領底線",
    keywordA: "退休月領金額如何估算",
    keywordB: "每月投入多少才有被動收入",
    keywordC: "退休試算怎麼做",
    closeQuestion: "你想要的是「不用上班」，還是「可以自由選工作」？",
  },
  {
    slug: "quick1-monthly-10000-vs-15000-gap",
    title: "月投一萬和一萬五，差在哪？不是 5000 而已",
    subtitle: "差距會被時間放大，重點是你願不願意看見它。",
    seoTitle: "月投一萬 vs 一萬五差多少？存股複利計算機比較 20 年資產差距",
    metaDescription: "比較月投一萬與一萬五在不同年數下的複利結果，搭配存股複利計算機找出你可負擔且有感的加碼策略。",
    focus: "月投級距比較",
    keywordA: "月投一萬和一萬五差多少",
    keywordB: "提高月投入有用嗎",
    keywordC: "複利差距比較",
    closeQuestion: "你現在可以多加多少，才不會讓生活直接失衡？",
  },
  {
    slug: "quick1-bonus-lump-sum-yearly-plan",
    title: "年終獎金該花掉還是加碼？用一個按鈕看 10 年差距",
    subtitle: "不是不能花，而是先算過再花。",
    seoTitle: "年終獎金投資怎麼分配？存股複利計算機看一次加碼的長期效果",
    metaDescription: "以存股複利計算機模擬年終加碼與不加碼兩種路線，幫你評估獎金分配和長期資產成長的關係。",
    focus: "年終獎金加碼",
    keywordA: "年終獎金要不要投資",
    keywordB: "一次加碼有用嗎",
    keywordC: "獎金投資規劃",
    closeQuestion: "今年的獎金，你要全部花掉，還是留一部分給未來的你？",
  },
  {
    slug: "quick1-salary-growth-stepup-plan",
    title: "加薪後月投該怎麼調？先調多少才不會三個月後崩掉",
    subtitle: "加薪不是全拿去升級消費，留一點給複利會很有感。",
    seoTitle: "加薪後要提高多少月投？存股複利計算機試算最穩升級幅度",
    metaDescription: "加薪後如何調整月投入才可持續？用存股複利計算機比較不同加碼比例，避免短期衝動長期斷線。",
    focus: "加薪後月投調整",
    keywordA: "加薪後月投要加多少",
    keywordB: "加薪理財分配",
    keywordC: "提高投入不痛苦方法",
    closeQuestion: "你會把加薪的幾成交給未來，而不是全部留給當下？",
  },
  {
    slug: "quick1-bear-market-keep-investing",
    title: "市場下跌還要繼續投入嗎？先別靠感覺，先看長線",
    subtitle: "最難的不是看懂走勢，是在波動裡保持節奏。",
    seoTitle: "股市下跌還要定期定額嗎？存股複利計算機看長期投入優勢",
    metaDescription: "面對市場回檔，透過存股複利計算機觀察持續投入與停扣的長期差異，建立可執行的抗波動策略。",
    focus: "下跌時持續投入",
    keywordA: "股市下跌還要定期定額嗎",
    keywordB: "停扣影響有多大",
    keywordC: "熊市投資心態",
    closeQuestion: "下次下跌來時，你要停手，還是照計畫慢慢買？",
  },
  {
    slug: "quick1-inflation-adjusted-goals",
    title: "你以為目標是 2000 萬？加上時間後可能根本不夠",
    subtitle: "目標不是固定數字，而是會隨時間變動的生活成本。",
    seoTitle: "退休目標金額怎麼抓？存股複利計算機搭配通膨思維調整目標",
    metaDescription: "用存股複利計算機先看資產路徑，再以通膨思維校正退休目標，避免只看名目數字造成判斷偏差。",
    focus: "目標金額校正",
    keywordA: "退休目標金額怎麼算",
    keywordB: "通膨下資產規劃",
    keywordC: "名目和實質差異",
    closeQuestion: "你的目標數字，有把未來的生活成本算進去嗎？",
  },
  {
    slug: "quick1-couple-joint-invest-plan",
    title: "伴侶理財常吵架？先用同一張圖看同一件事",
    subtitle: "不是誰對誰錯，而是你們看的是不同版本的未來。",
    seoTitle: "情侶夫妻如何一起投資？存股複利計算機建立共同月投計畫",
    metaDescription: "提供伴侶共同理財流程，透過存股複利計算機對齊月投入與年數期待，減少情緒衝突與目標落差。",
    focus: "伴侶共同規劃",
    keywordA: "夫妻理財怎麼分配",
    keywordB: "情侶共同投資規劃",
    keywordC: "家庭月投設定",
    closeQuestion: "你們吵的是錢，還是其實沒對齊同一個時間軸？",
  },
  {
    slug: "quick1-late-start-catchup-strategy",
    title: "30 歲才開始會太晚嗎？你真正需要的是追回路徑",
    subtitle: "晚開始不等於沒機會，怕的是晚開始又不開始。",
    seoTitle: "30 歲才開始投資來得及嗎？存股複利計算機追回策略教學",
    metaDescription: "針對晚起步族群，示範如何用存股複利計算機調整月投入與年數，建立可追趕但不爆壓的理財路線。",
    focus: "晚開始追趕",
    keywordA: "30歲開始投資來得及嗎",
    keywordB: "晚開始理財怎麼追",
    keywordC: "追趕複利策略",
    closeQuestion: "你要花時間後悔，還是花時間把路線追回來？",
  },
  {
    slug: "quick1-freelancer-irregular-income-plan",
    title: "收入不固定怎麼月投？接案族的穩定投入方法",
    subtitle: "不規律收入，也能做出有規律的投入。",
    seoTitle: "自由工作者如何定期定額？存股複利計算機設計彈性月投法",
    metaDescription: "給接案與收入波動族群的月投配置建議，透過存股複利計算機建立高低月雙版本，降低中斷機率。",
    focus: "不固定收入月投",
    keywordA: "收入不固定怎麼投資",
    keywordB: "接案族定期定額",
    keywordC: "彈性月投規劃",
    closeQuestion: "你的投資計畫，有替淡季預留呼吸空間嗎？",
  },
  {
    slug: "quick1-parenting-education-retire-balance",
    title: "有小孩後還能存退休嗎？先把兩個目標拆開算",
    subtitle: "教育金和退休金都重要，先排序就不會亂。",
    seoTitle: "有小孩怎麼規劃退休？存股複利計算機平衡教育金與退休金",
    metaDescription: "示範家庭在教育支出與退休準備並行時，如何用存股複利計算機設計雙軌月投與年期策略。",
    focus: "教育與退休平衡",
    keywordA: "有小孩怎麼存退休",
    keywordB: "教育金退休金分配",
    keywordC: "家庭理財月投",
    closeQuestion: "你家目前的理財順序，真的符合你們最在意的生活嗎？",
  },
  {
    slug: "quick1-debt-first-or-invest-first",
    title: "先還債還是先投資？不是二選一，重點在比例",
    subtitle: "極端答案很爽，但通常不適合真實生活。",
    seoTitle: "先還債還是先投資？存股複利計算機拆解現金流比例配置",
    metaDescription: "透過存股複利計算機模擬不同還債與月投比例，找出兼顧壓力管理與資產成長的務實解法。",
    focus: "還債投資比例",
    keywordA: "先還債還是先投資",
    keywordB: "負債時怎麼理財",
    keywordC: "現金流比例配置",
    closeQuestion: "你現在的分配，是在降低焦慮，還是在放大焦慮？",
  },
  {
    slug: "quick1-year-end-rebalance-checklist",
    title: "年底理財健檢怎麼做？每年一次就很有感",
    subtitle: "不用複雜，只要固定檢查三個數字。",
    seoTitle: "年底理財健檢清單：用存股複利計算機回顧月投與年數進度",
    metaDescription: "提供年度理財檢查流程，搭配存股複利計算機回顧月投入、年數進度與月領目標，建立長期迭代習慣。",
    focus: "年度健檢",
    keywordA: "年底理財健檢怎麼做",
    keywordB: "年度投資回顧",
    keywordC: "理財檢查清單",
    closeQuestion: "今年你的理財成績，是靠運氣還是靠流程？",
  },
  {
    slug: "quick1-emergency-fund-before-invest",
    title: "緊急預備金要先存嗎？先存多少才算夠",
    subtitle: "先把安全墊鋪好，投資才不會遇事就停。",
    seoTitle: "緊急預備金要存多少？存股複利計算機搭配安全墊與月投規劃",
    metaDescription: "說明緊急預備金與月投的先後與並行方式，透過存股複利計算機設計不易中斷的長期策略。",
    focus: "安全墊與月投",
    keywordA: "緊急預備金要存多少",
    keywordB: "先存錢還是先投資",
    keywordC: "預備金與月投比例",
    closeQuestion: "你現在的策略，遇到一次突發支出會不會整套中斷？",
  },
  {
    slug: "quick1-etf-dividend-reinvest-idea",
    title: "配息到底該花還是再投入？一個選擇，十年差很多",
    subtitle: "再投入不是神話，但長期很誠實。",
    seoTitle: "ETF 配息要花掉還是再投入？存股複利計算機看長期差異",
    metaDescription: "以存股複利計算機比較配息再投入與不再投入兩種路徑，協助你建立符合生活與目標的資金使用規則。",
    focus: "配息再投入",
    keywordA: "配息要不要再投入",
    keywordB: "ETF配息理財",
    keywordC: "再投入效果",
    closeQuestion: "你想要的是短期舒服，還是長期更有選擇權？",
  },
  {
    slug: "quick1-target-30000-passive-income",
    title: "目標月領 3 萬，月投要多少才比較有機會",
    subtitle: "先看到底線，再決定要加碼還是延長時間。",
    seoTitle: "月領 3 萬怎麼規劃？存股複利計算機倒推月投入與年期",
    metaDescription: "針對月領三萬元目標，利用存股複利計算機倒推所需月投入與年數，建立可執行退休現金流路線。",
    focus: "月領3萬倒推",
    keywordA: "月領三萬要存多少",
    keywordB: "被動收入三萬規劃",
    keywordC: "退休月領倒推",
    closeQuestion: "你會先提高投入，還是先延長計畫年期？",
  },
  {
    slug: "quick1-monthly-5min-review-system",
    title: "每月只花 5 分鐘，也能把理財做得很穩",
    subtitle: "不是你沒時間，是沒有固定節奏。",
    seoTitle: "每月理財回顧怎麼做？存股複利計算機 5 分鐘檢查流程",
    metaDescription: "建立每月五分鐘理財檢查習慣，透過存股複利計算機追蹤月投、年數與月領偏差，持續修正不焦慮。",
    focus: "每月5分鐘回顧",
    keywordA: "每月理財回顧流程",
    keywordB: "理財習慣怎麼養成",
    keywordC: "5分鐘檢查法",
    closeQuestion: "你願意每月固定 5 分鐘，換長期少很多焦慮嗎？",
  },
  {
    slug: "quick1-avoid-over-optimistic-return",
    title: "報酬率別一開始就填太高，這是最常見的自我欺騙",
    subtitle: "樂觀不是錯，但只用樂觀一定會痛。",
    seoTitle: "複利試算報酬率怎麼設定？存股複利計算機的保守中性樂觀三版法",
    metaDescription: "示範保守、中性、樂觀三組報酬率的試算方法，搭配存股複利計算機降低過度樂觀帶來的規劃失真。",
    focus: "報酬率三版法",
    keywordA: "複利報酬率怎麼設定",
    keywordB: "理財假設太樂觀",
    keywordC: "保守中性樂觀試算",
    closeQuestion: "你現在用的報酬率，是你希望的，還是你承受得了的？",
  },
  {
    slug: "quick1-build-30year-freedom-habit",
    title: "30 年自由不是一個決定，是一個可以活下去的習慣",
    subtitle: "先把節奏守住，時間自然會幫你放大結果。",
    seoTitle: "30 年財富自由路線圖：存股複利計算機建立長期投入習慣",
    metaDescription: "以存股複利計算機打造 30 年可持續投入習慣，從月投紀律到年期管理，建立穩定放大的資產引擎。",
    focus: "30年長期習慣",
    keywordA: "30年投資規劃",
    keywordB: "長期投入習慣",
    keywordC: "財富自由路線圖",
    closeQuestion: "你今天做的哪個小動作，能讓 10 年後的你說聲謝謝？",
  },
  {
    slug: "quick2-freedom-countdown-target-years",
    title: "💣 財富自由倒數計時器怎麼用？先算清楚你距離目標還有幾年",
    subtitle: "這台不是拿來做夢，是拿來把時間壓力說清楚。",
    seoTitle: "財富自由倒數計時器教學：目標月領與月投入怎麼設定才務實",
    metaDescription:
      "用第二台財富自由倒數計時器，從目標月領與每月投入倒推達標年數。適合想快速看清退休時間軸與調整方向的讀者。",
    focus: "財富自由倒數計時器",
    keywordA: "財富自由倒數計時器怎麼用",
    keywordB: "目標月領要設多少",
    keywordC: "每月投入幾年達成",
    closeQuestion: "你比較想先拉高月投入，還是先把目標月領調到能長期承受的版本？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
    calculatorNote: "先填目標月領，再填每月投入，直接看達標年數。先求可執行，再求速度。",
  },
  {
    slug: "quick2-monthly-40000-countdown",
    title: "月領 4 萬倒數怎麼抓？先看幾年達標，再談加碼",
    subtitle: "先把時間壓力看清楚，你就不會亂衝。",
    seoTitle: "月領 4 萬要幾年達成？財富自由倒數計時器實測",
    metaDescription: "透過財富自由倒數計時器，示範月領 4 萬目標下，月投入與達標年數的關係，快速找到可執行節奏。",
    focus: "月領4萬倒數",
    keywordA: "月領4萬要幾年",
    keywordB: "月投入和達標年數",
    keywordC: "退休倒數試算",
    closeQuestion: "你會先提高投入，還是先接受更長的時間軸？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-monthly-50000-countdown",
    title: "目標月領 5 萬，達標年數為何差這麼多？",
    subtitle: "同樣努力，不同起跑值，時間差可能很大。",
    seoTitle: "月領 5 萬需要多久？財富自由倒數計時器教學",
    metaDescription: "比較不同月投入下，月領 5 萬目標的達標時間，利用財富自由倒數計時器找到更務實路線。",
    focus: "月領5萬達標年",
    keywordA: "月領5萬多久達成",
    keywordB: "退休月領目標設定",
    keywordC: "達標時間比較",
    closeQuestion: "你現在的目標月領，是理想值還是可持續值？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-monthly-60000-countdown",
    title: "月領 6 萬不是不能追，先看你要拿什麼交換",
    subtitle: "時間、投入、生活壓力，三者一定要平衡。",
    seoTitle: "月領 6 萬怎麼規劃？財富自由倒數計時器倒推年數",
    metaDescription: "用財富自由倒數計時器分析月領 6 萬目標，評估不同投入對達標年數與壓力的影響。",
    focus: "月領6萬規劃",
    keywordA: "月領6萬怎麼達成",
    keywordB: "倒推達標年數",
    keywordC: "高月領規劃",
    closeQuestion: "你要更快，還是要更穩？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-raise-invest-or-extend-years",
    title: "該加碼還是延長年數？倒數計時器一看就懂",
    subtitle: "同一目標，不同策略，壓力感差很多。",
    seoTitle: "加碼月投或延長年數哪個好？財富自由倒數計時器比較",
    metaDescription: "比較『提高月投入』與『拉長年數』兩種策略，利用財富自由倒數計時器看哪個更符合你的生活。",
    focus: "加碼或延長",
    keywordA: "加碼還是延長年數",
    keywordB: "月投策略比較",
    keywordC: "達標策略選擇",
    closeQuestion: "你比較能承受短期壓力，還是長期等待？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-first-10-years-gap",
    title: "前 10 年最容易放棄：先把倒數做成可執行版本",
    subtitle: "不是你沒毅力，是設定太硬。",
    seoTitle: "前 10 年投資最難怎麼撐？財富自由倒數計時器思路",
    metaDescription: "用財富自由倒數計時器把目標拆小，降低前 10 年心理壓力，提高持續投入機率。",
    focus: "前10年持續",
    keywordA: "投資前10年怎麼撐",
    keywordB: "如何避免中途放棄",
    keywordC: "理財可執行版本",
    closeQuestion: "你現在的設定，是幫你前進，還是逼你放棄？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-salary-plateau-countdown",
    title: "薪水卡住怎麼辦？倒數計時器幫你重排路線",
    subtitle: "收入不變時，更要把時間與投入配好。",
    seoTitle: "薪水沒成長也能退休嗎？財富自由倒數計時器規劃法",
    metaDescription: "針對收入成長有限族群，示範如何用財富自由倒數計時器重排投入與年數，維持達標可能。",
    focus: "薪資停滯規劃",
    keywordA: "薪水不漲怎麼理財",
    keywordB: "收入停滯退休規劃",
    keywordC: "倒數計時器規劃",
    closeQuestion: "如果收入短期不變，你願意先調整哪個旋鈕？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-double-income-household-target",
    title: "雙薪家庭如何定目標月領？先把共同時間軸對齊",
    subtitle: "兩個人的投入節奏，必須用同一張圖討論。",
    seoTitle: "雙薪家庭退休目標怎麼抓？財富自由倒數計時器實作",
    metaDescription: "給雙薪家庭的倒數規劃範例，透過財富自由倒數計時器對齊目標月領、投入金額與達標時間。",
    focus: "雙薪目標對齊",
    keywordA: "雙薪家庭退休規劃",
    keywordB: "家庭目標月領設定",
    keywordC: "共同理財時間軸",
    closeQuestion: "你們現在的理財溝通，是在對齊目標還是在互相消耗？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-single-income-pressure-map",
    title: "單薪壓力很大？先用倒數計時器找到不爆表版本",
    subtitle: "先活得下去，才有機會走得下去。",
    seoTitle: "單薪族如何規劃退休？財富自由倒數計時器路線圖",
    metaDescription: "單薪族可用財富自由倒數計時器，找出不超壓的月投入與可接受達標年數，建立穩定路線。",
    focus: "單薪壓力地圖",
    keywordA: "單薪族退休規劃",
    keywordB: "單薪月投設定",
    keywordC: "壓力不爆表理財",
    closeQuestion: "你現在追的是速度，還是可持續？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-bonus-allocation-countdown",
    title: "有獎金時，倒數應該怎麼縮短才最有感？",
    subtitle: "一次加碼可以快，但要放在對的位置。",
    seoTitle: "獎金怎麼用能縮短退休年數？財富自由倒數計時器試算",
    metaDescription: "示範有獎金時如何用倒數計時器比較不同加碼策略，找到對達標年數最有感的配置。",
    focus: "獎金縮短倒數",
    keywordA: "獎金怎麼縮短退休",
    keywordB: "一次加碼怎麼配",
    keywordC: "達標年數縮短",
    closeQuestion: "你的獎金，想買當下快樂，還是買未來時間？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-lifestyle-upgrade-warning",
    title: "生活升級前先看倒數：別讓目標越來越遠",
    subtitle: "收入增加不代表你一定更接近自由。",
    seoTitle: "生活升級會拖慢退休嗎？財富自由倒數計時器提醒",
    metaDescription: "利用財富自由倒數計時器，在生活升級前先檢查達標年數變化，避免無感延後退休目標。",
    focus: "生活升級警訊",
    keywordA: "生活升級拖慢退休",
    keywordB: "收入增加卻沒存到錢",
    keywordC: "退休目標越來越遠",
    closeQuestion: "這次升級真的值得，還是只是習慣性加開銷？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-early-retire-vs-slower-path",
    title: "提早退休還是慢慢退？倒數計時器讓選擇更清楚",
    subtitle: "你不只在選年份，也在選生活節奏。",
    seoTitle: "提早退休可行嗎？財富自由倒數計時器比較快慢兩路",
    metaDescription: "比較激進與穩健兩種退休路線，透過財富自由倒數計時器看壓力與達標時間差距。",
    focus: "快慢路線比較",
    keywordA: "提早退休可行嗎",
    keywordB: "退休快慢路線",
    keywordC: "達標年數比較",
    closeQuestion: "你要的是最早退休，還是最穩退休？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-bear-market-delay-check",
    title: "市場下跌會讓倒數延長嗎？先把心理預期校正",
    subtitle: "知道會變慢，比突然受傷好太多。",
    seoTitle: "市場下跌退休倒數會延後嗎？財富自由倒數計時器示意",
    metaDescription: "用倒數計時器建立下跌情境心理預期，理解達標年數可能延長，減少恐慌式停扣。",
    focus: "下跌延長預期",
    keywordA: "市場下跌退休延後",
    keywordB: "下跌時怎麼維持投入",
    keywordC: "倒數延長怎麼辦",
    closeQuestion: "你有為逆風準備備案，還是只準備順風劇本？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-annual-review-reset-plan",
    title: "每年重算一次倒數，為什麼比你想像更重要",
    subtitle: "不重算，計畫就會默默過期。",
    seoTitle: "年度重算退休倒數怎麼做？財富自由倒數計時器流程",
    metaDescription: "建立每年重算倒數習慣，利用財富自由倒數計時器校正目標月領、投入與達標年數。",
    focus: "年度重算倒數",
    keywordA: "年度重算退休計畫",
    keywordB: "理財計畫多久更新",
    keywordC: "退休倒數校正",
    closeQuestion: "你的目標還是去年的版本，還是今年的現實版本？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-40000-to-60000-upgrade-roadmap",
    title: "目標從 4 萬升到 6 萬：該怎麼升級不爆壓",
    subtitle: "目標可以升，節奏更要跟著升。",
    seoTitle: "目標月領從 4 萬到 6 萬怎麼調？財富自由倒數計時器規劃",
    metaDescription: "用倒數計時器示範目標升級時，如何同步調整投入與年數，避免理想升級但執行崩盤。",
    focus: "月領升級路線",
    keywordA: "月領目標升級",
    keywordB: "4萬到6萬規劃",
    keywordC: "退休升級策略",
    closeQuestion: "你想升級的是數字，還是整體可執行能力？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-starting-late-with-high-goal",
    title: "晚開始又高目標，真的沒機會嗎？先看倒數拆解",
    subtitle: "你需要的是策略，不是自責。",
    seoTitle: "晚開始還能追高月領嗎？財富自由倒數計時器拆解法",
    metaDescription: "針對晚起步且高目標族群，透過倒數計時器拆解可行路線，平衡速度與壓力。",
    focus: "晚開始高目標",
    keywordA: "晚開始高目標退休",
    keywordB: "晚開始怎麼追",
    keywordC: "退休倒數拆解",
    closeQuestion: "你要繼續內耗，還是開始重排可行路線？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-stress-free-monthly-input",
    title: "月投入要設到剛好痛，還是幾乎無痛？",
    subtitle: "太痛會斷，太鬆會慢，重點是平衡。",
    seoTitle: "月投入怎麼設最穩？財富自由倒數計時器找平衡點",
    metaDescription: "利用財富自由倒數計時器尋找投入壓力與達標速度平衡，建立不中斷的長期理財節奏。",
    focus: "投入壓力平衡",
    keywordA: "月投入要設多少",
    keywordB: "理財投入壓力",
    keywordC: "可持續月投",
    closeQuestion: "你現在是為了快而痛苦，還是為了穩而前進？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-housing-cost-impact-countdown",
    title: "房租變動會影響退休倒數嗎？先算就不慌",
    subtitle: "固定支出一變，整條時間軸都會動。",
    seoTitle: "房租上升會延後退休嗎？財富自由倒數計時器檢查法",
    metaDescription: "在租金或居住成本變動時，用倒數計時器快速重算達標年數，及時修正投入策略。",
    focus: "居住成本影響",
    keywordA: "房租上升退休影響",
    keywordB: "居住成本理財",
    keywordC: "倒數重算方法",
    closeQuestion: "你的計畫有替生活成本上升留空間嗎？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-family-support-pressure",
    title: "要支援家人時，退休倒數該怎麼調整才不失速",
    subtitle: "責任增加，不代表目標一定要放棄。",
    seoTitle: "家庭支援壓力下如何維持退休進度？倒數計時器示範",
    metaDescription: "面對家庭支援支出，利用財富自由倒數計時器調整投入與年數，維持可前進但不崩盤的節奏。",
    focus: "家庭支援調整",
    keywordA: "家庭支援理財調整",
    keywordB: "退休進度維持",
    keywordC: "支出增加怎麼辦",
    closeQuestion: "你願意怎麼調，才能同時守住責任與未來？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick2-side-income-accelerator",
    title: "副業收入要怎麼用，才能最有效縮短倒數",
    subtitle: "有額外收入時，最怕只是額外花掉。",
    seoTitle: "副業收入如何加速退休？財富自由倒數計時器策略",
    metaDescription: "透過倒數計時器比較副業收入的不同分配方式，找出對達標年數最有效的加速策略。",
    focus: "副業加速倒數",
    keywordA: "副業收入怎麼投",
    keywordB: "縮短退休年數方法",
    keywordC: "副業理財配置",
    closeQuestion: "你的副業收入，是在放大目標，還是放大消費？",
    calculatorRoute: "/quick-2",
    calculatorName: "財富自由倒數計時器",
  },
  {
    slug: "quick3-dream-monthly-income-simulator",
    title: "💣 夢想月領試算器：先算出你的夢想月領，才知道月投要多誠實",
    subtitle: "夢想不是不能大，先讓它變成可執行的數字。",
    seoTitle: "夢想月領試算器教學：想月領 5 萬，每月要投多少才合理？",
    metaDescription:
      "用第三台夢想月領試算器，從希望月領與預計年數倒推出建議月投金額，快速建立可執行的退休準備路線。",
    focus: "夢想月領試算器",
    keywordA: "夢想月領試算器怎麼用",
    keywordB: "希望月領5萬要投多少",
    keywordC: "月領倒推月投工具",
    closeQuestion: "你會先調高希望月領，還是先把年數拉長，換一條壓力更低的路？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
    calculatorNote: "先填希望月領，再選預計年數，直接看建議月投。先求能執行，再求更漂亮。",
  },
  {
    slug: "quick3-monthly-30000-reverse-plan",
    title: "夢想月領 3 萬怎麼反推？先算月投再談速度",
    subtitle: "目標先拆清楚，執行才不會亂。",
    seoTitle: "夢想月領 3 萬要月投多少？夢想月領試算器反推教學",
    metaDescription: "用夢想月領試算器示範月領 3 萬目標，從年數倒推每月投入，建立可執行退休計畫。",
    focus: "月領3萬反推",
    keywordA: "月領3萬要月投多少",
    keywordB: "夢想月領試算器",
    keywordC: "反推月投教學",
    closeQuestion: "你現在先要的是穩定做到，還是數字漂亮？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-monthly-40000-reverse-plan",
    title: "夢想月領 4 萬：反推月投時最常算錯哪裡？",
    subtitle: "不是算不出來，是常常設太理想。",
    seoTitle: "月領 4 萬如何反推月投？夢想月領試算器實測",
    metaDescription: "針對月領 4 萬目標，使用夢想月領試算器比較不同年數下的投入需求，避開過度樂觀設定。",
    focus: "月領4萬反推",
    keywordA: "月領4萬月投多少",
    keywordB: "退休目標反推",
    keywordC: "投入需求比較",
    closeQuestion: "你願意先降目標，還是先拉長年數？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-monthly-50000-reverse-plan",
    title: "月領 5 萬夢想版，反推後壓力到底多大？",
    subtitle: "越想快達成，越要先看可承受度。",
    seoTitle: "月領 5 萬反推月投：夢想月領試算器看壓力差距",
    metaDescription: "夢想月領試算器可快速比較月領 5 萬目標下不同年數與投入壓力，幫你選擇可持續版本。",
    focus: "月領5萬反推",
    keywordA: "月領5萬反推月投",
    keywordB: "投入壓力試算",
    keywordC: "可持續目標設定",
    closeQuestion: "你想要更快，還是更穩地走到目標？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-monthly-60000-reverse-plan",
    title: "月領 6 萬不是不行，但要知道代價是什麼",
    subtitle: "目標可以大，節奏要真實。",
    seoTitle: "月領 6 萬要投多少？夢想月領試算器反推達標路線",
    metaDescription: "示範高月領目標下的月投反推方法，利用夢想月領試算器找到速度與壓力的平衡。",
    focus: "月領6萬反推",
    keywordA: "月領6萬要投多少",
    keywordB: "高目標理財規劃",
    keywordC: "反推達標路線",
    closeQuestion: "你真的要快，還是其實要能長期做？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-how-much-per-month-for-15-years",
    title: "15 年內達標要月投多少？",
    subtitle: "縮短時間，代價通常是提高投入。",
    seoTitle: "15 年退休目標怎麼反推月投？夢想月領試算器",
    metaDescription: "以 15 年時間軸為例，透過夢想月領試算器反推每月投入，快速評估可行與不可行區間。",
    focus: "15年反推",
    keywordA: "15年退休月投多少",
    keywordB: "時間軸反推",
    keywordC: "短年限規劃",
    closeQuestion: "你能承受的是高投入，還是更長時間？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-how-much-per-month-for-20-years",
    title: "20 年版本最常見：怎麼反推才不自欺？",
    subtitle: "關鍵不是公式，是你能不能連續做。",
    seoTitle: "20 年退休反推月投教學｜夢想月領試算器",
    metaDescription: "用夢想月領試算器建立 20 年標準版規劃，避開只看理想報酬而忽略執行壓力。",
    focus: "20年反推",
    keywordA: "20年月投反推",
    keywordB: "退休標準版規劃",
    keywordC: "可執行理財",
    closeQuestion: "你現在的 20 年版本，是理想版還是實戰版？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-how-much-per-month-for-25-years",
    title: "把時間拉到 25 年，壓力會不會好很多？",
    subtitle: "有時候延長年數，比硬撐投入更有效。",
    seoTitle: "25 年退休路線怎麼反推？夢想月領試算器比較",
    metaDescription: "比較 25 年長期路線下的月投入需求，利用夢想月領試算器找到更穩定的達標方式。",
    focus: "25年反推",
    keywordA: "25年退休規劃",
    keywordB: "延長年數有用嗎",
    keywordC: "長期投入策略",
    closeQuestion: "你願意拿多一點時間，換少很多壓力嗎？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-increase-goal-or-extend-years",
    title: "要升目標，還是先延長年數？",
    subtitle: "順序錯了，很容易三個月後崩掉。",
    seoTitle: "升目標還是延長年數？夢想月領試算器判斷法",
    metaDescription: "針對升級目標時的常見糾結，透過夢想月領試算器比較兩條路線的可執行性。",
    focus: "升目標或延長",
    keywordA: "升目標還是延長年數",
    keywordB: "目標升級策略",
    keywordC: "可執行判斷",
    closeQuestion: "你現在最缺的是時間，還是可持續投入？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-salary-growth-reverse-strategy",
    title: "加薪後怎麼反推新目標？",
    subtitle: "加薪如果沒轉成投入，倒數不會自己變短。",
    seoTitle: "加薪後月領目標怎麼升級？夢想月領試算器策略",
    metaDescription: "用夢想月領試算器示範加薪後目標調整方法，避免生活升級吃掉投入增幅。",
    focus: "加薪反推策略",
    keywordA: "加薪後目標調整",
    keywordB: "月領目標升級",
    keywordC: "加薪理財策略",
    closeQuestion: "你會把加薪留給現在，還是分一部分給未來？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-single-income-reverse-plan",
    title: "單薪版反推：如何不爆壓還能前進",
    subtitle: "先守住節奏，再慢慢加速。",
    seoTitle: "單薪族月領目標反推：夢想月領試算器實戰",
    metaDescription: "單薪族使用夢想月領試算器，反推可承受投入與時間軸，避免高壓設定造成中斷。",
    focus: "單薪反推",
    keywordA: "單薪月領目標反推",
    keywordB: "單薪退休規劃",
    keywordC: "不爆壓投入",
    closeQuestion: "你現在的設定，是在幫你走得遠還是走得累？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-double-income-reverse-plan",
    title: "雙薪反推：怎麼讓兩個人的節奏對齊",
    subtitle: "不是誰投得多，而是同一張時間軸。",
    seoTitle: "雙薪家庭月領目標反推｜夢想月領試算器",
    metaDescription: "夢想月領試算器可協助雙薪家庭對齊目標、投入與年數，降低理財溝通摩擦。",
    focus: "雙薪反推",
    keywordA: "雙薪家庭反推月投",
    keywordB: "家庭目標對齊",
    keywordC: "雙薪理財節奏",
    closeQuestion: "你們現在是同隊合作，還是各算各的？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-bonus-topup-reverse-plan",
    title: "有獎金時，反推結果怎麼優化最有感",
    subtitle: "一次加碼要加在對的地方。",
    seoTitle: "獎金加碼如何優化月領目標？夢想月領試算器",
    metaDescription: "用夢想月領試算器比較有獎金與無獎金版本，找出對目標月領最有效的加碼方式。",
    focus: "獎金反推優化",
    keywordA: "獎金加碼理財",
    keywordB: "月領目標優化",
    keywordC: "一次加碼策略",
    closeQuestion: "你的獎金，會變成資產加速器嗎？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-late-start-reverse-path",
    title: "晚開始怎麼反推？先把路線拆細",
    subtitle: "晚不代表沒機會，不拆才沒機會。",
    seoTitle: "晚開始投資如何反推月領目標？夢想月領試算器",
    metaDescription: "針對晚起步族群，透過夢想月領試算器拆解目標與投入，建立可追趕路徑。",
    focus: "晚開始反推",
    keywordA: "晚開始反推月投",
    keywordB: "追趕目標路線",
    keywordC: "晚起步理財",
    closeQuestion: "你要繼續拖延，還是先開啟可追趕版本？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-inflation-adjusted-monthly-goal",
    title: "月領目標要不要加通膨？不加常常會錯估",
    subtitle: "名目數字好看，不代表未來夠用。",
    seoTitle: "月領目標要含通膨嗎？夢想月領試算器校正法",
    metaDescription: "用夢想月領試算器先做基礎反推，再加入通膨思維校正目標，避免低估未來需求。",
    focus: "通膨校正目標",
    keywordA: "月領目標通膨",
    keywordB: "退休目標校正",
    keywordC: "實質購買力",
    closeQuestion: "你現在追的是漂亮數字，還是實際生活力？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-risk-buffer-before-goal-upgrade",
    title: "升目標前先留緩衝，不然很容易半路掉隊",
    subtitle: "先有餘裕，再追更高月領。",
    seoTitle: "升級月領目標前要先留多少緩衝？夢想月領試算器",
    metaDescription: "示範升目標前先設緩衝的反推方法，透過夢想月領試算器降低中途放棄風險。",
    focus: "升級前緩衝",
    keywordA: "升目標前要留緩衝",
    keywordB: "中途放棄怎麼避免",
    keywordC: "反推風險控管",
    closeQuestion: "你想追更高目標，還是先把穩定度拉高？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-side-income-accelerate-goal",
    title: "副業收入怎麼用，反推結果才會真的變短",
    subtitle: "多賺的錢，最怕只是多花掉。",
    seoTitle: "副業收入如何加速月領目標？夢想月領試算器",
    metaDescription: "比較副業收入的不同用途，利用夢想月領試算器找出最能縮短目標時間的分配方式。",
    focus: "副業加速目標",
    keywordA: "副業收入怎麼用",
    keywordB: "加速月領目標",
    keywordC: "副業資金分配",
    closeQuestion: "你的副業，是在補現在，還是在加速未來？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-annual-reset-reverse-checklist",
    title: "每年一次反推重設，能省下很多焦慮",
    subtitle: "不重設，計畫就會和現實脫節。",
    seoTitle: "年更月領目標反推清單｜夢想月領試算器",
    metaDescription: "用夢想月領試算器建立年度重設流程，讓目標月領、投入與年數跟著現實更新。",
    focus: "年度反推重設",
    keywordA: "年度反推清單",
    keywordB: "目標年更流程",
    keywordC: "理財重設",
    closeQuestion: "你今年的目標，是新版本還是去年舊版本？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-expense-cut-vs-income-rise",
    title: "省支出和增收入，哪個對反推比較快？",
    subtitle: "答案常常不是二選一，而是先後順序。",
    seoTitle: "省支出 vs 增收入哪個更快達標？夢想月領試算器比較",
    metaDescription: "比較降低支出與提高收入兩條路，透過夢想月領試算器評估對月領目標的影響速度。",
    focus: "省支出或增收入",
    keywordA: "省支出還是增收入",
    keywordB: "達標速度比較",
    keywordC: "反推策略優先序",
    closeQuestion: "你下一步該先省，還是先賺？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick3-avoid-overoptimistic-goal-gap",
    title: "目標別設太樂觀，反推失真會讓你更焦慮",
    subtitle: "先誠實，再樂觀，才走得長。",
    seoTitle: "避免反推過度樂觀：夢想月領試算器務實設定法",
    metaDescription: "說明夢想月領反推常見過度樂觀問題，提供務實設定方法，提升長期執行率。",
    focus: "避免過度樂觀",
    keywordA: "反推太樂觀怎麼辦",
    keywordB: "務實月領設定",
    keywordC: "長期執行率",
    closeQuestion: "你現在是在規劃未來，還是在安慰現在？",
    calculatorRoute: "/quick-3",
    calculatorName: "夢想月領試算器",
  },
  {
    slug: "quick4-etf-monthly-income-simulator-guide",
    title: "💣 ETF 月領試算器：先算現金流，再決定 ETF 配置",
    subtitle: "不是配息越高越好，先看你每月實際想領多少。",
    seoTitle: "ETF 月領試算器教學：目標月領倒推資產與投入策略",
    metaDescription:
      "用第四台 ETF 月領試算器，先從目標月領反推資產需求，再回頭校正投入節奏，打造較穩定的退休現金流計畫。",
    focus: "ETF 月領試算器",
    keywordA: "ETF月領試算器怎麼用",
    keywordB: "ETF月領要準備多少資產",
    keywordC: "ETF退休現金流規劃",
    closeQuestion: "你現在的 ETF 目標，是在追高配息，還是在追可持續月領？",
    calculatorRoute: "/quick-4",
    calculatorName: "ETF 月領試算器",
    calculatorNote: "先填目標月領，再看反推資產與投入。先求穩定，再追效率。",
  },
  {
    slug: "quick5-principal-vs-compound-reality",
    title: "💣 雪球效應：本金 vs 複利｜你以為在存錢，其實在買時間",
    subtitle: "本金成長看起來慢，複利成長常在後段突然拉開。",
    seoTitle: "雪球效應：本金 vs 複利教學｜同月投下兩條曲線差距有多大",
    metaDescription:
      "透過第五台雪球效應：本金 vs 複利，直觀看見同一投入在不同時間軸的差距，幫你建立長期投入耐心。",
    focus: "雪球效應：本金 vs 複利",
    keywordA: "本金複利差距有多大",
    keywordB: "複利什麼時候會明顯",
    keywordC: "定期定額複利對照",
    closeQuestion: "你現在放棄的是一時的焦慮，還是後段最關鍵的複利區間？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
    calculatorNote: "看同一筆月投在本金線與複利線的分岔。先理解時間價值，再談報酬率。",
  },
  {
    slug: "quick5-first-100k-snowball-start",
    title: "第一個 10 萬最慢？雪球效應：本金 vs 複利的起跑觀念",
    subtitle: "最難的是起步，不是複利本身。",
    seoTitle: "第一個10萬怎麼存最快？雪球效應：本金 vs 複利起跑教學",
    metaDescription: "用雪球效應：本金 vs 複利看第一個 10 萬的形成過程，理解起跑期最該守住的投入節奏。",
    focus: "第一個10萬起跑",
    keywordA: "第一個10萬怎麼存",
    keywordB: "複利起跑期怎麼做",
    keywordC: "月投起步策略",
    closeQuestion: "你願意先慢一點但持續，還是快一點卻很快中斷？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-first-500k-compound-curve",
    title: "為什麼 50 萬前看起來很普通？其實你正在進入複利區",
    subtitle: "很多人放棄在最可惜的前段。",
    seoTitle: "存到50萬後會加速嗎？雪球效應：本金 vs 複利曲線解析",
    metaDescription: "透過第五台對照曲線理解 50 萬門檻後的加速感，建立對時間與紀律的正確認知。",
    focus: "50萬門檻曲線",
    keywordA: "存到50萬後會怎樣",
    keywordB: "複利加速點在哪",
    keywordC: "資產曲線成長",
    closeQuestion: "你現在的投入策略，有打算撐過看起來最無聊的那段嗎？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-first-million-snowball-moment",
    title: "第一個 100 萬不是終點，是雪球開始有感的那一刻",
    subtitle: "到這裡才看見時間真正站在你這邊。",
    seoTitle: "第一個100萬之後怎麼走？雪球效應：本金 vs 複利實戰思路",
    metaDescription: "用雪球效應：本金 vs 複利檢視百萬後路線，避免提早鬆懈，讓複利繼續放大成果。",
    focus: "第一個100萬後",
    keywordA: "第一個100萬之後",
    keywordB: "百萬後投資策略",
    keywordC: "雪球效應怎麼放大",
    closeQuestion: "到第一個百萬後，你是想停下來喘，還是把節奏守住？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-10year-vs-20year-gap",
    title: "同樣月投，10 年 vs 20 年差在哪？答案常超過想像",
    subtitle: "差距不是線性，而是被時間放大。",
    seoTitle: "月投10年和20年差多少？雪球效應：本金 vs 複利差距圖",
    metaDescription: "比較同月投入在 10 年與 20 年的結果差，透過對照曲線看懂時間的放大力。",
    focus: "10年vs20年差距",
    keywordA: "月投10年和20年差多少",
    keywordB: "時間對複利影響",
    keywordC: "長期投資差距",
    closeQuestion: "如果時間是最大槓桿，你現在有沒有在好好使用它？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-20year-vs-30year-gap",
    title: "20 年跟 30 年的差，不只多 10 年而已",
    subtitle: "後段的斜率，才是複利最狠的地方。",
    seoTitle: "投資20年和30年差在哪？雪球效應：本金 vs 複利後段威力",
    metaDescription: "透過第五台觀察 20 年與 30 年曲線差，理解長期複利在後段快速拉開的關鍵。",
    focus: "20年vs30年差距",
    keywordA: "投資20年和30年差別",
    keywordB: "複利後段威力",
    keywordC: "延長投資年期價值",
    closeQuestion: "你願不願意多給自己 10 年，把結果放大到真正有感？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-stop-investing-for-1year-impact",
    title: "中斷一年真的差很多嗎？雪球效應：本金 vs 複利直接對照",
    subtitle: "短暫停手，可能讓後段落差擴大。",
    seoTitle: "投資中斷一年影響多大？雪球效應：本金 vs 複利試算",
    metaDescription: "模擬中斷投入一年的影響，利用對照曲線看見節奏斷裂對長期結果的代價。",
    focus: "中斷一年影響",
    keywordA: "投資中斷一年差多少",
    keywordB: "停扣影響",
    keywordC: "持續投入的重要",
    closeQuestion: "你有沒有替自己設計『不想投時也能投』的備案？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-small-increase-big-longterm-gap",
    title: "每月多 1000 看起來很少，長期可能很有感",
    subtitle: "微調，不一定微小。",
    seoTitle: "每月多存1000有用嗎？雪球效應：本金 vs 複利長期差距",
    metaDescription: "以第五台比較月投微幅增加的長期效果，找出不爆生活但能加速路線的調整方式。",
    focus: "小幅加碼長期差",
    keywordA: "每月多存1000有用嗎",
    keywordB: "小額加碼投資",
    keywordC: "長期複利差距",
    closeQuestion: "你願意少一點短期舒適，換長期更大的餘裕嗎？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-monthly-10000-vs-12000",
    title: "月投 10000 vs 12000：你以為只差 2000，其實不只",
    subtitle: "被放大的不是金額，是時間乘上紀律。",
    seoTitle: "月投10000和12000差多少？雪球效應：本金 vs 複利比較",
    metaDescription: "比較月投 10000 與 12000 在長期路徑的差異，幫你找出最可執行的升級幅度。",
    focus: "10000對12000",
    keywordA: "月投10000和12000差多少",
    keywordB: "月投加2000有用嗎",
    keywordC: "定期定額差距",
    closeQuestion: "你現在的版本，是最舒服的，還是最有效的？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-monthly-15000-vs-20000",
    title: "月投 15000 vs 20000：差距何時開始擴大？",
    subtitle: "開始那幾年不明顯，後面通常會拉開。",
    seoTitle: "月投15000和20000差距多大？雪球效應：本金 vs 複利試算",
    metaDescription: "用第五台比較月投 15000 與 20000 的時間差距，幫你判斷加碼是否值得。",
    focus: "15000對20000",
    keywordA: "月投15000和20000差多少",
    keywordB: "加碼5000值不值得",
    keywordC: "月投策略比較",
    closeQuestion: "如果可以加碼，你想一次加大，還是分段加？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-lump-sum-plus-monthly-plan",
    title: "一次投入加每月投入，雪球會滾更快嗎？",
    subtitle: "組合打法，重點是節奏不是衝動。",
    seoTitle: "一次投入搭配月投怎麼配？雪球效應：本金 vs 複利規劃",
    metaDescription: "示範一次投入與定期投入並行的策略，透過對照曲線找出更穩的複利節奏。",
    focus: "一次加碼加月投",
    keywordA: "一次投入加月投",
    keywordB: "加碼策略怎麼配",
    keywordC: "複利節奏規劃",
    closeQuestion: "你的加碼是有計畫，還是每次都憑當下情緒？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-bear-market-continue-or-stop",
    title: "下跌時該停還是續投？雪球效應：本金 vs 複利幫你看長線",
    subtitle: "情緒很吵時，最需要看圖說話。",
    seoTitle: "下跌時停扣還是續投？雪球效應：本金 vs 複利長線比較",
    metaDescription: "在市場回檔情境下，透過第五台對照續投與停手的長期差，降低情緒決策風險。",
    focus: "下跌續投或停手",
    keywordA: "下跌時要不要停扣",
    keywordB: "熊市續投策略",
    keywordC: "情緒投資修正",
    closeQuestion: "下次市場震盪時，你要照情緒，還是照計畫？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-inflation-vs-nominal-balance",
    title: "名目有在長，不代表購買力也在長",
    subtitle: "雪球要看體積，也要看密度。",
    seoTitle: "通膨下的複利怎麼看？雪球效應：本金 vs 複利實用提醒",
    metaDescription: "從名目數字與實質購買力差異出發，搭配第五台建立更務實的長期目標。",
    focus: "通膨與名目差",
    keywordA: "通膨下複利怎麼看",
    keywordB: "名目和實質差異",
    keywordC: "購買力理財",
    closeQuestion: "你在追的數字，能不能真的換到你要的生活？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-expense-growth-eats-snowball",
    title: "支出慢慢長大，可能正在吃掉你的雪球速度",
    subtitle: "看似小調整，長期會很有感。",
    seoTitle: "生活支出上升會拖慢複利嗎？雪球效應：本金 vs 複利對照",
    metaDescription: "示範固定支出上升對月投與長期曲線的影響，幫你提前調整而非事後焦慮。",
    focus: "支出成長拖慢",
    keywordA: "支出上升投資影響",
    keywordB: "月投被生活吃掉",
    keywordC: "理財節奏調整",
    closeQuestion: "你有沒有定期檢查：哪筆支出正在默默吃掉未來？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-salary-growth-boost-compound",
    title: "加薪後怎麼讓雪球更快？不是全加碼，是先分配",
    subtitle: "加薪是一個重設節奏的機會。",
    seoTitle: "加薪後月投怎麼調？雪球效應：本金 vs 複利升級策略",
    metaDescription: "利用第五台比較加薪後不同投入比例，找到可持續又能加速的複利升級版本。",
    focus: "加薪後放大雪球",
    keywordA: "加薪後月投怎麼調",
    keywordB: "加薪理財分配",
    keywordC: "複利加速策略",
    closeQuestion: "這次加薪，你打算幫今天的自己，還是也幫未來的自己？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-risk-buffer-before-acceleration",
    title: "想加速前先放安全墊，雪球才不會遇事就停",
    subtitle: "速度重要，但不中斷更重要。",
    seoTitle: "加速投入前要先做什麼？雪球效應：本金 vs 複利安全墊觀念",
    metaDescription: "說明在加大投入前先建立風險緩衝的必要性，避免計畫因突發事件中斷。",
    focus: "安全墊先行",
    keywordA: "投資前要先準備什麼",
    keywordB: "安全墊與月投",
    keywordC: "避免中斷投入",
    closeQuestion: "你的計畫有備案嗎？還是只在順風時有效？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-annual-rebalance-snowball-check",
    title: "每年檢查一次雪球方向，勝過每天盯盤焦慮",
    subtitle: "路線對，比頻繁動作更重要。",
    seoTitle: "年度複利健檢怎麼做？雪球效應：本金 vs 複利檢查清單",
    metaDescription: "提供年度檢查流程，搭配第五台確認投入節奏是否仍與目標一致。",
    focus: "年度雪球健檢",
    keywordA: "年度理財檢查怎麼做",
    keywordB: "複利路線校正",
    keywordC: "投資健檢清單",
    closeQuestion: "你現在的路線，還是去年那條嗎？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-dividend-reinvest-snowball",
    title: "配息再投入，為什麼常是雪球變大的關鍵",
    subtitle: "看起來小，長期常很關鍵。",
    seoTitle: "配息再投入有差嗎？雪球效應：本金 vs 複利十年觀察",
    metaDescription: "比較配息再投入與不再投入的長期差異，協助你建立適合自己的資金規則。",
    focus: "配息再投入雪球",
    keywordA: "配息再投入有差嗎",
    keywordB: "ETF配息再投資",
    keywordC: "複利放大方法",
    closeQuestion: "你希望配息帶來短期舒服，還是長期更大選擇權？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-why-time-beats-perfect-timing",
    title: "完美進場很難，長時間在場反而更實際",
    subtitle: "你不必抓神點位，也能靠紀律放大結果。",
    seoTitle: "進場時機重要還是時間重要？雪球效應：本金 vs 複利給答案",
    metaDescription: "透過第五台對照理解『長時間在場』的價值，減少追求完美時機造成的拖延。",
    focus: "時間勝過時機",
    keywordA: "進場時機和時間哪個重要",
    keywordB: "長期在場價值",
    keywordC: "定期定額心理建設",
    closeQuestion: "你現在是在等完美時機，還是在累積真實時間？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick5-build-30year-snowball-habit",
    title: "30 年雪球不是奇蹟，是一套可活下去的習慣",
    subtitle: "習慣比天分更能決定長期差距。",
    seoTitle: "30年複利怎麼做得到？雪球效應：本金 vs 複利習慣養成法",
    metaDescription: "以第五台為核心建立 30 年長期投入習慣，從小步穩定到長期放大，打造可持續路線。",
    focus: "30年雪球習慣",
    keywordA: "30年複利怎麼做",
    keywordB: "長期投資習慣",
    keywordC: "雪球效應養成",
    closeQuestion: "你今天願意做哪個小動作，讓 10 年後的自己更有底氣？",
    calculatorRoute: "/quick-5",
    calculatorName: "雪球效應：本金 vs 複利",
  },
  {
    slug: "quick6-leverage-choice-property-vs-global-stocks",
    title: "💣 槓桿抉擇：房產 vs 全球股市｜你不是二選一，是在選現金流壓力",
    subtitle: "同樣都叫資產，現金流體感可能完全不同。",
    seoTitle: "槓桿抉擇：房產 vs 全球股市｜房貸路線與全球股市路線如何比較",
    metaDescription:
      "用第六台槓桿抉擇：房產 vs 全球股市，比較不同房貸支出與投資投入的長期結果，幫你做更貼近生活的配置判斷。",
    focus: "槓桿抉擇：房產 vs 全球股市",
    keywordA: "房產和全球股市怎麼選",
    keywordB: "房貸與全球股市比較",
    keywordC: "現金流壓力試算",
    closeQuestion: "你現在最需要的是資產增值，還是先把每月壓力降到可持續？",
    calculatorRoute: "/quick-6",
    calculatorName: "槓桿抉擇：房產 vs 全球股市",
    calculatorNote: "把房產槓桿與全球股市放進同一張時間軸看。先看壓力，再看收益。",
  },
  {
    slug: "quick6-rent-vs-buy-cashflow-truth",
    title: "租房還是買房？先看每月現金流真相再站隊",
    subtitle: "你要的是資產，還是穩定可活的生活版本。",
    seoTitle: "租房還是買房比較好？槓桿抉擇：房產 vs 全球股市現金流教學",
    metaDescription: "用第六台比較租房與買房路線的每月壓力與長期差，先看現金流，再談信仰。",
    focus: "租房vs買房現金流",
    keywordA: "租房還是買房比較好",
    keywordB: "買房現金流壓力",
    keywordC: "租房投資比較",
    closeQuestion: "你的選擇是在累積資產，還是在累積壓力？",
    calculatorRoute: "/quick-6",
    calculatorName: "槓桿抉擇：房產 vs 全球股市",
  },
  {
    slug: "quick6-down-payment-vs-monthly-invest-gap",
    title: "頭期款拿去買房，和分批投入全球股市，差距在哪？",
    subtitle: "一次大額決策，會改寫未來十年的彈性。",
    seoTitle: "頭期款該買房還是投入ETF？槓桿抉擇：房產 vs 全球股市比較",
    metaDescription: "比較頭期款進房產與分批投入全球股市兩種路線，幫你看懂彈性與機會成本。",
    focus: "頭期款配置取捨",
    keywordA: "頭期款該買房還是投資",
    keywordB: "頭期款機會成本",
    keywordC: "房產投資比較",
    closeQuestion: "你比較在意資產名目，還是現金流彈性？",
    calculatorRoute: "/quick-6",
    calculatorName: "槓桿抉擇：房產 vs 全球股市",
  },
  {
    slug: "quick6-interest-rate-shock-stress-test",
    title: "利率上升時，你的房貸路線撐得住嗎？",
    subtitle: "很多人不是輸在報酬，而是輸在現金流斷裂。",
    seoTitle: "利率上升怎麼影響買房決策？槓桿抉擇：房產 vs 全球股市壓力測試",
    metaDescription: "透過第六台模擬利率變動下的房貸壓力，對照全球股市路線，降低決策盲點。",
    focus: "利率變動壓力測試",
    keywordA: "利率上升房貸影響",
    keywordB: "房貸壓力測試",
    keywordC: "利率和投資配置",
    closeQuestion: "你的計畫有包含利率逆風版本嗎？",
    calculatorRoute: "/quick-6",
    calculatorName: "槓桿抉擇：房產 vs 全球股市",
  },
  {
    slug: "quick6-15year-vs-30year-loan-impact",
    title: "房貸 15 年和 30 年，哪個比較接近你想要的人生？",
    subtitle: "縮短年限不一定更好，重點是可持續。",
    seoTitle: "房貸15年vs30年差在哪？槓桿抉擇：房產 vs 全球股市年限比較",
    metaDescription: "比較房貸不同年限對現金流與長期投資能力的影響，找出你能長期執行的版本。",
    focus: "房貸年限比較",
    keywordA: "房貸15年和30年差別",
    keywordB: "房貸年限怎麼選",
    keywordC: "房貸和投資平衡",
    closeQuestion: "你追求的是快速還清，還是更穩的資金彈性？",
    calculatorRoute: "/quick-6",
    calculatorName: "槓桿抉擇：房產 vs 全球股市",
  },
  {
    slug: "quick6-home-ownership-cost-hidden-list",
    title: "買房最容易漏算的，不是房價，是持有成本",
    subtitle: "漏一筆，整個路線都可能失真。",
    seoTitle: "買房持有成本有哪些？槓桿抉擇：房產 vs 全球股市完整提醒",
    metaDescription: "整理買房後常被忽略的持有成本，搭配第六台對照房產與全球股市路線。",
    focus: "房屋持有隱形成本",
    keywordA: "買房隱形成本有哪些",
    keywordB: "房屋持有成本",
    keywordC: "買房成本試算",
    closeQuestion: "你的買房預算有把『買完之後』算進去嗎？",
    calculatorRoute: "/quick-6",
    calculatorName: "槓桿抉擇：房產 vs 全球股市",
  },
  {
    slug: "quick6-liquidity-trap-property-heavy-portfolio",
    title: "資產都在房子裡，真的比較安心嗎？",
    subtitle: "看起來有資產，不等於可動用。",
    seoTitle: "房產比重太高會怎樣？槓桿抉擇：房產 vs 全球股市流動性分析",
    metaDescription: "說明房產比重過高的流動性風險，並用第六台對照更彈性的全球股市配置路線。",
    focus: "流動性陷阱",
    keywordA: "房產比重太高風險",
    keywordB: "資產流動性不足",
    keywordC: "房產配置比例",
    closeQuestion: "你現在擁有的是資產，還是只是一種看起來安心的幻覺？",
    calculatorRoute: "/quick-6",
    calculatorName: "槓桿抉擇：房產 vs 全球股市",
  },
  {
    slug: "quick6-first-home-or-first-million",
    title: "先買第一間房，還是先存第一個一百萬？",
    subtitle: "先後順序，會影響整個人生的彈性。",
    seoTitle: "先買房還是先存第一桶金？槓桿抉擇：房產 vs 全球股市路線圖",
    metaDescription: "透過第六台比較『先房後投』與『先投後房』兩種策略，找到更適合你的起跑順序。",
    focus: "先房還是先百萬",
    keywordA: "先買房還是先存錢",
    keywordB: "第一桶金和買房順序",
    keywordC: "買房投資先後",
    closeQuestion: "你要先追身份感，還是先追現金流底氣？",
    calculatorRoute: "/quick-6",
    calculatorName: "槓桿抉擇：房產 vs 全球股市",
  },
  {
    slug: "quick6-couple-buy-home-invest-balance",
    title: "伴侶一起買房與投資，先對齊哪三件事？",
    subtitle: "沒對齊之前，數字再漂亮都容易吵架。",
    seoTitle: "夫妻買房與投資怎麼平衡？槓桿抉擇：房產 vs 全球股市實作",
    metaDescription: "給伴侶的房產與投資協作框架，透過第六台先對齊目標、壓力與時間軸。",
    focus: "伴侶買房投資平衡",
    keywordA: "夫妻買房投資怎麼分配",
    keywordB: "伴侶理財對齊",
    keywordC: "家庭財務時間軸",
    closeQuestion: "你們是在討論數字，還是其實在討論安全感？",
    calculatorRoute: "/quick-6",
    calculatorName: "槓桿抉擇：房產 vs 全球股市",
  },
  {
    slug: "quick6-single-income-mortgage-pressure-map",
    title: "單薪背房貸，怎樣才不把自己壓到喘不過氣？",
    subtitle: "先求不爆，再求快。",
    seoTitle: "單薪房貸壓力怎麼抓？槓桿抉擇：房產 vs 全球股市路線建議",
    metaDescription: "針對單薪族，利用第六台建立可承受的房貸與投資平衡，避免高壓中斷。",
    focus: "單薪房貸壓力",
    keywordA: "單薪房貸壓力",
    keywordB: "單薪買房可行嗎",
    keywordC: "房貸和投資平衡",
    closeQuestion: "你現在的設定，是讓你前進，還是把你鎖死？",
    calculatorRoute: "/quick-6",
    calculatorName: "槓桿抉擇：房產 vs 全球股市",
  },
  {
    slug: "quick6-inflation-helps-or-hurts-home-buyer",
    title: "通膨到底是幫買房的人，還是害買房的人？",
    subtitle: "答案取決於你的現金流與持有能力。",
    seoTitle: "通膨對買房有利嗎？槓桿抉擇：房產 vs 全球股市雙路徑比較",
    metaDescription: "解析通膨下房產與全球股市路線的差異，幫你避開『只看單一論點』的誤判。",
    focus: "通膨與買房關係",
    keywordA: "通膨對買房有利嗎",
    keywordB: "通膨下投資配置",
    keywordC: "房產抗通膨比較",
    closeQuestion: "你在抗通膨，還是在放大現金流壓力？",
    calculatorRoute: "/quick-6",
    calculatorName: "槓桿抉擇：房產 vs 全球股市",
  },
  {
    slug: "quick6-global-etf-vs-local-property-bias",
    title: "本地房產情感很強，全球股市常被低估",
    subtitle: "偏好不是錯，但要知道代價。",
    seoTitle: "本地房產vs全球ETF怎麼選？槓桿抉擇：房產 vs 全球股市分析",
    metaDescription: "比較本地房產與全球股市常見偏誤，透過第六台用同一條時間軸校正選擇。",
    focus: "本地房產偏誤",
    keywordA: "房產和全球ETF怎麼選",
    keywordB: "本地偏誤投資",
    keywordC: "全球股市配置",
    closeQuestion: "你的選擇是基於數據，還是基於熟悉感？",
    calculatorRoute: "/quick-6",
    calculatorName: "槓桿抉擇：房產 vs 全球股市",
  },
  {
    slug: "quick6-bear-market-while-paying-mortgage",
    title: "邊繳房貸邊遇股市回檔，路線要怎麼守住？",
    subtitle: "壓力雙擊時，最怕亂改策略。",
    seoTitle: "房貸期間遇股市下跌怎麼辦？槓桿抉擇：房產 vs 全球股市應對法",
    metaDescription: "模擬房貸期遇到股市逆風的情境，建立不恐慌、不斷線的應對框架。",
    focus: "房貸期遇股災",
    keywordA: "房貸期間股市下跌怎麼辦",
    keywordB: "雙重壓力理財",
    keywordC: "逆風理財策略",
    closeQuestion: "逆風來時，你有預先想好哪個旋鈕先調嗎？",
    calculatorRoute: "/quick-6",
    calculatorName: "槓桿抉擇：房產 vs 全球股市",
  },
  {
    slug: "quick6-bonus-use-prepay-or-invest",
    title: "年終獎金先還房貸，還是投入全球股市？",
    subtitle: "沒有標準答案，只有適合你的當下版本。",
    seoTitle: "獎金先還房貸還是投資ETF？槓桿抉擇：房產 vs 全球股市試算",
    metaDescription: "利用第六台比較獎金拿去提前還款或投入市場的效果，協助做出更貼近生活的決策。",
    focus: "獎金用法抉擇",
    keywordA: "獎金先還房貸還是投資",
    keywordB: "提前還款還是ETF",
    keywordC: "獎金理財分配",
    closeQuestion: "這筆獎金，你想買的是安心，還是時間？",
    calculatorRoute: "/quick-6",
    calculatorName: "槓桿抉擇：房產 vs 全球股市",
  },
  {
    slug: "quick6-career-risk-and-mortgage-commitment",
    title: "工作不確定時，房貸承諾要怎麼看才不踩雷？",
    subtitle: "收入波動時，固定承諾更要保守。",
    seoTitle: "工作不穩還能背房貸嗎？槓桿抉擇：房產 vs 全球股市風險框架",
    metaDescription: "針對職涯不確定族群，提供房貸承諾與投資彈性的平衡思路，避免高壓誤判。",
    focus: "職涯風險與房貸",
    keywordA: "工作不穩可以買房嗎",
    keywordB: "房貸承諾風險",
    keywordC: "收入波動理財",
    closeQuestion: "你的承諾大小，有跟你的風險承受度對齊嗎？",
    calculatorRoute: "/quick-6",
    calculatorName: "槓桿抉擇：房產 vs 全球股市",
  },
  {
    slug: "quick6-rebalance-after-buying-property",
    title: "買房後投資組合要不要重配？很多人都太晚做",
    subtitle: "房子進來後，整體風險結構已經變了。",
    seoTitle: "買房後資產配置怎麼調？槓桿抉擇：房產 vs 全球股市重配指南",
    metaDescription: "說明買房後如何重整房產與金融資產比例，透過第六台避免風險過度集中。",
    focus: "買房後資產重配",
    keywordA: "買房後資產配置",
    keywordB: "房產佔比太高怎麼辦",
    keywordC: "投資組合重平衡",
    closeQuestion: "你有把『買房後的新風險』納入配置嗎？",
    calculatorRoute: "/quick-6",
    calculatorName: "槓桿抉擇：房產 vs 全球股市",
  },
  {
    slug: "quick6-retire-with-mortgage-plan",
    title: "退休前房貸還沒清，真的一定不行嗎？",
    subtitle: "重點不是清不清，而是現金流是否可承受。",
    seoTitle: "退休前房貸未清怎麼規劃？槓桿抉擇：房產 vs 全球股市思路",
    metaDescription: "針對退休前仍有房貸情境，透過第六台評估現金流可承受度與資產配置調整方向。",
    focus: "退休前未清房貸",
    keywordA: "退休前房貸沒清怎麼辦",
    keywordB: "退休房貸規劃",
    keywordC: "退休現金流管理",
    closeQuestion: "你追求的是形式上的無貸款，還是真正可持續的退休生活？",
    calculatorRoute: "/quick-6",
    calculatorName: "槓桿抉擇：房產 vs 全球股市",
  },
  {
    slug: "quick6-property-upgrade-vs-portfolio-growth",
    title: "升級房子，還是升級投資組合？先看代價",
    subtitle: "每次升級，都是一次機會成本選擇題。",
    seoTitle: "換大房還是加碼投資？槓桿抉擇：房產 vs 全球股市比較法",
    metaDescription: "比較房屋升級與投資升級兩種路線的長期差，避免只看當下舒適感。",
    focus: "升級房產vs升級投資",
    keywordA: "換房還是加碼投資",
    keywordB: "房屋升級機會成本",
    keywordC: "資產升級選擇",
    closeQuestion: "這次升級是增加生活品質，還是增加長期壓力？",
    calculatorRoute: "/quick-6",
    calculatorName: "槓桿抉擇：房產 vs 全球股市",
  },
  {
    slug: "quick6-why-cashflow-beats-paper-wealth",
    title: "帳面資產很漂亮，卻每天焦慮？問題常在現金流",
    subtitle: "先活得穩，才有資格談長期放大。",
    seoTitle: "為什麼現金流比帳面資產重要？槓桿抉擇：房產 vs 全球股市提醒",
    metaDescription: "透過第六台理解『帳面富有』與『現金流可持續』的差異，降低理財焦慮。",
    focus: "現金流勝過帳面",
    keywordA: "現金流比資產重要",
    keywordB: "帳面富有但焦慮",
    keywordC: "可持續理財",
    closeQuestion: "你現在追的是看起來有錢，還是活起來不焦慮？",
    calculatorRoute: "/quick-6",
    calculatorName: "槓桿抉擇：房產 vs 全球股市",
  },
  {
    slug: "quick6-build-30year-leverage-discipline",
    title: "30 年槓桿紀律，不是衝動，是可持續的選擇能力",
    subtitle: "真正厲害的不是一次選對，而是持續校正。",
    seoTitle: "30年買房投資怎麼平衡？槓桿抉擇：房產 vs 全球股市長期框架",
    metaDescription: "建立 30 年房產與全球股市並行的紀律框架，幫你在不同人生階段持續調整而不失速。",
    focus: "30年槓桿紀律",
    keywordA: "長期買房投資平衡",
    keywordB: "30年資產配置",
    keywordC: "槓桿紀律規劃",
    closeQuestion: "你的策略有沒有留給未來自己『重新調整』的空間？",
    calculatorRoute: "/quick-6",
    calculatorName: "槓桿抉擇：房產 vs 全球股市",
  },
  {
    slug: "quick7-leverage-choice-mortgage-vs-global-stocks",
    title: "💣 槓桿抉擇：房貸 vs 全球股市｜先看壓力，再看報酬",
    subtitle: "你不是在選立場，你是在選現金流版本。",
    seoTitle: "槓桿抉擇：房貸 vs 全球股市教學｜房貸路線與全球股市路線比較",
    metaDescription: "第七台聚焦房貸槓桿與全球股市投入比較，幫你用同一時間軸看清現金流與長期差異。",
    focus: "槓桿抉擇：房貸 vs 全球股市",
    keywordA: "房貸和全球股市怎麼選",
    keywordB: "房貸槓桿與ETF比較",
    keywordC: "現金流壓力試算",
    closeQuestion: "你現在做的選擇，是讓你更自由，還是更綁手綁腳？",
    calculatorRoute: "/quick-7",
    calculatorName: "槓桿抉擇：房貸 vs 全球股市",
    calculatorNote: "把房貸與全球股市放在同一張時間軸。先看壓力，再看長期差距。",
  },
  {
    slug: "quick7-rent-or-buy-global-portfolio-balance",
    title: "租房或買房，怎麼和全球資產配置一起思考？",
    subtitle: "先看資金彈性，再看身份想像。",
    seoTitle: "租房還是買房比較好？槓桿抉擇：房貸 vs 全球股市平衡法",
    metaDescription: "用第七台比較租房與買房搭配全球股市的長期路線，避免只靠情緒決策。",
    focus: "租買與全球配置平衡",
    keywordA: "租房還是買房比較好",
    keywordB: "全球資產配置買房",
    keywordC: "租買投資平衡",
    closeQuestion: "你追的是看起來安穩，還是真正可持續？",
    calculatorRoute: "/quick-7",
    calculatorName: "槓桿抉擇：房貸 vs 全球股市",
  },
  {
    slug: "quick7-mortgage-term-20-vs-30-impact",
    title: "房貸 20 年與 30 年，差的不只利息",
    subtitle: "更大的差別常是你每月能不能喘氣。",
    seoTitle: "房貸20年vs30年怎麼選？槓桿抉擇：房貸 vs 全球股市比較",
    metaDescription: "比較不同房貸年限對月現金流與投資彈性的影響，找出你能長期執行的版本。",
    focus: "房貸年限20對30",
    keywordA: "房貸20年和30年差別",
    keywordB: "房貸年限選擇",
    keywordC: "房貸與投資彈性",
    closeQuestion: "你要的是早點清貸，還是更穩地走完整條路？",
    calculatorRoute: "/quick-7",
    calculatorName: "槓桿抉擇：房貸 vs 全球股市",
  },
  {
    slug: "quick7-down-payment-vs-dca-global-etf",
    title: "頭期款一次下去，還是分批投入全球 ETF？",
    subtitle: "兩條路都可以，但代價不同。",
    seoTitle: "頭期款該買房還是投資ETF？槓桿抉擇：房貸 vs 全球股市",
    metaDescription: "比較頭期款進房產與分批投入全球 ETF 的差異，幫你看懂機會成本。",
    focus: "頭期款對分批投入",
    keywordA: "頭期款該買房還是ETF",
    keywordB: "頭期款機會成本",
    keywordC: "分批投入全球ETF",
    closeQuestion: "你比較重視立即擁有，還是長期彈性？",
    calculatorRoute: "/quick-7",
    calculatorName: "槓桿抉擇：房貸 vs 全球股市",
  },
  {
    slug: "quick7-rate-hike-risk-check",
    title: "利率上升來了，你的房貸策略有備案嗎？",
    subtitle: "先想逆風，不是悲觀，是專業。",
    seoTitle: "利率上升房貸怎麼辦？槓桿抉擇：房貸 vs 全球股市風險檢查",
    metaDescription: "透過第七台檢查利率上升情境下的現金流承受度，避免策略失速。",
    focus: "升息風險檢查",
    keywordA: "利率上升房貸怎麼辦",
    keywordB: "升息風險試算",
    keywordC: "房貸壓力管理",
    closeQuestion: "你的計畫是只在順風有效嗎？",
    calculatorRoute: "/quick-7",
    calculatorName: "槓桿抉擇：房貸 vs 全球股市",
  },
  {
    slug: "quick7-single-income-mortgage-survival-map",
    title: "單薪背房貸，怎樣才不會每月都在硬撐？",
    subtitle: "先活得下去，才有機會走更遠。",
    seoTitle: "單薪房貸壓力怎麼解？槓桿抉擇：房貸 vs 全球股市生存地圖",
    metaDescription: "給單薪族的房貸與投資平衡框架，避免高壓導致計畫中斷。",
    focus: "單薪房貸生存地圖",
    keywordA: "單薪房貸壓力怎麼辦",
    keywordB: "單薪買房規劃",
    keywordC: "房貸與投資平衡",
    closeQuestion: "你的方案能撐過壓力期嗎？",
    calculatorRoute: "/quick-7",
    calculatorName: "槓桿抉擇：房貸 vs 全球股市",
  },
  {
    slug: "quick7-double-income-home-invest-strategy",
    title: "雙薪家庭買房＋投資，先對齊哪三個數字？",
    subtitle: "先對齊，後面才不會一直拉扯。",
    seoTitle: "雙薪家庭怎麼買房又投資？槓桿抉擇：房貸 vs 全球股市策略",
    metaDescription: "第七台提供雙薪家庭的對齊思路，整合房貸與全球股市投入節奏。",
    focus: "雙薪房貸投資策略",
    keywordA: "雙薪家庭買房投資",
    keywordB: "夫妻房貸投資規劃",
    keywordC: "家庭理財對齊",
    closeQuestion: "你們是在算數字，還是在對齊生活方向？",
    calculatorRoute: "/quick-7",
    calculatorName: "槓桿抉擇：房貸 vs 全球股市",
  },
  {
    slug: "quick7-bonus-prepay-or-invest-global",
    title: "有獎金時，先提前還房貸還是加碼全球股市？",
    subtitle: "別急著選邊，先看你想買什麼。",
    seoTitle: "獎金先還房貸還是投資ETF？槓桿抉擇：房貸 vs 全球股市教學",
    metaDescription: "比較獎金提前還款與加碼投資兩種路線，幫你做更有依據的配置。",
    focus: "獎金配置抉擇",
    keywordA: "獎金先還房貸還是投資",
    keywordB: "提前還款還是ETF",
    keywordC: "獎金理財分配",
    closeQuestion: "這筆獎金，你想買的是安心，還是時間？",
    calculatorRoute: "/quick-7",
    calculatorName: "槓桿抉擇：房貸 vs 全球股市",
  },
  {
    slug: "quick7-liquidity-buffer-before-leverage",
    title: "上槓桿前先留現金緩衝，真的很重要",
    subtitle: "你不是怕風險，你是怕沒彈性。",
    seoTitle: "房貸前需要多少緩衝金？槓桿抉擇：房貸 vs 全球股市提醒",
    metaDescription: "說明房貸前建立流動性緩衝的必要性，降低計畫中斷機率。",
    focus: "槓桿前流動性緩衝",
    keywordA: "房貸前要留多少現金",
    keywordB: "緩衝金規劃",
    keywordC: "房貸風險控管",
    closeQuestion: "你的計畫有預留呼吸空間嗎？",
    calculatorRoute: "/quick-7",
    calculatorName: "槓桿抉擇：房貸 vs 全球股市",
  },
  {
    slug: "quick7-home-ownership-hidden-costs",
    title: "買房後最容易忽略的隱形成本清單",
    subtitle: "買得起，不代表持有得起。",
    seoTitle: "買房隱形成本有哪些？槓桿抉擇：房貸 vs 全球股市完整檢查",
    metaDescription: "整理房屋持有常見隱形成本，協助你建立更貼近真實的房貸路線。",
    focus: "房屋隱形成本",
    keywordA: "買房隱形成本",
    keywordB: "房屋持有成本",
    keywordC: "房貸總成本",
    closeQuestion: "你現在算的，是買房成本，還是持有成本？",
    calculatorRoute: "/quick-7",
    calculatorName: "槓桿抉擇：房貸 vs 全球股市",
  },
  {
    slug: "quick7-property-concentration-risk",
    title: "資產太集中在房產，風險真的有那麼大嗎？",
    subtitle: "集中不一定錯，但要知道你承擔什麼。",
    seoTitle: "房產集中風險怎麼看？槓桿抉擇：房貸 vs 全球股市配置提醒",
    metaDescription: "用第七台對照房產集中與全球分散配置，幫你看懂流動性與波動差異。",
    focus: "房產集中風險",
    keywordA: "房產集中風險",
    keywordB: "資產分散配置",
    keywordC: "房產ETF平衡",
    closeQuestion: "你的資產結構，禁得起單一風險嗎？",
    calculatorRoute: "/quick-7",
    calculatorName: "槓桿抉擇：房貸 vs 全球股市",
  },
  {
    slug: "quick7-bear-market-while-paying-mortgage",
    title: "繳房貸同時遇股市下跌，該怎麼守住策略？",
    subtitle: "先有逆風計畫，才不會亂砍亂停。",
    seoTitle: "房貸期遇股市下跌怎麼辦？槓桿抉擇：房貸 vs 全球股市應對",
    metaDescription: "模擬雙壓力情境下的決策框架，降低恐慌式錯誤調整。",
    focus: "房貸期遇股災",
    keywordA: "房貸期間股市下跌",
    keywordB: "雙重壓力理財",
    keywordC: "逆風應對策略",
    closeQuestion: "逆風來時，你知道先調哪個旋鈕嗎？",
    calculatorRoute: "/quick-7",
    calculatorName: "槓桿抉擇：房貸 vs 全球股市",
  },
  {
    slug: "quick7-career-uncertainty-and-mortgage",
    title: "職涯不確定時，房貸承諾怎麼抓才不失控？",
    subtitle: "承諾不是越大越好，是越穩越好。",
    seoTitle: "工作不穩還能背房貸嗎？槓桿抉擇：房貸 vs 全球股市風險管理",
    metaDescription: "針對收入不確定族群，提供房貸與投資並行時的風險管理邏輯。",
    focus: "職涯不確定與房貸",
    keywordA: "工作不穩能買房嗎",
    keywordB: "房貸承諾風險",
    keywordC: "收入波動理財",
    closeQuestion: "你的承諾大小，跟風險承受度一致嗎？",
    calculatorRoute: "/quick-7",
    calculatorName: "槓桿抉擇：房貸 vs 全球股市",
  },
  {
    slug: "quick7-inflation-and-mortgage-choice",
    title: "通膨時代下，房貸決策會更有利嗎？",
    subtitle: "不是通膨本身，關鍵在你的現金流體質。",
    seoTitle: "通膨下房貸比較有利？槓桿抉擇：房貸 vs 全球股市分析",
    metaDescription: "比較通膨情境下房貸與全球股市路線差異，避免單一論點誤導。",
    focus: "通膨與房貸抉擇",
    keywordA: "通膨下房貸有利嗎",
    keywordB: "通膨理財策略",
    keywordC: "房貸全球股市比較",
    closeQuestion: "你在對抗通膨，還是在放大壓力？",
    calculatorRoute: "/quick-7",
    calculatorName: "槓桿抉擇：房貸 vs 全球股市",
  },
  {
    slug: "quick7-global-diversification-vs-local-home-bias",
    title: "本地房產偏好很正常，但別忽略全球分散",
    subtitle: "熟悉感不等於風險更低。",
    seoTitle: "本地房產偏好怎麼平衡全球分散？槓桿抉擇：房貸 vs 全球股市",
    metaDescription: "用第七台對照本地房產與全球分散投資，提升配置決策品質。",
    focus: "本地偏好與全球分散",
    keywordA: "本地房產偏好",
    keywordB: "全球分散投資",
    keywordC: "房產與ETF配置",
    closeQuestion: "你的偏好，來自數據還是習慣？",
    calculatorRoute: "/quick-7",
    calculatorName: "槓桿抉擇：房貸 vs 全球股市",
  },
  {
    slug: "quick7-retire-with-mortgage-plan",
    title: "退休前房貸未清，真的一定不行嗎？",
    subtitle: "關鍵不在形式，而在現金流可承受度。",
    seoTitle: "退休前房貸未清怎麼規劃？槓桿抉擇：房貸 vs 全球股市路線",
    metaDescription: "說明退休前未清房貸情境下如何重整現金流與投資節奏，降低焦慮。",
    focus: "退休前未清房貸",
    keywordA: "退休前房貸沒清",
    keywordB: "退休房貸規劃",
    keywordC: "退休現金流管理",
    closeQuestion: "你想追求形式上的無貸，還是實質上的可持續？",
    calculatorRoute: "/quick-7",
    calculatorName: "槓桿抉擇：房貸 vs 全球股市",
  },
  {
    slug: "quick7-asset-rebalance-after-home-buy",
    title: "買房後要不要重配資產？很多人都忽略了",
    subtitle: "房產進來後，風險結構其實已經改變。",
    seoTitle: "買房後資產配置怎麼調？槓桿抉擇：房貸 vs 全球股市重配建議",
    metaDescription: "提供買房後資產重平衡方向，避免過度集中與流動性不足。",
    focus: "買房後資產重配",
    keywordA: "買房後資產配置",
    keywordB: "資產重平衡",
    keywordC: "房產集中風險",
    closeQuestion: "你有把『買房後的新風險』算進去嗎？",
    calculatorRoute: "/quick-7",
    calculatorName: "槓桿抉擇：房貸 vs 全球股市",
  },
  {
    slug: "quick7-upgrade-home-vs-upgrade-portfolio",
    title: "升級房子還是升級投資組合，哪個先？",
    subtitle: "每次升級，都有一個看不見的代價。",
    seoTitle: "換大房還是加碼投資？槓桿抉擇：房貸 vs 全球股市比較",
    metaDescription: "比較房屋升級與投資升級兩種路線，幫你釐清生活與資產優先序。",
    focus: "升級房屋vs投資組合",
    keywordA: "換房還是加碼投資",
    keywordB: "房屋升級機會成本",
    keywordC: "資產升級策略",
    closeQuestion: "這次升級，是買到品質，還是買到壓力？",
    calculatorRoute: "/quick-7",
    calculatorName: "槓桿抉擇：房貸 vs 全球股市",
  },
  {
    slug: "quick7-cashflow-first-paper-wealth-second",
    title: "帳面資產再漂亮，也比不上穩定現金流",
    subtitle: "先活得穩，才有長期放大的可能。",
    seoTitle: "為何現金流比帳面富有更重要？槓桿抉擇：房貸 vs 全球股市",
    metaDescription: "從第七台角度拆解帳面與現金流落差，降低理財焦慮與錯誤決策。",
    focus: "現金流優先",
    keywordA: "現金流比資產重要",
    keywordB: "帳面富有焦慮",
    keywordC: "可持續理財策略",
    closeQuestion: "你現在追求的是看起來有錢，還是活得有底氣？",
    calculatorRoute: "/quick-7",
    calculatorName: "槓桿抉擇：房貸 vs 全球股市",
  },
  {
    slug: "quick7-build-30year-leverage-discipline",
    title: "30 年槓桿紀律，不靠賭運氣，靠持續校正",
    subtitle: "不是一次選對，而是每年都能調整。",
    seoTitle: "30年房貸與全球股市怎麼平衡？槓桿抉擇：房貸 vs 全球股市框架",
    metaDescription: "建立 30 年可持續的房貸與全球股市並行策略，讓你在不同階段都能穩定前進。",
    focus: "30年槓桿紀律",
    keywordA: "30年房貸投資平衡",
    keywordB: "長期槓桿紀律",
    keywordC: "房貸全球股市策略",
    closeQuestion: "你的策略，留了多少空間給未來的自己調整？",
    calculatorRoute: "/quick-7",
    calculatorName: "槓桿抉擇：房貸 vs 全球股市",
  },
  {
    slug: "quick8-delay-gratification-simulator-guide",
    title: "💣 延遲享樂模擬器：晚一點花，真的會差很多嗎？",
    subtitle: "你不是在犧牲快樂，而是在買更大的選擇權。",
    seoTitle: "延遲享樂模擬器教學：分期支出 vs 可投資金額長期差距",
    metaDescription:
      "使用第八台延遲享樂模擬器，觀察分期支出與可投資金額變化如何影響長期資產，讓消費決策更有依據。",
    focus: "延遲享樂模擬器",
    keywordA: "延遲享樂有用嗎",
    keywordB: "分期對投資影響",
    keywordC: "可投資金額試算",
    closeQuestion: "你願意把哪一筆當下想要，換成未來更穩的底氣？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
    calculatorNote: "先調整分期支出，再看可投資金額與曲線差距。你會很快看懂代價。",
  },
  {
    slug: "quick8-installment-vs-invest-3000-gap",
    title: "每月分期 3000，看起來不多，長期真的沒差嗎？",
    subtitle: "小額固定支出，常是速度被吃掉的地方。",
    seoTitle: "每月分期3000會影響投資嗎？延遲享樂模擬器長期差距比較",
    metaDescription: "透過第八台比較每月分期 3000 與轉為投資的長期差異，幫你看懂細節代價。",
    focus: "分期3000差距",
    keywordA: "每月分期3000影響",
    keywordB: "小額分期機會成本",
    keywordC: "延遲享樂試算",
    closeQuestion: "你願意先省小額固定支出，換長期更大的自由嗎？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
  },
  {
    slug: "quick8-installment-vs-invest-5000-gap",
    title: "每月分期 5000，和每月多投 5000，十年後會差多少？",
    subtitle: "差距不是感覺，是可以被量化的。",
    seoTitle: "每月分期5000值得嗎？延遲享樂模擬器對照投資路線",
    metaDescription: "比較每月分期與每月投資 5000 兩條路線，協助你做更有數字基礎的消費選擇。",
    focus: "分期5000對照",
    keywordA: "每月分期5000值得嗎",
    keywordB: "分期與投資比較",
    keywordC: "機會成本試算",
    closeQuestion: "你現在刷下去的每個月 5000，真的是你最想要的版本嗎？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
  },
  {
    slug: "quick8-new-phone-now-or-later",
    title: "手機現在換，還是晚一年換？先看資產曲線再決定",
    subtitle: "晚一點，不一定是委屈，可能是升級策略。",
    seoTitle: "手機現在買還是延後買？延遲享樂模擬器看長期差異",
    metaDescription: "用第八台評估延後換機對可投資金額與長期資產的影響，降低衝動決策。",
    focus: "手機延後購買",
    keywordA: "手機現在買還是延後",
    keywordB: "延後消費有用嗎",
    keywordC: "換機機會成本",
    closeQuestion: "你想買的是即時爽感，還是未來的選擇權？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
  },
  {
    slug: "quick8-subscription-creep-vs-freedom-speed",
    title: "訂閱越來越多，為什麼自由速度越來越慢？",
    subtitle: "不是單筆貴，是總和長期很重。",
    seoTitle: "訂閱服務太多怎麼辦？延遲享樂模擬器檢查自由速度",
    metaDescription: "分析訂閱支出累積如何拖慢資產成長，透過第八台重設每月分配。",
    focus: "訂閱膨脹檢查",
    keywordA: "訂閱費太多怎麼辦",
    keywordB: "固定支出整理",
    keywordC: "延遲享樂策略",
    closeQuestion: "你每月訂閱的是生活必要，還是習慣性自動扣款？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
  },
  {
    slug: "quick8-weekend-shopping-habit-audit",
    title: "週末慣性購物，會怎麼吃掉你的可投資金額？",
    subtitle: "小習慣疊加，長期非常有感。",
    seoTitle: "週末購物習慣怎麼調整？延遲享樂模擬器實用檢查法",
    metaDescription: "把週末消費轉成可量化差距，協助你建立更穩定的月投入節奏。",
    focus: "週末購物習慣",
    keywordA: "週末購物習慣",
    keywordB: "衝動消費調整",
    keywordC: "可投資金額提升",
    closeQuestion: "下次週末，你願意先等 24 小時再決定嗎？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
  },
  {
    slug: "quick8-couple-spending-alignment-framework",
    title: "伴侶消費觀不同，怎麼一起做延遲享樂規劃？",
    subtitle: "先有同一張圖，再談誰對誰錯。",
    seoTitle: "伴侶理財怎麼對齊？延遲享樂模擬器協作框架",
    metaDescription: "用第八台把雙方消費與投資選擇放到同一條時間軸，降低情緒衝突。",
    focus: "伴侶延遲享樂對齊",
    keywordA: "伴侶理財對齊",
    keywordB: "夫妻消費觀不同",
    keywordC: "共同投資規劃",
    closeQuestion: "你們現在在爭對錯，還是在對齊未來版本？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
  },
  {
    slug: "quick8-year-end-sale-trap-analysis",
    title: "年底促銷真的有省到，還是只是把未來拿來先花？",
    subtitle: "便宜不等於划算，得看機會成本。",
    seoTitle: "雙11雙12值得買嗎？延遲享樂模擬器看促銷消費代價",
    metaDescription: "拆解促銷購物與延後購買的長期差異，避免『看起來有省』的錯覺。",
    focus: "年底促銷陷阱",
    keywordA: "雙11值得買嗎",
    keywordB: "促銷購物陷阱",
    keywordC: "延後購買策略",
    closeQuestion: "你買的是折扣，還是被折扣買走了選擇權？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
  },
  {
    slug: "quick8-bonus-spend-or-invest-split",
    title: "年終獎金要爽花還是加碼投資？先拆比例",
    subtitle: "不是全花或全存，重點是分配規則。",
    seoTitle: "年終獎金怎麼分配？延遲享樂模擬器比較花費與投資比例",
    metaDescription: "透過第八台比較不同獎金分配策略，找到兼顧當下與長期的平衡點。",
    focus: "獎金分配規則",
    keywordA: "年終獎金怎麼分配",
    keywordB: "獎金花費與投資比例",
    keywordC: "延遲享樂理財",
    closeQuestion: "這筆獎金，你想買短期快樂，還是長期底氣？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
  },
  {
    slug: "quick8-travel-budget-vs-longterm-assets",
    title: "旅行預算怎麼抓，才不會回來只剩焦慮？",
    subtitle: "享受生活和長期規劃可以並存。",
    seoTitle: "旅行和理財如何平衡？延遲享樂模擬器看預算安排",
    metaDescription: "比較旅行花費與可投資金額調整，協助建立不內耗的生活與理財節奏。",
    focus: "旅行預算平衡",
    keywordA: "旅行和理財平衡",
    keywordB: "旅行預算怎麼抓",
    keywordC: "延遲享樂生活版",
    closeQuestion: "你願意用規劃換自在，還是用衝動換後悔？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
  },
  {
    slug: "quick8-lifestyle-upgrade-timing-choice",
    title: "生活升級要不要晚一年？時間常是最便宜的槓桿",
    subtitle: "晚一點，不代表退步，可能是更強版本。",
    seoTitle: "生活升級何時做最好？延遲享樂模擬器時間選擇題",
    metaDescription: "透過第八台比較立即升級與延後升級對長期資產的影響，提升決策品質。",
    focus: "生活升級時機",
    keywordA: "生活升級要不要延後",
    keywordB: "延後消費時機",
    keywordC: "升級機會成本",
    closeQuestion: "這次升級，是必要，還是只是想立刻有感？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
  },
  {
    slug: "quick8-emotion-buying-cooldown-system",
    title: "情緒購物很難戒？先用冷卻機制，而不是意志力",
    subtitle: "流程比狠勁更可靠。",
    seoTitle: "如何避免衝動購物？延遲享樂模擬器冷卻流程教學",
    metaDescription: "建立可執行的消費冷卻流程，降低衝動花費對長期投資的侵蝕。",
    focus: "情緒購物冷卻",
    keywordA: "如何避免衝動購物",
    keywordB: "情緒消費管理",
    keywordC: "冷卻機制理財",
    closeQuestion: "下次想刷卡時，你願意先等 48 小時嗎？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
  },
  {
    slug: "quick8-credit-card-installment-hidden-cost",
    title: "信用卡分期看似無痛，為什麼會讓你越算越慢？",
    subtitle: "真正痛點常在你看不到的長期代價。",
    seoTitle: "信用卡分期真的划算嗎？延遲享樂模擬器拆解隱形成本",
    metaDescription: "拆解信用卡分期對可投資金額的長期影響，幫你看清分期代價。",
    focus: "信用卡分期代價",
    keywordA: "信用卡分期划算嗎",
    keywordB: "分期隱形成本",
    keywordC: "分期與投資差異",
    closeQuestion: "你選的分期，真的在幫你，還是在鎖住你？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
  },
  {
    slug: "quick8-low-buy-impulse-high-invest-routine",
    title: "降低購買衝動，怎麼變成可複製的日常習慣？",
    subtitle: "習慣一旦成型，焦慮會明顯下降。",
    seoTitle: "如何減少購買衝動並增加投資？延遲享樂模擬器習慣版",
    metaDescription: "用第八台搭配習慣流程，把消費衝動轉成可持續的長期投入。",
    focus: "低衝動高投入習慣",
    keywordA: "減少購買衝動方法",
    keywordB: "增加投資習慣",
    keywordC: "延遲享樂日常",
    closeQuestion: "你今天能做哪個小動作，讓明天更不容易亂買？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
  },
  {
    slug: "quick8-pay-yourself-first-delay-gratification",
    title: "先付錢給未來的自己，再決定要不要買",
    subtitle: "順序一改，整個結果會變。",
    seoTitle: "先支付自己法怎麼用？延遲享樂模擬器實作分配順序",
    metaDescription: "示範『先投資後消費』流程，幫你把延遲享樂變成可執行系統。",
    focus: "先支付自己法",
    keywordA: "先支付自己法",
    keywordB: "先投資後消費",
    keywordC: "理財分配順序",
    closeQuestion: "你每月的第一筆錢，是給未來，還是給衝動？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
  },
  {
    slug: "quick8-family-budget-priority-map",
    title: "家庭預算怎麼排序，才不會每個月都在拉扯？",
    subtitle: "先排序，再分配，焦慮會少很多。",
    seoTitle: "家庭預算優先順序怎麼排？延遲享樂模擬器情境規劃",
    metaDescription: "用第八台建立家庭預算優先順序，平衡當下開銷與長期目標。",
    focus: "家庭預算排序",
    keywordA: "家庭預算怎麼安排",
    keywordB: "家庭理財優先順序",
    keywordC: "支出分配規劃",
    closeQuestion: "你們家的預算，是有策略，還是每月臨場反應？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
  },
  {
    slug: "quick8-side-income-do-not-inflate-lifestyle",
    title: "副業收入進來後，最怕不是少，而是立刻膨脹生活",
    subtitle: "額外收入是加速器，不是借口。",
    seoTitle: "副業收入怎麼用不亂花？延遲享樂模擬器生活膨脹檢查",
    metaDescription: "透過第八台比較副業收入拿去消費或投資的長期差，避免收入升級但自由沒升級。",
    focus: "副業收入不膨脹",
    keywordA: "副業收入怎麼分配",
    keywordB: "避免生活膨脹",
    keywordC: "額外收入理財",
    closeQuestion: "你的副業收入，是放大目標，還是放大開銷？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
  },
  {
    slug: "quick8-minimalism-vs-consumption-balance",
    title: "極簡生活和享受消費，可以找到平衡點嗎？",
    subtitle: "重點不是極端，而是可持續。",
    seoTitle: "極簡與消費怎麼平衡？延遲享樂模擬器生活策略比較",
    metaDescription: "比較不同消費風格對可投資金額與長期資產的影響，找出你的平衡版本。",
    focus: "極簡與消費平衡",
    keywordA: "極簡生活和消費平衡",
    keywordB: "消費風格理財",
    keywordC: "延遲享樂生活方式",
    closeQuestion: "你的消費選擇，讓你更自由，還是更依賴下一次購物？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
  },
  {
    slug: "quick8-annual-reset-delay-gratification-plan",
    title: "每年一次重設延遲享樂計畫，為什麼很有用？",
    subtitle: "不重設，策略會默默過期。",
    seoTitle: "延遲享樂計畫多久重設一次？第八台年度校正流程",
    metaDescription: "建立年度重設流程，透過第八台持續校正消費與投資分配，維持長期節奏。",
    focus: "年度重設延遲享樂",
    keywordA: "延遲享樂計畫重設",
    keywordB: "年度理財校正",
    keywordC: "消費投資重配",
    closeQuestion: "你現在的消費規則，還適合今年的你嗎？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
  },
  {
    slug: "quick8-build-30year-delay-gratification-habit",
    title: "30 年後的自由，來自每次延後 24 小時的選擇",
    subtitle: "大結果，常由很小的習慣累積。",
    seoTitle: "如何養成長期延遲享樂習慣？第八台打造30年自由節奏",
    metaDescription: "用第八台建立長期延遲享樂與持續投入習慣，讓短期衝動不再吃掉未來。",
    focus: "30年延遲享樂習慣",
    keywordA: "延遲享樂習慣養成",
    keywordB: "長期理財習慣",
    keywordC: "30年自由節奏",
    closeQuestion: "你今天願不願意多等一下，換未來多很多選擇？",
    calculatorRoute: "/quick-8",
    calculatorName: "延遲享樂模擬器",
  },
  {
    slug: "quick9-delay-spending-value-calculator-guide",
    title: "💣 延遲消費價值計算機：晚買不是忍耐，是重新定價",
    subtitle: "同一筆錢，時間不同，價值真的不同。",
    seoTitle: "延遲消費價值計算機：3年5年10年切換看差距",
    metaDescription:
      "透過第九台延遲消費價值計算機，以 3/5/10 年幅度比較延後消費的資產差，幫你做更聰明的消費節奏。",
    focus: "延遲消費價值計算機",
    keywordA: "延遲消費價值怎麼算",
    keywordB: "晚買真的划算嗎",
    keywordC: "消費延後試算",
    closeQuestion: "你現在的每一次刷卡，真的符合你想要的長期生活版本嗎？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
    calculatorNote: "切換 3/5/10 年視角看差距，別只看當下價格，先看長期機會成本。",
  },
  {
    slug: "quick9-3year-5year-10year-compare",
    title: "3 年、5 年、10 年切換後，消費差距會長怎樣？",
    subtitle: "時間一拉長，很多決策會重寫答案。",
    seoTitle: "3年5年10年差多少？延遲消費價值計算機幅度比較教學",
    metaDescription: "透過第九台切換 3/5/10 年視角，比較延後消費與即時消費的長期價值差。",
    focus: "3/5/10年幅度比較",
    keywordA: "3年5年10年投資差距",
    keywordB: "延後消費年限比較",
    keywordC: "消費機會成本年期",
    closeQuestion: "你平常做決定時，看的是 3 個月，還是 3 年？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
  },
  {
    slug: "quick9-buy-now-vs-buy-later-laptop-case",
    title: "筆電現在買還是晚一年買？這題其實能被量化",
    subtitle: "你不需要猜，直接比兩條路線。",
    seoTitle: "筆電現在買還是延後買？延遲消費價值計算機案例",
    metaDescription: "以筆電購買情境示範延後消費價值，幫你把直覺轉成可比對數字。",
    focus: "筆電購買時機",
    keywordA: "筆電現在買還是延後",
    keywordB: "延後購買價值",
    keywordC: "消費時機試算",
    closeQuestion: "這筆花費是急需，還是其實可以等更好的版本？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
  },
  {
    slug: "quick9-installment-or-cash-global-invest-impact",
    title: "分期買和現金買，對你的可投資金額差在哪？",
    subtitle: "付款方式改變，長期路線也會改變。",
    seoTitle: "分期或現金哪個划算？延遲消費價值計算機比較投資影響",
    metaDescription: "比較分期與現金購買對可投資金額和長期資產的影響，幫助你選擇付款策略。",
    focus: "分期vs現金影響",
    keywordA: "分期和現金哪個划算",
    keywordB: "付款方式影響投資",
    keywordC: "分期機會成本",
    closeQuestion: "你選付款方式時，有把未來資產差也算進去嗎？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
  },
  {
    slug: "quick9-impulse-purchase-cooldown-72h",
    title: "衝動購物先等 72 小時，真的有差嗎？",
    subtitle: "冷卻機制看似簡單，效果常比想像大。",
    seoTitle: "72小時冷卻法有用嗎？延遲消費價值計算機實測",
    metaDescription: "用第九台搭配 72 小時冷卻機制，降低衝動花費對長期資產的侵蝕。",
    focus: "72小時冷卻機制",
    keywordA: "72小時冷卻法",
    keywordB: "如何減少衝動購物",
    keywordC: "延遲消費習慣",
    closeQuestion: "下次想買時，你願意先讓自己冷靜三天嗎？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
  },
  {
    slug: "quick9-monthly-wants-budget-cap-system",
    title: "想要型支出要不要設上限？先看你要換哪個未來",
    subtitle: "設上限不是壓抑，是保留選擇權。",
    seoTitle: "想要型支出要設多少？延遲消費價值計算機上限系統",
    metaDescription: "建立每月想要型預算上限，透過第九台維持生活感與資產成長平衡。",
    focus: "想要支出上限",
    keywordA: "想要型支出上限",
    keywordB: "每月預算上限怎麼設",
    keywordC: "消費控制系統",
    closeQuestion: "你的支出上限，是你定義的，還是情緒定義的？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
  },
  {
    slug: "quick9-credit-card-points-vs-real-cost",
    title: "信用卡回饋很香，但真的有賺到嗎？",
    subtitle: "回饋常被高估，機會成本常被低估。",
    seoTitle: "信用卡回饋真的划算嗎？延遲消費價值計算機看真實成本",
    metaDescription: "拆解信用卡回饋與消費行為落差，透過第九台看清『回饋』與『成本』。",
    focus: "回饋與真實成本",
    keywordA: "信用卡回饋划算嗎",
    keywordB: "信用卡真實成本",
    keywordC: "回饋迷思",
    closeQuestion: "你拿到的是回饋，還是被回饋推著多花？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
  },
  {
    slug: "quick9-year-end-discount-vs-longterm-value",
    title: "年底折扣看起來賺，長期價值真的賺嗎？",
    subtitle: "短期便宜，不一定是長期划算。",
    seoTitle: "年底折扣值不值得？延遲消費價值計算機長期對照",
    metaDescription: "用第九台比較年底折扣購物與延後投入資產的長期差異。",
    focus: "折扣與長期價值",
    keywordA: "年底折扣值得嗎",
    keywordB: "折扣購物機會成本",
    keywordC: "長期價值比較",
    closeQuestion: "你這次追折扣，是在省錢，還是在加速花錢？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
  },
  {
    slug: "quick9-subscription-stack-cleanup-plan",
    title: "訂閱一層疊一層，先清理哪幾個最有感？",
    subtitle: "最有感的不是砍最多，而是砍對。",
    seoTitle: "訂閱服務怎麼精簡？延遲消費價值計算機清理流程",
    metaDescription: "透過第九台找出訂閱堆疊對可投資金額的侵蝕，建立精簡優先順序。",
    focus: "訂閱堆疊清理",
    keywordA: "訂閱服務精簡",
    keywordB: "固定支出清理",
    keywordC: "訂閱管理流程",
    closeQuestion: "哪些訂閱真有用，哪些只是忘記取消？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
  },
  {
    slug: "quick9-iphone-upgrade-cycle-choice",
    title: "手機升級週期拉長一年，差別可能超過你想像",
    subtitle: "不是不能升級，是先選週期。",
    seoTitle: "iPhone幾年換一次最划算？延遲消費價值計算機比較",
    metaDescription: "比較不同手機升級週期對長期資產與現金流的影響，幫你做更穩定決策。",
    focus: "手機升級週期",
    keywordA: "手機幾年換一次",
    keywordB: "iPhone升級週期",
    keywordC: "延後升級價值",
    closeQuestion: "你追的是最新型號，還是最穩節奏？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
  },
  {
    slug: "quick9-car-upgrade-delay-value",
    title: "車子升級晚兩年，真的會慢很多嗎？",
    subtitle: "有時候晚，不是輸，而是更聰明。",
    seoTitle: "車子升級要延後嗎？延遲消費價值計算機評估方法",
    metaDescription: "評估延後車輛升級對可投資金額與資產路線的影響，降低情緒決策。",
    focus: "車輛升級延後",
    keywordA: "車子升級要延後嗎",
    keywordB: "換車時機",
    keywordC: "延後大額消費",
    closeQuestion: "現在換車，對你是必要，還是只是想快點有感？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
  },
  {
    slug: "quick9-home-appliance-replace-or-repair",
    title: "家電壞了該換新還是先修？先算價值再決定",
    subtitle: "不是省不省，而是總成本比較。",
    seoTitle: "家電換新還是維修？延遲消費價值計算機決策框架",
    metaDescription: "用第九台協助比較家電換新與維修的機會成本，做出更理性的家庭決策。",
    focus: "家電換新或維修",
    keywordA: "家電換新還是維修",
    keywordB: "家電決策比較",
    keywordC: "家庭消費決策",
    closeQuestion: "你在買的是效率，還是只是避免當下麻煩？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
  },
  {
    slug: "quick9-side-income-spend-or-invest-rule",
    title: "副業收入拿來花，還是拿來投？先訂規則",
    subtitle: "沒規則，額外收入通常留不住。",
    seoTitle: "副業收入怎麼分配？延遲消費價值計算機建立規則",
    metaDescription: "建立副業收入花費與投資比例規則，讓額外收入真正加速目標。",
    focus: "副業收入分配規則",
    keywordA: "副業收入怎麼分配",
    keywordB: "副業收入投資",
    keywordC: "額外收入規則",
    closeQuestion: "這份額外收入，會成為跳板，還是又變成開銷？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
  },
  {
    slug: "quick9-couple-big-ticket-decision-framework",
    title: "伴侶遇到大額消費，怎麼不吵架做決定？",
    subtitle: "先對齊原則，再看產品。",
    seoTitle: "伴侶大額消費怎麼決策？延遲消費價值計算機框架",
    metaDescription: "提供伴侶大額消費決策框架，透過第九台量化即時買與延後買差異。",
    focus: "伴侶大額決策框架",
    keywordA: "伴侶大額消費決策",
    keywordB: "夫妻理財溝通",
    keywordC: "共同消費規則",
    closeQuestion: "你們吵的是商品，還是其實沒對齊標準？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
  },
  {
    slug: "quick9-family-consumption-priority-order",
    title: "家庭消費優先順序，該怎麼排才不失衡？",
    subtitle: "排序比節省更重要。",
    seoTitle: "家庭消費優先順序怎麼排？延遲消費價值計算機實作",
    metaDescription: "用第九台建立家庭消費優先順序，兼顧生活品質與長期資產累積。",
    focus: "家庭消費優先順序",
    keywordA: "家庭消費優先順序",
    keywordB: "家庭預算分配",
    keywordC: "消費排序策略",
    closeQuestion: "你家的支出，是有策略，還是每月即興？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
  },
  {
    slug: "quick9-buy-experience-or-buy-asset-balance",
    title: "買體驗還是買資產？其實可以同時做到",
    subtitle: "不是二選一，而是比例設計。",
    seoTitle: "買體驗或買資產怎麼平衡？延遲消費價值計算機比例法",
    metaDescription: "比較體驗型支出與資產型投入配置，找到不後悔的生活與理財比例。",
    focus: "體驗與資產平衡",
    keywordA: "買體驗還是買資產",
    keywordB: "生活與理財平衡",
    keywordC: "支出比例設計",
    closeQuestion: "你的花費有在支持你想要的人生版本嗎？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
  },
  {
    slug: "quick9-annual-reset-consumption-value-map",
    title: "每年重設一次消費價值地圖，真的很值得",
    subtitle: "不重設，舊習慣會拖著你走。",
    seoTitle: "消費價值地圖如何年度重設？延遲消費價值計算機流程",
    metaDescription: "建立年度消費價值重設流程，維持消費與投資分配的長期一致性。",
    focus: "年度消費價值重設",
    keywordA: "年度消費重設",
    keywordB: "理財年度回顧",
    keywordC: "消費投資校正",
    closeQuestion: "你今年的花費規則，還是去年的版本嗎？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
  },
  {
    slug: "quick9-low-consumption-high-freedom-routine",
    title: "低消費不是苦行，是把自由放大的一種習慣",
    subtitle: "重點不是少花，而是花得對。",
    seoTitle: "如何打造低消費高自由習慣？延遲消費價值計算機實戰",
    metaDescription: "示範低消費高自由的日常流程，透過第九台把習慣轉成可見結果。",
    focus: "低消費高自由習慣",
    keywordA: "低消費生活",
    keywordB: "高自由理財",
    keywordC: "消費習慣養成",
    closeQuestion: "你願意今天少一點衝動，換明天多一點自由嗎？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
  },
  {
    slug: "quick9-avoid-lifestyle-inflation-checklist",
    title: "收入升了，生活也膨脹了嗎？先做這份檢查",
    subtitle: "很多人輸在看不見的膨脹。",
    seoTitle: "如何避免生活膨脹？延遲消費價值計算機檢查清單",
    metaDescription: "提供生活膨脹檢查清單，協助你把收入成長轉成資產成長。",
    focus: "避免生活膨脹",
    keywordA: "如何避免生活膨脹",
    keywordB: "收入增加卻沒存錢",
    keywordC: "生活膨脹檢查",
    closeQuestion: "你的加薪有放大資產，還是只放大開銷？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
  },
  {
    slug: "quick9-build-30year-delay-spending-discipline",
    title: "30 年後的差距，常從每次晚買一點開始",
    subtitle: "紀律不是硬撐，是可持續選擇。",
    seoTitle: "如何建立30年延遲消費紀律？第九台長期路線圖",
    metaDescription: "用第九台打造 30 年延遲消費紀律，讓短期誘惑不再打斷長期目標。",
    focus: "30年延遲消費紀律",
    keywordA: "延遲消費紀律",
    keywordB: "30年理財習慣",
    keywordC: "長期消費策略",
    closeQuestion: "你今天的選擇，有在照顧 10 年後的你嗎？",
    calculatorRoute: "/quick-9",
    calculatorName: "延遲消費價值計算機",
  },
  {
    slug: "quick10-compound-dream-vs-crash-reality-guide",
    title: "💣 複利美夢 VS 崩盤現實 計算機：順風很美，逆風更該先看",
    subtitle: "真正的安全感，來自你看過最壞版本。",
    seoTitle: "複利美夢 VS 崩盤現實 計算機教學：崩盤情境壓力測試怎麼看",
    metaDescription: "第十台幫你把順風複利與崩盤情境放在同一張圖，提前看到風險與韌性。",
    focus: "複利美夢 vs 崩盤現實",
    keywordA: "崩盤情境壓力測試",
    keywordB: "複利遇到崩盤怎麼看",
    keywordC: "資產防護線試算",
    closeQuestion: "你想追漂亮曲線，還是追撐得住的曲線？",
    calculatorRoute: "/quick-10",
    calculatorName: "複利美夢 VS 崩盤現實 計算機",
    calculatorNote: "先看順風，再看崩盤。能睡得著的版本，才是你的版本。",
  },
  {
    slug: "quick10-if-crash-hits-last-year-what-happens",
    title: "如果崩盤發生在最後一年，結果會怎樣？",
    subtitle: "越接近終點，越怕時序風險。",
    seoTitle: "崩盤發生在最後一年怎麼辦？複利美夢 VS 崩盤現實 計算機案例",
    metaDescription: "模擬崩盤落在不同年份的影響，幫你理解接近退休期的脆弱點。",
    focus: "末期崩盤風險",
    keywordA: "最後一年崩盤怎麼辦",
    keywordB: "時序風險",
    keywordC: "退休前崩盤影響",
    closeQuestion: "你的計畫有保護接近終點那幾年嗎？",
    calculatorRoute: "/quick-10",
    calculatorName: "複利美夢 VS 崩盤現實 計算機",
  },
  {
    slug: "quick10-20percent-drop-stress-case",
    title: "遇到 -20% 回檔，你會不會就亂掉？",
    subtitle: "輕中度回檔，最容易低估。",
    seoTitle: "遇到20%回檔怎麼調整？複利美夢 VS 崩盤現實 計算機壓測",
    metaDescription: "透過 -20% 情境先做心理與資金演練，避免真實回檔時失措。",
    focus: "20%回檔壓測",
    keywordA: "20%回檔怎麼辦",
    keywordB: "回檔壓力測試",
    keywordC: "投資心理準備",
    closeQuestion: "回檔 20% 時，你是有流程，還是靠運氣？",
    calculatorRoute: "/quick-10",
    calculatorName: "複利美夢 VS 崩盤現實 計算機",
  },
  {
    slug: "quick10-30percent-drop-stress-case",
    title: "遇到 -30% 修正，策略還站得住嗎？",
    subtitle: "這個深度常是情緒分水嶺。",
    seoTitle: "30%修正如何應對？複利美夢 VS 崩盤現實 計算機實戰",
    metaDescription: "以 -30% 情境檢查配置與行為風險，找出你能長期執行的版本。",
    focus: "30%修正壓測",
    keywordA: "30%修正應對",
    keywordB: "大跌配置調整",
    keywordC: "崩盤行為風險",
    closeQuestion: "跌到 30% 時，你能照計畫做事嗎？",
    calculatorRoute: "/quick-10",
    calculatorName: "複利美夢 VS 崩盤現實 計算機",
  },
  {
    slug: "quick10-40percent-drop-stress-case",
    title: "假設 -40% 崩盤，哪些設定會先出事？",
    subtitle: "先承認最壞，才能守住最好。",
    seoTitle: "40%崩盤情境怎麼撐？複利美夢 VS 崩盤現實 計算機檢查",
    metaDescription: "用 -40% 極端情境找出脆弱設定，提早補強資金與行為防線。",
    focus: "40%崩盤壓測",
    keywordA: "40%崩盤怎麼撐",
    keywordB: "極端情境試算",
    keywordC: "崩盤防線",
    closeQuestion: "你有看過最壞版本，還是只看順風版本？",
    calculatorRoute: "/quick-10",
    calculatorName: "複利美夢 VS 崩盤現實 計算機",
  },
  {
    slug: "quick10-withdrawal-need-during-crash",
    title: "崩盤時剛好要用錢，才是最痛的情境",
    subtitle: "現金需求會放大市場風險。",
    seoTitle: "崩盤時需要提款怎麼辦？複利美夢 VS 崩盤現實 計算機提醒",
    metaDescription: "檢查崩盤期提款需求對資產路線的衝擊，建立更穩提款前準備。",
    focus: "崩盤期提款風險",
    keywordA: "崩盤時需要用錢",
    keywordB: "提款風險",
    keywordC: "現金流防守",
    closeQuestion: "你的計畫有把臨時提款壓力算進去嗎？",
    calculatorRoute: "/quick-10",
    calculatorName: "複利美夢 VS 崩盤現實 計算機",
  },
  {
    slug: "quick10-emergency-fund-before-risk-assets",
    title: "緊急預備金先到位，崩盤時才不會被迫賣在低點",
    subtitle: "先活下來，才有機會等回升。",
    seoTitle: "為什麼預備金先於投資？複利美夢 VS 崩盤現實 計算機觀點",
    metaDescription: "說明預備金在崩盤情境下的保護作用，降低被迫停損風險。",
    focus: "預備金防護",
    keywordA: "預備金重要性",
    keywordB: "崩盤被迫賣出",
    keywordC: "低點賣出風險",
    closeQuestion: "你的安全墊夠你撐過一段逆風嗎？",
    calculatorRoute: "/quick-10",
    calculatorName: "複利美夢 VS 崩盤現實 計算機",
  },
  {
    slug: "quick10-sequence-risk-for-near-retire",
    title: "接近退休時，報酬時序比平均報酬更可怕",
    subtitle: "同樣平均值，不同順序差很大。",
    seoTitle: "退休前時序風險怎麼看？複利美夢 VS 崩盤現實 計算機解析",
    metaDescription: "解析接近退休期的時序風險，幫你理解為何平均報酬不等於安全。",
    focus: "退休前時序風險",
    keywordA: "退休前時序風險",
    keywordB: "平均報酬迷思",
    keywordC: "接近退休配置",
    closeQuestion: "你的配置有為接近退休期降風險嗎？",
    calculatorRoute: "/quick-10",
    calculatorName: "複利美夢 VS 崩盤現實 計算機",
  },
  {
    slug: "quick10-sell-in-panic-vs-hold-discipline",
    title: "恐慌賣出和紀律持有，長期會差在哪？",
    subtitle: "真正決定結果的，常是行為。",
    seoTitle: "恐慌賣出會怎樣？複利美夢 VS 崩盤現實 計算機行為比較",
    metaDescription: "比較恐慌賣出與紀律持有在崩盤後的差異，降低情緒決策傷害。",
    focus: "恐慌賣出對照",
    keywordA: "恐慌賣出後果",
    keywordB: "崩盤持有策略",
    keywordC: "情緒決策風險",
    closeQuestion: "你會在低點賣掉，還是照流程走完？",
    calculatorRoute: "/quick-10",
    calculatorName: "複利美夢 VS 崩盤現實 計算機",
  },
  {
    slug: "quick10-recovery-years-after-big-drawdown",
    title: "大跌之後要幾年回本？很多人都估太快",
    subtitle: "回本時間是耐心測試。",
    seoTitle: "崩盤後幾年回本？複利美夢 VS 崩盤現實 計算機回復路徑",
    metaDescription: "示範不同跌幅下的回復時間差異，協助建立更務實的心理預期。",
    focus: "回本年數預期",
    keywordA: "崩盤後幾年回本",
    keywordB: "回本時間估算",
    keywordC: "跌幅回復路徑",
    closeQuestion: "你有給自己的策略足夠回復時間嗎？",
    calculatorRoute: "/quick-10",
    calculatorName: "複利美夢 VS 崩盤現實 計算機",
  },
  {
    slug: "quick10-asset-allocation-under-crash",
    title: "崩盤情境下，資產配置比例要怎麼看？",
    subtitle: "配置是為了活下來，不是為了炫耀報酬。",
    seoTitle: "崩盤時資產配置怎麼調？複利美夢 VS 崩盤現實 計算機建議",
    metaDescription: "透過第十台對照不同配置在崩盤時的體感差異，找到可承受區間。",
    focus: "崩盤配置比例",
    keywordA: "崩盤資產配置",
    keywordB: "風險承受度配置",
    keywordC: "防守型配置",
    closeQuestion: "你的配置是在追高報酬，還是追可持續？",
    calculatorRoute: "/quick-10",
    calculatorName: "複利美夢 VS 崩盤現實 計算機",
  },
  {
    slug: "quick10-hedge-cash-bond-equity-balance",
    title: "現金、債券、股票怎麼搭，崩盤時才不慌？",
    subtitle: "平衡不是無聊，是韌性來源。",
    seoTitle: "現金債券股票比例怎麼配？複利美夢 VS 崩盤現實 計算機",
    metaDescription: "提供現金/債券/股票平衡思路，提升崩盤情境下的行為穩定度。",
    focus: "現金債股平衡",
    keywordA: "現金債券股票比例",
    keywordB: "崩盤防守配置",
    keywordC: "資產平衡策略",
    closeQuestion: "你的配置能讓你在逆風夜晚睡得著嗎？",
    calculatorRoute: "/quick-10",
    calculatorName: "複利美夢 VS 崩盤現實 計算機",
  },
  {
    slug: "quick10-income-stability-vs-risk-capacity",
    title: "收入穩不穩，決定你能承受多大波動",
    subtitle: "風險承受度不是口號，是現金流條件。",
    seoTitle: "收入穩定性如何影響投資風險？複利美夢 VS 崩盤現實 計算機",
    metaDescription: "連結收入穩定度與風險承受能力，幫你設定更貼近現實的投資節奏。",
    focus: "收入穩定與風險",
    keywordA: "收入穩定性和投資",
    keywordB: "風險承受能力評估",
    keywordC: "現金流與配置",
    closeQuestion: "你的風險設定，符合你現在的收入結構嗎？",
    calculatorRoute: "/quick-10",
    calculatorName: "複利美夢 VS 崩盤現實 計算機",
  },
  {
    slug: "quick10-job-loss-plus-market-crash-plan",
    title: "如果失業同時遇崩盤，計畫還能不能走？",
    subtitle: "雙重壓力要先演練，不要臨場反應。",
    seoTitle: "失業加崩盤怎麼辦？複利美夢 VS 崩盤現實 計算機雙壓力方案",
    metaDescription: "模擬失業與市場下跌同時發生的情境，建立更實際的備援計畫。",
    focus: "失業加崩盤預案",
    keywordA: "失業又崩盤怎麼辦",
    keywordB: "雙重壓力理財",
    keywordC: "備援理財策略",
    closeQuestion: "你的策略有雙重逆風備案嗎？",
    calculatorRoute: "/quick-10",
    calculatorName: "複利美夢 VS 崩盤現實 計算機",
  },
  {
    slug: "quick10-family-protection-during-drawdown",
    title: "有家庭責任時，崩盤防線該怎麼加強？",
    subtitle: "先保護現金流，再談增長。",
    seoTitle: "家庭責任下如何面對崩盤？複利美夢 VS 崩盤現實 計算機",
    metaDescription: "針對家庭責任情境，說明崩盤期間的資金防線與配置優先順序。",
    focus: "家庭責任防線",
    keywordA: "家庭責任崩盤規劃",
    keywordB: "家庭現金流防線",
    keywordC: "風險管理家庭版",
    closeQuestion: "你的配置能同時照顧家庭與長期目標嗎？",
    calculatorRoute: "/quick-10",
    calculatorName: "複利美夢 VS 崩盤現實 計算機",
  },
  {
    slug: "quick10-annual-crash-rehearsal-checklist",
    title: "每年做一次崩盤演練，為什麼很值得？",
    subtitle: "沒有演練，真實來時容易慌。",
    seoTitle: "崩盤演練清單怎麼做？複利美夢 VS 崩盤現實 計算機年度流程",
    metaDescription: "建立年度崩盤演練清單，確保你的策略在逆風時依然可執行。",
    focus: "年度崩盤演練",
    keywordA: "崩盤演練清單",
    keywordB: "年度風險檢查",
    keywordC: "投資壓測流程",
    closeQuestion: "你有定期驗證策略，還是只希望它會有效？",
    calculatorRoute: "/quick-10",
    calculatorName: "複利美夢 VS 崩盤現實 計算機",
  },
  {
    slug: "quick10-avoid-overoptimistic-return-setting",
    title: "報酬率設太樂觀，崩盤時最容易崩心態",
    subtitle: "先務實，才能長期走得遠。",
    seoTitle: "報酬率怎麼設才不自欺？複利美夢 VS 崩盤現實 計算機提醒",
    metaDescription: "說明過度樂觀報酬假設的風險，幫你建立更穩健的試算基準。",
    focus: "避免過度樂觀",
    keywordA: "報酬率設太樂觀",
    keywordB: "務實報酬設定",
    keywordC: "試算假設風險",
    closeQuestion: "你的數字是在規劃未來，還是在安慰現在？",
    calculatorRoute: "/quick-10",
    calculatorName: "複利美夢 VS 崩盤現實 計算機",
  },
  {
    slug: "quick10-sleep-well-portfolio-design",
    title: "睡得著的投資組合，才是你真正能持有的組合",
    subtitle: "心態穩，才有機會撐過波動。",
    seoTitle: "如何設計睡得著的投資組合？複利美夢 VS 崩盤現實 計算機",
    metaDescription: "用第十台幫你找出能承受波動又能長期持有的投資配置節奏。",
    focus: "睡得著的配置",
    keywordA: "睡得著投資組合",
    keywordB: "可持有配置",
    keywordC: "波動承受度",
    closeQuestion: "你現在的配置，能讓你在大跌時還睡得著嗎？",
    calculatorRoute: "/quick-10",
    calculatorName: "複利美夢 VS 崩盤現實 計算機",
  },
  {
    slug: "quick10-build-30year-antifragile-habit",
    title: "30 年抗震習慣，來自每次逆風都不亂動",
    subtitle: "抗脆弱不是神技，是流程。",
    seoTitle: "如何打造30年抗脆弱投資習慣？複利美夢 VS 崩盤現實 計算機",
    metaDescription: "建立 30 年抗脆弱理財習慣，讓策略在逆風中越跑越穩。",
    focus: "30年抗脆弱習慣",
    keywordA: "抗脆弱投資習慣",
    keywordB: "30年理財紀律",
    keywordC: "逆風投資流程",
    closeQuestion: "你願意用流程取代情緒，換長期穩定嗎？",
    calculatorRoute: "/quick-10",
    calculatorName: "複利美夢 VS 崩盤現實 計算機",
  },
  {
    slug: "quick10-crash-reality-longterm-discipline",
    title: "崩盤現實很痛，但紀律會把你帶回路上",
    subtitle: "最終差距，常在風暴裡被拉開。",
    seoTitle: "崩盤現實下如何守住長期紀律？複利美夢 VS 崩盤現實 計算機",
    metaDescription: "總結崩盤情境下的長期紀律策略，幫你把恐慌轉成可執行行動。",
    focus: "崩盤下長期紀律",
    keywordA: "崩盤如何守紀律",
    keywordB: "長期投資抗壓",
    keywordC: "崩盤現實應對",
    closeQuestion: "下一次大跌來時，你會崩潰，還是照流程前進？",
    calculatorRoute: "/quick-10",
    calculatorName: "複利美夢 VS 崩盤現實 計算機",
  },
];

function buildSections(seed: TopicSeed, calculatorName: string): Quick1ExclusiveSection[] {
  return [
    {
      heading: `先把問題說白：${seed.focus}，不是靠感覺`,
      paragraphs: [
        `很多人一開始都會問：「${seed.focus}到底要怎麼做才對？」`,
        "我通常會先回一句內心戲：\"先別急著找標準答案，先看你現在做不做得到。\"",
        `${calculatorName}的價值很務實：把你現在的月投入、年數，直接翻成看得懂的結果。`,
        "當數字攤開，你就不再靠想像做決策...而是靠可驗證的路線在前進。",
      ],
      bullets: [`🔎 你可能也在找：${seed.keywordA}`, `🔎 你可能也在找：${seed.keywordB}`, `🔎 你可能也在找：${seed.keywordC}`],
    },
    {
      heading: "最常見的卡點：不是不努力，是路線太硬",
      paragraphs: [
        "很多計畫一開始很熱血，三個月後就停下來。不是你不行，而是你把起跑值設得太吃緊。",
        "我自己的原則很簡單：可以慢，但不要斷。因為一旦中斷，重啟的心理成本會比你想像高。",
        "把目標拆成可調旋鈕最實際——提高月投入、延長年數、或先調整生活版本。",
        "你不需要一次完美；你只需要每次都比上一次更可持續。",
      ],
    },
    {
      heading: "給你一套可執行版 ✅",
      paragraphs: [
        "① 先填你「下個月也做得到」的月投入。",
        "② 用 15 / 20 / 25 年三組比較，別只看單一答案。",
        "③ 看月領示意時，問自己一句：\"這個生活版本我願意長期承擔嗎？\"",
        "④ 每 30 天回來校正一次，只調參數，不用自責。",
        "一句話收尾：理財不是比賽誰最猛，而是看誰最能長期不掉線。",
      ],
    },
  ];
}

export const QUICK1_EXCLUSIVE_POSTS: Quick1ExclusivePost[] = TOPIC_SEEDS.map((seed, idx) => {
  const calculatorRoute = seed.calculatorRoute ?? "/quick-1";
  const calculatorName = seed.calculatorName ?? "存股複利計算機";
  const fallbackDate = PUBLISH_DATES[idx] ?? (() => {
    const baseMs = Date.parse("2026-05-04T01:00:00.000Z");
    const isoDate = new Date(baseMs + Math.max(0, idx) * 12 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
    return `${isoDate}T09:00:00+08:00`;
  })();
  const scheduledAt =
    calculatorRoute === "/quick-2"
      ? (QUICK2_PUBLISH_DATES[seed.slug] ?? fallbackDate)
      : calculatorRoute === "/quick-3"
        ? (QUICK3_PUBLISH_DATES[seed.slug] ?? fallbackDate)
        : calculatorRoute === "/quick-5"
          ? (QUICK5_PUBLISH_DATES[seed.slug] ?? fallbackDate)
          : calculatorRoute === "/quick-6"
            ? (QUICK6_PUBLISH_DATES[seed.slug] ?? fallbackDate)
            : calculatorRoute === "/quick-7"
              ? (QUICK7_PUBLISH_DATES[seed.slug] ?? fallbackDate)
              : calculatorRoute === "/quick-8"
                ? (QUICK8_PUBLISH_DATES[seed.slug] ?? fallbackDate)
                : calculatorRoute === "/quick-9"
                  ? (QUICK9_PUBLISH_DATES[seed.slug] ?? fallbackDate)
                  : calculatorRoute === "/quick-10"
                    ? (QUICK10_PUBLISH_DATES[seed.slug] ?? fallbackDate)
          : fallbackDate;
  return {
    slug: seed.slug,
    title: seed.title,
    subtitle: seed.subtitle,
    seoTitle: seed.seoTitle,
    metaDescription: seed.metaDescription,
    publishAtIso: scheduledAt,
    calculatorRoute,
    calculatorTitle: `${calculatorName}（直接放入）`,
    calculatorNote: seed.calculatorNote ?? "先改月投，再改年數，最後看月領示意。先求做得到，再求做得快。",
    sections: buildSections(seed, calculatorName),
    closeQuestion: seed.closeQuestion,
    disclaimer: "本文為情境試算與經驗分享，非投資建議；實際結果受市場、費用、稅務與個人行為影響。",
  };
});

export function getQuick1ExclusivePostBySlug(slug: string): Quick1ExclusivePost | undefined {
  return QUICK1_EXCLUSIVE_POSTS.find((post) => post.slug === slug);
}
